### ISSUE TITLE
Exception in thread "main" javax.ws.rs.ProcessingException: java.net.SocketTimeoutException: Read timed out

### ISSUE THREAD

**Issue by ifourvimal** [docker-java/docker-java#1013]
Hi,

I have to execute docker image using the java code so after a long search I have found this git-hub repo for doing the same.

So I have added the dependency for docker-java to my project and try to run my code as suggested on the wiki.I have followed all the step and while running my program I am getting the below error,

`Exception in thread "main" javax.ws.rs.ProcessingException: java.net.SocketTimeoutException: Read timed out
	at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:481)
	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:252)
	at org.glassfish.jersey.client.JerseyInvocation$3.call(JerseyInvocation.java:724)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:444)
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:720)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:430)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.get(JerseyInvocation.java:321)
	at com.github.dockerjava.jaxrs.SearchImagesCmdExec.execute(SearchImagesCmdExec.java:30)
	at com.github.dockerjava.jaxrs.SearchImagesCmdExec.execute(SearchImagesCmdExec.java:16)
	at com.github.dockerjava.jaxrs.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:23)
	at com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:35)
	at com.pht.RunTask.main(RunTask.java:52)
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:983)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:940)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
	at org.apache.http.impl.conn.LoggingInputStream.read(LoggingInputStream.java:87)
	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
	at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)
	at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:282)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:140)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:167)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:271)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:71)
	at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:435)
	... 14 more
`

Below is my code which I am using,

```
package com.pht;

import java.io.IOException;
import java.util.List;

import com.github.dockerjava.api.DockerClient;
import com.github.dockerjava.api.command.DockerCmdExecFactory;
import com.github.dockerjava.api.model.SearchItem;
import com.github.dockerjava.core.DefaultDockerClientConfig;
import com.github.dockerjava.core.DockerClientBuilder;
import com.github.dockerjava.core.DockerClientConfig;
import com.github.dockerjava.jaxrs.JerseyDockerCmdExecFactory;

public class RunTask {
	
	public static void main(String[] args) throws IOException {
			System.out.println("Hello world!!");
					
			DockerClientConfig config = DefaultDockerClientConfig.createDefaultConfigBuilder()
					  .withDockerHost("tcp://192.168.99.100:2376")
					  .withDockerTlsVerify(true)
					  .withDockerCertPath("C:\\Users\\vimal.darji\\.docker\\machine\\machines\\default").withDockerConfig("C:\\Users\\vimal.darji\\.docker\\machine\\machines\\default\\config.json").build();
			DockerCmdExecFactory dockerCmdExecFactory = new JerseyDockerCmdExecFactory()
					  .withReadTimeout(1000)
					  .withConnectTimeout(1000)
					  .withMaxTotalConnections(100)
					  .withMaxPerRouteConnections(10);
			
			DockerClient dockerClient = DockerClientBuilder.getInstance(config)
						.withDockerCmdExecFactory(dockerCmdExecFactory)
					  .build();
			
			List<SearchItem> dockerSearch = dockerClient.searchImagesCmd("busybox").exec();
			System.out.println("Search returned" + dockerSearch.toString());	
		}	
}
```

Below is my machine details,

```
$ docker-machine ls
NAME      ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER        ERRORS
default   *        virtualbox   Running   tcp://192.168.99.100:2376           v18.03.0-ce
```

Please, anybody, help me on this issue.
I want to run docker command from java code so I have to execute as below 
docker exec -it "docker-image-name" java -jar "jarfile-name"

**Comment by orzeh** [comment]
@ifourvimal you probably set too short time for read timeout (1000ms).

> I want to run docker command from java code so I have to execute as below
docker exec -it "docker-image-name" java -jar "jarfile-name"

You don't have to run your java code inside container in order to communicate with Docker daemon. Or maybe I don't understand your use case :confused:

**Comment by ifourvimal** [comment]
Hi @orzeh Thanks for the quick reply,

Here is my active docker container running,

```
$ docker ps
CONTAINER ID        IMAGE                          COMMAND                  CREATED             STATUS              PORTS                                            NAMES
f37c7ae71e12        tomcat:latest                  "/usr/local/tomcat/b"   2 hours ago         Up 2 hours          0.0.0.0:8080->8080/tcp                           tomcat_docker
f2cc2579b861        java:latest                    "/bin/bash"              2 hours ago         Up 2 hours          0.0.0.0:2377->2377/tcp                           test_docker
673c6617a0d5        mysql                          "docker-entrypoint.s"   2 hours ago         Up 2 hours          0.0.0.0:53306->3306/tcp                          mysql_docker
a76ca8d8f9e4        java:latest                    "/bin/bash"              2 hours ago         Up 2 hours                                                           Client
b0f44aa99170        openlink/virtuoso_opensource   "/opt/virtuoso-opens"   2 hours ago         Up 2 hours          0.0.0.0:1111->1111/tcp, 0.0.0.0:8890->8890/tcp   virtuoso_docker
```

I want to execute test_docker  using the java code.
Normally when I execute using command this will perfectly be running fine inside docker terminal.
`docker exec -it test_docker java -jar test.jar`

I want to use this command inside java code so while searching I found this git-repo which will allow doing so. So I have to try to run test case which will be giving me an error.

for read timeout(1000ms) how do I change it?

**Comment by orzeh** [comment]
> I want to execute test_docker using the java code.

Looking at `docker ps` output I can see that `test_docker` container is currently running on your daemon. So why you want to _execute_ it from java code?

> for read timeout(1000ms) how do I change it?

You set it in your java code:
````java
DockerCmdExecFactory dockerCmdExecFactory = new JerseyDockerCmdExecFactory()
					  .withReadTimeout(1000)
					  .withConnectTimeout(1000)
					  .withMaxTotalConnections(100)
					  .withMaxPerRouteConnections(10);
````

I guess you should go through integration tests in this repository before you start writing your own code.

**Comment by ifourvimal** [comment]
After increasing timeout its solve my problem though for another question which I have I will create new so it would be miss guide.
