### ISSUE TITLE
Unable to connect to a docker swarm.

### ISSUE THREAD

**Issue by mytech1235** [docker-java/docker-java#1024]
Hi

I have a spring boot application where i use the docker api to launch another container to run some tasks. The spring boot app provides rest api, that takes some paramters from the caller, image is one of them. When invoked that rest api, the app will create a container for the image provided. I tested with simple "hello-world" and a custom image and that works fine.

i can run it successfully locally

`java -DDOCKER_HOST=unix:///var/run/docker.sock -jar ./target/application.jar .`

when i run this with a host that is a docker swarm, i see the exception below... i have the certificates in the root of the jar file.

i am creating the docker client as below

`DockerClientConfig config = new Builder().withDockerHost(dockerHost)
                                                 .withDockerTlsVerify(true)
                                                 .withDockerCertPath("/")
                                                 .build();`

threw exception [Request processing failed; nested exception is javax.ws.rs.ProcessingException: org.apache.http.client.ClientProtocolException] with root cause
org.apache.http.ProtocolException: The server failed to respond with a valid HTTP response
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:151) ~[httpclient-4.5.jar!/:4.5]
at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57) ~[httpclient-4.5.jar!/:4.5]
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259) ~[httpcore-4.4.5.jar!/:4.4.5]
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163) ~[httpcore-4.4.5.jar!/:4.4.5]
	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:167) ~[httpclient-4.5.jar!/:4.5]
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273) ~[httpcore-4.4.5.jar!/:4.4.5]
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125) ~[httpcore-4.4.5.jar!/:4.4.5]
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:271) ~[httpclient-4.5.jar!/:4.5]
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184) ~[httpclient-4.5.jar!/:4.5]

**Comment by KostyaSha** [comment]
org.apache.http.ProtocolException: The server failed to respond with a valid HTTP response
at 

Check with what protocol to what protocol do you connect.

**Comment by mytech1235** [comment]
i am using tcp, sorry forgot to mention
`
java -DDOCKER_HOST=tcp://docker.swarm.host:443 -jar ./target/application.jar .
`
i also tried unix:///

**Comment by mytech1235** [comment]
I see that the issue is in closed state, what does that mean?

**Comment by orzeh** [comment]
@mytech1235 you can enable logging in your Spring Boot app and maybe that will give you some hint. Just add `--logging.level.org.apache.http=DEBUG` as a last parameter in command. This should grab some logs from HTTP Client.

**Comment by mytech1235** [comment]
thanks, here is the output

```
2018-04-20 17:22:25.531  INFO 48849 --- [nio-8080-exec-1] o.a.c.c.C.[.[.[/talent-docker-master]    : Initializing Spring FrameworkServlet 'dispatcherServletRegistration'
2018-04-20 17:22:25.531  INFO 48849 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : FrameworkServlet 'dispatcherServletRegistration': initialization started
2018-04-20 17:22:25.551  INFO 48849 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : FrameworkServlet 'dispatcherServletRegistration': initialization completed in 20 ms
2018-04-20 17:22:25.941 DEBUG 48849 --- [nio-8080-exec-1] o.a.h.client.protocol.RequestAddCookies  : CookieSpec selected: default
2018-04-20 17:22:25.950 DEBUG 48849 --- [nio-8080-exec-1] o.a.h.client.protocol.RequestAuthCache   : Auth cache not set in the context
2018-04-20 17:22:25.964 DEBUG 48849 --- [nio-8080-exec-1] o.a.http.impl.execchain.MainClientExec   : Opening connection {}->http://docker.swarm.host:443
2018-04-20 17:22:26.002 DEBUG 48849 --- [nio-8080-exec-1] .i.c.DefaultHttpClientConnectionOperator : Connecting to docker.swarm.host/docker.swarm.IP:443
2018-04-20 17:22:26.015 DEBUG 48849 --- [nio-8080-exec-1] .i.c.DefaultHttpClientConnectionOperator : Connection established 26.57.115.226:54864<->docker.swarm.IP:443
2018-04-20 17:22:26.015 DEBUG 48849 --- [nio-8080-exec-1] o.a.http.impl.execchain.MainClientExec   : Executing request GET /info HTTP/1.1
2018-04-20 17:22:26.015 DEBUG 48849 --- [nio-8080-exec-1] o.a.http.impl.execchain.MainClientExec   : Target auth state: UNCHALLENGED
2018-04-20 17:22:26.016 DEBUG 48849 --- [nio-8080-exec-1] o.a.http.impl.execchain.MainClientExec   : Proxy auth state: UNCHALLENGED
2018-04-20 17:22:26.018 DEBUG 48849 --- [nio-8080-exec-1] org.apache.http.headers                  : http-outgoing-0 >> GET /info HTTP/1.1
2018-04-20 17:22:26.018 DEBUG 48849 --- [nio-8080-exec-1] org.apache.http.headers                  : http-outgoing-0 >> Accept: application/json
2018-04-20 17:22:26.018 DEBUG 48849 --- [nio-8080-exec-1] org.apache.http.headers                  : http-outgoing-0 >> User-Agent: Jersey/2.23.1 (Apache HttpClient 4.5)
2018-04-20 17:22:26.018 DEBUG 48849 --- [nio-8080-exec-1] org.apache.http.headers                  : http-outgoing-0 >> Host: docker.swarm.host:443
2018-04-20 17:22:26.018 DEBUG 48849 --- [nio-8080-exec-1] org.apache.http.headers                  : http-outgoing-0 >> Connection: Keep-Alive
2018-04-20 17:22:26.018 DEBUG 48849 --- [nio-8080-exec-1] org.apache.http.headers                  : http-outgoing-0 >> Accept-Encoding: gzip,deflate
2018-04-20 17:22:26.018 DEBUG 48849 --- [nio-8080-exec-1] org.apache.http.wire                     : http-outgoing-0 >> "GET /info HTTP/1.1[\r][\n]"
2018-04-20 17:22:26.018 DEBUG 48849 --- [nio-8080-exec-1] org.apache.http.wire                     : http-outgoing-0 >> "Accept: application/json[\r][\n]"
2018-04-20 17:22:26.018 DEBUG 48849 --- [nio-8080-exec-1] org.apache.http.wire                     : http-outgoing-0 >> "User-Agent: Jersey/2.23.1 (Apache HttpClient 4.5)[\r][\n]"
2018-04-20 17:22:26.018 DEBUG 48849 --- [nio-8080-exec-1] org.apache.http.wire                     : http-outgoing-0 >> "Host: docker.swarm.host:443[\r][\n]"
2018-04-20 17:22:26.018 DEBUG 48849 --- [nio-8080-exec-1] org.apache.http.wire                     : http-outgoing-0 >> "Connection: Keep-Alive[\r][\n]"
2018-04-20 17:22:26.018 DEBUG 48849 --- [nio-8080-exec-1] org.apache.http.wire                     : http-outgoing-0 >> "Accept-Encoding: gzip,deflate[\r][\n]"
2018-04-20 17:22:26.018 DEBUG 48849 --- [nio-8080-exec-1] org.apache.http.wire                     : http-outgoing-0 >> "[\r][\n]"
2018-04-20 17:22:26.030 DEBUG 48849 --- [nio-8080-exec-1] org.apache.http.wire                     : http-outgoing-0 << "[0x15][0x3][0x1][0x0][0x2][0x2][\n]"
2018-04-20 17:22:26.031 DEBUG 48849 --- [nio-8080-exec-1] o.a.h.i.conn.DefaultHttpResponseParser   : Garbage in response: 
2018-04-20 17:22:26.031 DEBUG 48849 --- [nio-8080-exec-1] org.apache.http.wire                     : http-outgoing-0 << "end of stream"
2018-04-20 17:22:26.031 DEBUG 48849 --- [nio-8080-exec-1] h.i.c.DefaultManagedHttpClientConnection : http-outgoing-0: Close connection
2018-04-20 17:22:26.032 DEBUG 48849 --- [nio-8080-exec-1] h.i.c.DefaultManagedHttpClientConnection : http-outgoing-0: Shutdown connection
2018-04-20 17:22:26.033 DEBUG 48849 --- [nio-8080-exec-1] o.a.http.impl.execchain.MainClientExec   : Connection discarded
2018-04-20 17:22:26.033 DEBUG 48849 --- [nio-8080-exec-1] h.i.c.DefaultManagedHttpClientConnection : http-outgoing-0: Close connection
2018-04-20 17:22:26.044 ERROR 48849 --- [nio-8080-exec-1] .C.[.[.[.[dispatcherServletRegistration] : Servlet.service() for servlet [dispatcherServletRegistration] in context with path [/talent-docker-master] threw exception [Request processing failed; nested exception is javax.ws.rs.ProcessingException: org.apache.http.client.ClientProtocolException] with root cause

org.apache.http.ProtocolException: The server failed to respond with a valid HTTP response
    at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:151) ~[httpclient-4.5.jar!/:4.5]
    at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57) ~[httpclient-4.5.jar!/:4.5]
    at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259) ~[httpcore-4.4.5.jar!/:4.4.5]
    at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163) ~[httpcore-4.4.5.jar!/:4.4.5]
    at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:167) ~[httpclient-4.5.jar!/:4.5]
    at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273) ~[httpcore-4.4.5.jar!/:4.4.5]
    at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125) ~[httpcore-4.4.5.jar!/:4.4.5]
    at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:271) ~[httpclient-4.5.jar!/:4.5]
    at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184) ~[httpclient-4.5.jar!/:4.5]
    at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88) ~[httpclient-4.5.jar!/:4.5]
    at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[httpclient-4.5.jar!/:4.5]
    at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184) ~[httpclient-4.5.jar!/:4.5]
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:71) ~[httpclient-4.5.jar!/:4.5]
    at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:435) ~[jersey-apache-connector-2.23.1.jar!/:na]
    at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:252) ~[jersey-client-2.23.1.jar!/:na]
    at org.glassfish.jersey.client.JerseyInvocation$2.call(JerseyInvocation.java:701) ~[jersey-client-2.23.1.jar!/:na]
    at org.glassfish.jersey.internal.Errors.process(Errors.java:315) ~[jersey-common-2.23.1.jar!/:na]
    at org.glassfish.jersey.internal.Errors.process(Errors.java:297) ~[jersey-common-2.23.1.jar!/:na]
    at org.glassfish.jersey.internal.Errors.process(Errors.java:228) ~[jersey-common-2.23.1.jar!/:na]
    at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:444) ~[jersey-common-2.23.1.jar!/:na]
    at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:697) ~[jersey-client-2.23.1.jar!/:na]
    at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:420) ~[jersey-client-2.23.1.jar!/:na]
    at org.glassfish.jersey.client.JerseyInvocation$Builder.get(JerseyInvocation.java:316) ~[jersey-client-2.23.1.jar!/:na]
    at com.github.dockerjava.jaxrs.InfoCmdExec.execute(InfoCmdExec.java:26) ~[docker-java-3.0.9.jar!/:na]
    at com.github.dockerjava.jaxrs.InfoCmdExec.execute(InfoCmdExec.java:13) ~[docker-java-3.0.9.jar!/:na]
    at com.github.dockerjava.jaxrs.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:23) ~[docker-java-3.0.9.jar!/:na]
    at com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:35) ~[docker-java-3.0.9.jar!/:na]
    at com.adp.talent.tools.docker.controller.DockerMasterController.getInfo(DockerMasterController.java:71) ~[talent-docker-master.jar!/:1.0.0-PRERELEASE-SNAPSHOT]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_162]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_162]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_162]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_162]
    at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) ~[spring-web-4.3.8.RELEASE.jar!/:4.3.8.RELEASE]
    at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133) ~[spring-web-4.3.8.RELEASE.jar!/:4.3.8.RELEASE]
    at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97) ~[spring-webmvc-4.3.8.RELEASE.jar!/:4.3.8.RELEASE]
    at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827) ~[spring-webmvc-4.3.8.RELEASE.jar!/:4.3.8.RELEASE]
    at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738) ~[spring-webmvc-4.3.8.RELEASE.jar!/:4.3.8.RELEASE]
    at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85) ~[spring-webmvc-4.3.8.RELEASE.jar!/:4.3.8.RELEASE]
    at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963) ~[spring-webmvc-4.3.8.RELEASE.jar!/:4.3.8.RELEASE]
    at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897) ~[spring-webmvc-4.3.8.RELEASE.jar!/:4.3.8.RELEASE]
    at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970) ~[spring-webmvc-4.3.8.RELEASE.jar!/:4.3.8.RELEASE]
    at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861) ~[spring-webmvc-4.3.8.RELEASE.jar!/:4.3.8.RELEASE]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:635) ~[tomcat-embed-core-8.5.14.jar!/:8.5.14]
    at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846) ~[spring-webmvc-4.3.8.RELEASE.jar!/:4.3.8.RELEASE]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) ~[tomcat-embed-core-8.5.14.jar!/:8.5.14]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[tomcat-embed-core-8.5.14.jar!/:8.5.14]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.14.jar!/:8.5.14]
    at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) ~[tomcat-embed-websocket-8.5.14.jar!/:8.5.14]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.14.jar!/:8.5.14]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.14.jar!/:8.5.14]
    at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55) ~[spring-boot-1.5.3.RELEASE.jar!/:1.5.3.RELEASE]
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.3.8.RELEASE.jar!/:4.3.8.RELEASE]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.14.jar!/:8.5.14]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.14.jar!/:8.5.14]
    at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:110) ~[spring-boot-actuator-1.5.3.RELEASE.jar!/:1.5.3.RELEASE]
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.3.8.RELEASE.jar!/:4.3.8.RELEASE]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.14.jar!/:8.5.14]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.14.jar!/:8.5.14]
    at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99) ~[spring-web-4.3.8.RELEASE.jar!/:4.3.8.RELEASE]
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.3.8.RELEASE.jar!/:4.3.8.RELEASE]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.14.jar!/:8.5.14]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.14.jar!/:8.5.14]
    at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:105) ~[spring-web-4.3.8.RELEASE.jar!/:4.3.8.RELEASE]
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.3.8.RELEASE.jar!/:4.3.8.RELEASE]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.14.jar!/:8.5.14]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.14.jar!/:8.5.14]
    at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81) ~[spring-web-4.3.8.RELEASE.jar!/:4.3.8.RELEASE]
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.3.8.RELEASE.jar!/:4.3.8.RELEASE]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.14.jar!/:8.5.14]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.14.jar!/:8.5.14]
    at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197) ~[spring-web-4.3.8.RELEASE.jar!/:4.3.8.RELEASE]
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.3.8.RELEASE.jar!/:4.3.8.RELEASE]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.14.jar!/:8.5.14]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.14.jar!/:8.5.14]
    at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:106) ~[spring-boot-actuator-1.5.3.RELEASE.jar!/:1.5.3.RELEASE]
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.3.8.RELEASE.jar!/:4.3.8.RELEASE]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.14.jar!/:8.5.14]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.14.jar!/:8.5.14]
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198) ~[tomcat-embed-core-8.5.14.jar!/:8.5.14]
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat-embed-core-8.5.14.jar!/:8.5.14]
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478) [tomcat-embed-core-8.5.14.jar!/:8.5.14]
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) [tomcat-embed-core-8.5.14.jar!/:8.5.14]
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80) [tomcat-embed-core-8.5.14.jar!/:8.5.14]
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [tomcat-embed-core-8.5.14.jar!/:8.5.14]
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342) [tomcat-embed-core-8.5.14.jar!/:8.5.14]
    at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799) [tomcat-embed-core-8.5.14.jar!/:8.5.14]
    at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-embed-core-8.5.14.jar!/:8.5.14]
    at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:861) [tomcat-embed-core-8.5.14.jar!/:8.5.14]
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1455) [tomcat-embed-core-8.5.14.jar!/:8.5.14]
    at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-8.5.14.jar!/:8.5.14]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_162]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_162]
    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.5.14.jar!/:8.5.14]
    at java.lang.Thread.run(Thread.java:748) [na:1.8.0_162]
```

**Comment by orzeh** [comment]
@mytech1235 response `[0x15][0x3][0x1][0x0][0x2][0x2][\n]` doesn't seem to be a valid HTTP response. Check if you can connect to `http://docker.swarm.host:443`

**Comment by mytech1235** [comment]
That is what is puzzling me, i have a unit test that does the same thing that works fine..
i cannot connect to ```http://docker.swarm.host:443``` from a browser, but i can connect to ```https://docker.swarm.host:443``` which is obvious.

in the code i am using ```tcp```, not ```http/https```

unit test code.
```
DockerClientConfig config = new Builder().withDockerHost("tcp://docker.swarm.host:443")
                                                 .withDockerTlsVerify(true)
                                                 .withDockerCertPath("./src/test/resources")
                                                 .build();
        JerseyDockerCmdExecFactory dockerCmdExecFactory = new JerseyDockerCmdExecFactory();
        dockerCmdExecFactory.withConnectTimeout(50000)
                            .withMaxTotalConnections(100)
                            .withMaxPerRouteConnections(10);

        // create the docker client.
        dockerClient = DockerClientBuilder.getInstance(config)
                                          .withDockerCmdExecFactory(dockerCmdExecFactory).build();
```

in the actual code

```
        String dockerHost = System.getProperty(DOCKER_HOST_KEY);
        DockerClientConfig config = new Builder().withDockerHost(dockerHost)
                                                 .withDockerTlsVerify(true)
                                                 .withDockerCertPath("/")
                                                 .build();

        JerseyDockerCmdExecFactory dockerCmdExecFactory = new JerseyDockerCmdExecFactory();
        dockerCmdExecFactory.withConnectTimeout(DOCKER_CONNECTION_TIMEOUT)
                            .withMaxTotalConnections(MAX_DOCKER_CONNECTIONS)
                            .withReadTimeout(DOCKER_READ_TIMEOUT)
                            .withMaxPerRouteConnections(10);

        // create the docker client.
        return DockerClientBuilder.getInstance(config)
                                  .withDockerCmdExecFactory(dockerCmdExecFactory)
                                  .build();
```

the only difference is read timeout, which is set to 50000

**Comment by orzeh** [comment]
@mytech1235 the cert path is also different

**Comment by mytech1235** [comment]
Same files in two locations.

**Comment by mytech1235** [comment]
Anyone had success with this type of approach?

**Comment by mytech1235** [comment]
the issue seems to be with path to the certificate files.
I have have them in the root of the jar file, looks like withDockerCertPath cannot look inside the jar file?

Trying them outside now.

**Comment by tkesh** [comment]
This is related to the certificate path. Thanks @mytech1235
