### ISSUE TITLE
docker-java fails in OSGi/Karaf context with jersey ResponseProcessingException

### ISSUE THREAD

**Issue by aboudzakaria** [docker-java/docker-java#1027]
I'm trying to include docker-java 3.1.0-RC-2 dependency in an OSGi context and run it inside a karaf runtime. however, I'm getting this exception when executing a simple command like versionCMD

```java
javax.ws.rs.client.ResponseProcessingException: org.glassfish.jersey.message.internal.MessageBodyProviderNotFoundException: MessageBodyReader not found for media type=application/json, type=class com.github.dockerjava.api.model.Version, genericType=class com.github.dockerjava.api.model.Version.
        at org.glassfish.jersey.client.JerseyInvocation.translate(JerseyInvocation.java:875)
        at org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$1(JerseyInvocation.java:767)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:316)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:298)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:229)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:414)
        at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:765)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:428)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.get(JerseyInvocation.java:324)
        at com.github.dockerjava.jaxrs.VersionCmdExec.execute(VersionCmdExec.java:26)
        at com.github.dockerjava.jaxrs.VersionCmdExec.execute(VersionCmdExec.java:13)
        at com.github.dockerjava.jaxrs.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:23)
        at com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:35)
        at com.pqsoft.virtualization.docker.DockerHelper.readServerInfo(DockerHelper.java:57)
        ...
        Caused by: org.glassfish.jersey.message.internal.MessageBodyProviderNotFoundException: MessageBodyReader not found for media type=application/json, type=class com.github.dockerjava.api.model.Version, genericType=class com.github.dockerjava.api.model.Version.
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.aroundReadFrom(ReaderInterceptorExecutor.java:232)
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor.proceed(ReaderInterceptorExecutor.java:156)
	at org.glassfish.jersey.message.internal.MessageBodyFactory.readFrom(MessageBodyFactory.java:1091)
	at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:874)
	at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:808)
	at org.glassfish.jersey.client.ClientResponse.readEntity(ClientResponse.java:321)
	at org.glassfish.jersey.client.JerseyInvocation.translate(JerseyInvocation.java:870)
```

**Comment by orzeh** [comment]
@aboudzakaria unfortunately I don't use Karaf.

I guess the bundle resolved successfully? Is this the full stack trace? This might be some missing import.

**Comment by orzeh** [comment]
@aboudzakaria probably something related to Jersey. Take a look at https://stackoverflow.com/a/25313319

**Comment by aboudzakaria** [comment]
it should be something with jersey, I've already tried every solution on stackoverflow with no luck. all the required bundles are loaded in karaf and looks good, here's the list:
```
Feature contains followed bundles:
  mvn:features/docker-impl/0.1.0-SNAPSHOT
  mvn:io.netty/netty-transport-native-kqueue/4.1.14.Final
  mvn:io.netty/netty-common/4.1.14.Final
  mvn:io.netty/netty-buffer/4.1.14.Final
  mvn:io.netty/netty-transport-native-unix-common/4.1.14.Final
  mvn:io.netty/netty-transport/4.1.14.Final
  mvn:io.netty/netty-resolver/4.1.14.Final
  mvn:com.github.docker-java/docker-java/3.1.0-rc-2
  mvn:com.fasterxml.jackson.jaxrs/jackson-jaxrs-json-provider/2.6.4
  mvn:com.fasterxml.jackson.jaxrs/jackson-jaxrs-base/2.6.4
  mvn:com.fasterxml.jackson.core/jackson-core/2.6.4
  mvn:com.fasterxml.jackson.core/jackson-databind/2.6.4
  mvn:com.fasterxml.jackson.core/jackson-annotations/2.6.0
  mvn:com.fasterxml.jackson.module/jackson-module-jaxb-annotations/2.6.4
  mvn:org.glassfish.jersey.connectors/jersey-apache-connector/2.26
  mvn:org.glassfish.jersey.core/jersey-common/2.26
  mvn:javax.annotation/javax.annotation-api/1.2
  mvn:org.glassfish.hk2/osgi-resource-locator/1.0.1
  mvn:javax.ws.rs/javax.ws.rs-api/2.1
  wrap:mvn:org.apache.httpcomponents/httpcore/4.4.5
  wrap:mvn:org.apache.httpcomponents/httpclient/4.5
  mvn:org.glassfish.jersey.core/jersey-client/2.26
  mvn:org.glassfish.hk2.external/javax.inject/2.5.0-b42
  mvn:org.glassfish.jersey.inject/jersey-hk2/2.26
  mvn:org.glassfish.hk2/hk2-locator/2.5.0-b42
  mvn:org.glassfish.hk2.external/aopalliance-repackaged/2.5.0-b42
  mvn:org.glassfish.hk2/hk2-api/2.5.0-b42
  mvn:org.glassfish.hk2/hk2-utils/2.5.0-b42
  mvn:org.javassist/javassist/3.22.0-CR2
  wrap:mvn:com.kohlschutter.junixsocket/junixsocket-common/2.0.4
  mvn:log4j/log4j/1.2.17
  wrap:mvn:com.kohlschutter.junixsocket/junixsocket-native-common/2.0.4
  wrap:mvn:org.scijava/native-lib-loader/2.0.2
  mvn:org.apache.commons/commons-compress/1.12
  mvn:commons-codec/commons-codec/1.10
  mvn:commons-lang/commons-lang/2.6
  mvn:commons-io/commons-io/2.5
  mvn:org.slf4j/jcl-over-slf4j/1.7.21
  mvn:com.google.guava/guava/19.0
  mvn:org.bouncycastle/bcpkix-jdk15on/1.54
  mvn:org.bouncycastle/bcprov-jdk15on/1.54
  mvn:io.netty/netty-codec-http/4.1.14.Final
  mvn:io.netty/netty-codec/4.1.14.Final
  mvn:io.netty/netty-handler/4.1.14.Final
  mvn:io.netty/netty-handler-proxy/4.1.14.Final
  mvn:io.netty/netty-codec-socks/4.1.14.Final
  mvn:io.netty/netty-transport-native-epoll/4.1.14.Final/jar/linux-x86_64
  mvn:org.slf4j/slf4j-api/1.7.21
  mvn:org.slf4j/slf4j-simple/1.7.21
  mvn:com.google.code.gson/gson/2.7
```

**Comment by aboudzakaria** [comment]
I was able to fix this by stating these two dependencies directly in the module that depends on docker-java,
```xml
        <dependency>
            <groupId>org.glassfish.jersey.media</groupId>
            <artifactId>jersey-media-json-jackson</artifactId>
            <version>${jersey.version}</version>
        </dependency>
        <dependency>
            <groupId>org.glassfish.jersey.core</groupId>
            <artifactId>jersey-server</artifactId>
            <version>${jersey.version}</version>
        </dependency>
```
