### ISSUE TITLE
Docker Java on Raspberry Pi 3

### ISSUE THREAD

**Issue by bandarapusatyam** [docker-java/docker-java#1051]
Hi All,

I used docker java library to join the docker swarm in Raspberry Pi3. Got following error message, but works fine in Ubuntu. I know its related to netty library, and also tried VM suggestions, but non of them worked for me.  Any suggestions or workaround to resolve this issue appreciated.

Code used:  `DockerClient client; = DockerClientBuilder.getInstance()
				.withDockerCmdExecFactory((new NettyDockerCmdExecFactory()).withConnectTimeout(10 * 1000)).build();`

Error message: 

Java HotSpot(TM) Client VM warning: You have loaded library /tmp/libnetty-transport-native-epoll5058740718546369006.so which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.
Exception in thread "main" java.lang.UnsatisfiedLinkError: failed to load the required native library
	at io.netty.channel.epoll.Epoll.ensureAvailability(Epoll.java:78)
	at io.netty.channel.epoll.EpollEventLoop.<clinit>(EpollEventLoop.java:53)
	at io.netty.channel.epoll.EpollEventLoopGroup.newChild(EpollEventLoopGroup.java:134)
	at io.netty.channel.epoll.EpollEventLoopGroup.newChild(EpollEventLoopGroup.java:35)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:84)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:58)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:47)
	at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:59)
	at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:104)
	at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:91)
	at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:68)
	at com.github.dockerjava.netty.NettyDockerCmdExecFactory$UnixDomainSocketInitializer.epollGroup(NettyDockerCmdExecFactory.java:144)
	at com.github.dockerjava.netty.NettyDockerCmdExecFactory$UnixDomainSocketInitializer.init(NettyDockerCmdExecFactory.java:136)
	at com.github.dockerjava.netty.NettyDockerCmdExecFactory.init(NettyDockerCmdExecFactory.java:109)
	at com.github.dockerjava.core.DockerClientImpl.withDockerCmdExecFactory(DockerClientImpl.java:188)
	at com.github.dockerjava.core.DockerClientBuilder.build(DockerClientBuilder.java:45)

Caused by: java.lang.ExceptionInInitializerError
	at io.netty.channel.epoll.Epoll.<clinit>(Epoll.java:33)
	... 18 more
Caused by: java.lang.IllegalArgumentException: Failed to load any of the given libraries: [netty-transport-native-epoll, netty_transport_native_epoll]
	at io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:180)
	at io.netty.channel.epoll.Native.loadNativeLibrary(Native.java:195)
	at io.netty.channel.epoll.Native.<clinit>(Native.java:61)

**Comment by adrians** [comment]
Hello,

I've just encountered this issue on an ARM64 target. The issue is with the `docker-java-api` extension[1] (version 3.0.14 at the moment, sha1 `68c9abe6554b530eac0a65f96de6d525b7f6d7a2`).

### Root cause

Basically, the Docker interface inside Docker tries to instantiate a `io.netty.channel.epoll.EpollEventLoopGroup` class, which is inside the netty-transport-native-epoll library and fails, as the Java Runtime cannot load that jar.

That jar contains an x86_64 binary file, which gets rejected by the Java Runtime (as we're running on arm64).

### Investigating the issue (strange archive mismatch)

The `docker-java-api` extension bundles a jar at `/WEB-INF/lib/netty-transport-native-epoll-4.1.11.Final.jar` (sha1sum `26e02ff1a85393138c29ce9af1427436a8336ff3`). This jar contains a binary file at `/META-INF/native/libnetty-transport-native-epoll.so` (sha1sum `f00da0ee78220faab6b10a6f6fc39488320ffe7b`) which is compiled for x86_64 targets.

```
$ file libnetty-transport-native-epoll.so

libnetty-transport-native-epoll.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, not stripped
```

The weird thing is that when downloading the same library using maven[2], even though the filenames match (`netty-transport-native-epoll-4.1.11.Final.jar`), the sha1 sum is different (`db6234a77e9776a7db4eca0824f3c65036c6e419`) and that shared object does not exist.

Also, the timestamp of `libnetty-transport-native-epoll.so` in the jar is really similar (11 may 2017 16:29 , within 5 minutes of the rest of the files except `/META-INF/maven/io.netty/netty-transport-native-epoll/` which has a timestamp of 11 may 2018 16:02).

I'm not really familiar with the Java library ecosystem to dig deeper... but for me it seems weird.

### Workaround
You can try to manually re-compile the netty library and replace the incompatible jar. Didn't attempt it though (just moved to a x86_64 machine instead).

Best regards,
/Adrian

[1] https://updates.jenkins-ci.org/download/plugins/docker-java-api/
[2] http://central.maven.org/maven2/io/netty/netty-transport-native-epoll/4.1.11.Final/netty-transport-native-epoll-4.1.11.Final.jar

**Comment by bsideup** [comment]
Only x86_64 architecture is supported. Consider providing your own `DockerHttpClient`.
