### ISSUE TITLE
Exception:  No enum constant com.github.dockerjava.api.model.TaskState.REMOVE

### ISSUE THREAD

**Issue by kamalhakim** [docker-java/docker-java#1065]
I recieve the below exception when I try to fetch the number of tasks for a docker service like the following:  

`List<Task> tasks = client().listTasksCmd().withServiceFilter(nameFilter).exec();`

I use the latest release of the docker-java:

```
    <dependency>
      <groupId>com.github.docker-java</groupId>
      <artifactId>docker-java</artifactId>
      <version>3.1.0-rc-3</version>
    </dependency>
```

This exception happens when I use the call right after I have issued a scale-down call. 

```
Exception in thread "main" javax.ws.rs.client.ResponseProcessingException: com.fasterxml.jackson.databind.JsonMappingException: Can not construct instance of com.github.dockerjava.api.model.TaskState, problem: No enum constant com.github.dockerjava.api.model.TaskState.REMOVE
 at [Source: org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream@5669c5fb; line: 1, column: 2697] (through reference chain: java.util.ArrayList[1]->com.github.dockerjava.api.model.Task["DesiredState"])
	at org.glassfish.jersey.client.JerseyInvocation.translate(JerseyInvocation.java:940)
	at org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$2(JerseyInvocation.java:787)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:316)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:298)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:229)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:414)
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:785)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:438)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.get(JerseyInvocation.java:329)
	at com.github.dockerjava.jaxrs.ListTasksCmdExec.execute(ListTasksCmdExec.java:36)
	at com.github.dockerjava.jaxrs.ListTasksCmdExec.execute(ListTasksCmdExec.java:17)
	at com.github.dockerjava.jaxrs.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:23)
	at com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:35)
	at com.github.dockerjava.core.command.ListTasksCmdImpl.exec(ListTasksCmdImpl.java:12)

```

Any idea?

**Comment by kamalhakim** [comment]
Update: If I prolong the call (around 30 sec) after the scale-down call then it works.

**Comment by KostyaSha** [comment]
Change is in master, will prepare new release after solve #1064

**Comment by kamalhakim** [comment]
Great Thanks!
