### ISSUE TITLE
 InjectionManagerFactory not found

### ISSUE THREAD

**Issue by ThePinkPanther** [docker-java/docker-java#1151]
I'm using   `'com.github.docker-java:docker-java:3.0.14'`
On a spring boot class 
    `classpath "org.springframework.boot:spring-boot-gradle-plugin:2.1.0.M4"`

Java 8

When I run 
```
 client.createContainerCmd("imageName")
   // set all configuration here
  .exec()
```

I get

`java.lang.IllegalStateException: InjectionManagerFactory not found.`

```

Caused by: java.lang.IllegalStateException: InjectionManagerFactory not found.
	at org.glassfish.jersey.internal.inject.Injections.lambda$lookupInjectionManagerFactory$0(Injections.java:98) ~[jersey-common-2.27.jar:na]
	at java.util.Optional.orElseThrow(Optional.java:290) ~[na:1.8.0_131]
	at org.glassfish.jersey.internal.inject.Injections.lookupInjectionManagerFactory(Injections.java:98) ~[jersey-common-2.27.jar:na]
	at org.glassfish.jersey.internal.inject.Injections.createInjectionManager(Injections.java:68) ~[jersey-common-2.27.jar:na]
	at org.glassfish.jersey.client.ClientConfig$State.initRuntime(ClientConfig.java:432) ~[jersey-client-2.27.jar:na]
	at org.glassfish.jersey.internal.util.collection.Values$LazyValueImpl.get(Values.java:341) ~[jersey-common-2.27.jar:na]
	at org.glassfish.jersey.client.ClientConfig.getRuntime(ClientConfig.java:826) ~[jersey-client-2.27.jar:na]
	at org.glassfish.jersey.client.ClientRequest.getConfiguration(ClientRequest.java:285) ~[jersey-client-2.27.jar:na]
	at org.glassfish.jersey.client.JerseyInvocation.validateHttpMethodAndEntity(JerseyInvocation.java:143) ~[jersey-client-2.27.jar:na]
	at org.glassfish.jersey.client.JerseyInvocation.<init>(JerseyInvocation.java:112) ~[jersey-client-2.27.jar:na]
	at org.glassfish.jersey.client.JerseyInvocation.<init>(JerseyInvocation.java:108) ~[jersey-client-2.27.jar:na]
	at org.glassfish.jersey.client.JerseyInvocation.<init>(JerseyInvocation.java:99) ~[jersey-client-2.27.jar:na]
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:456) ~[jersey-client-2.27.jar:na]
	at org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:357) ~[jersey-client-2.27.jar:na]
	at com.github.dockerjava.jaxrs.CreateContainerCmdExec.execute(CreateContainerCmdExec.java:34) ~[docker-java-3.0.14.jar:na]
	at com.github.dockerjava.jaxrs.CreateContainerCmdExec.execute(CreateContainerCmdExec.java:15) ~[docker-java-3.0.14.jar:na]
	at com.github.dockerjava.jaxrs.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:23) ~[docker-java-3.0.14.jar:na]
	at com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:35) ~[docker-java-3.0.14.jar:na]
	at com.github.dockerjava.core.command.CreateContainerCmdImpl.exec(CreateContainerCmdImpl.java:177) ~[docker-java-3.0.14.jar:na]
	at org.avero.mngo.masternode.Application.run(Application.java:54) [classes/:na]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:835) [spring-boot-2.1.0.M4.jar:2.1.0.M4]
	... 5 common frames omitted
```

**Comment by KostyaSha** [comment]
Sorry, i don't know. It's library error. Maybe try to google to get solutions for jersey library.

**Comment by ThePinkPanther** [comment]
I don't really have a direct dependency to jersey, so it's unlikely that my dependencies broke it

**Comment by ThePinkPanther** [comment]
By the way, this error no longer occurs when I switched to 'com.github.docker-java:docker-java:3.1.0-rc-2'
