### ISSUE TITLE
build Image from ECR: "no basic auth credentials" even after "login success"

### ISSUE THREAD

**Issue by keaxu-exp** [docker-java/docker-java#1173]
Trying to build an image based on an ECR image:

Dockerfile looks like this:
```
FROM {aws_account}.dkr.ecr.us-west-2.amazonaws.com/my-base

{other docker file cmd ...}

```
I am calling:
```
String imageId = dockerClient.buildImageCmd(dockerfile).exec(new BuildImageResultCallbackImpl()).awaitImageId();
```
And I get:
```
Exception in thread "pool-2-thread-1" com.github.dockerjava.api.exception.DockerClientException: Could not build image: Get https://{aws_account}.dkr.ecr.us-west-2.amazonaws.com/v2/my-base/manifests/latest: no basic auth credentials
	at com.github.dockerjava.core.command.BuildImageResultCallback.getImageId(BuildImageResultCallback.java:79)
	at com.github.dockerjava.core.command.BuildImageResultCallback.awaitImageId(BuildImageResultCallback.java:51)
```

Here is my client config:
```
    @Bean
    DockerClient dockerClient() {
        GetAuthorizationTokenResult result = amazonECR().getAuthorizationToken(new GetAuthorizationTokenRequest());

        String decodedToken = new String(Base64.getDecoder().decode(result.getAuthorizationData().get(0).getAuthorizationToken()));

        String[] registryUsernamePasswordPair = decodedToken.split(":");

        DockerClientConfig config = DefaultDockerClientConfig.createDefaultConfigBuilder()
                .withRegistryUsername(registryUsernamePasswordPair[0])
                .withRegistryPassword(registryUsernamePasswordPair[1])
                .withRegistryUrl(result.getAuthorizationData().get(0).getProxyEndpoint())
                .build();

        return DockerClientBuilder.getInstance(config).build();
    }
```

I can see login success when I call:
```
AuthResponse authResponse = dockerClient().authCmd().exec();
```

```
2019-03-11 17:37:30.557 level=DEBUG thread=main logger=JerseyDockerCmdExecFactory message=4 * Client response received on thread main
4 < 200
4 < Api-Version: 1.38
4 < Content-Length: 48
4 < Content-Type: application/json
4 < Date: Mon, 11 Mar 2019 17:37:30 GMT
4 < Docker-Experimental: false
4 < Ostype: linux
4 < Server: Docker/18.06.2-ce (linux)
{"IdentityToken":"","Status":"Login Succeeded"}
```

**Comment by adeaner** [comment]
I am getting similar issue. When pulling from ECR, I get ```com.github.dockerjava.api.exception.NotFoundException: Status 404: {"message":"No such image: <image name>} ```, but works fine from CLI.

**Comment by nineinchnick** [comment]
I'm getting the same issue, can we reopen this?
