### ISSUE TITLE
Error: javax.ws.rs.ProcessingException while execute any command

### ISSUE THREAD

**Issue by odravison** [docker-java/docker-java#1192]
Hello guys, 

I hope to be doing nothing wrong in report this error, If I do, I'm sorry

I trying to execute a command just after build `DockerClient` class. I tried to execute PingCmd and just to make sure that this error isn't in the method I tried to list all volumes, but seems this is the same error.

Below is the code and more detailed:

CODE EXECUTED:
```
/**
		 * Initializing docker client
		 */
		DockerClientConfig config = DefaultDockerClientConfig.createDefaultConfigBuilder()
		    .withDockerHost(BusinessIntegrationServiceImpl.DOCKER_SOCK_PATH)
		    .withRegistryUrl(BusinessIntegrationServiceImpl.DOCKER_URL_REPOSITORY)
		    .withRegistryUsername(BusinessIntegrationServiceImpl.DOCKER_USERNAME_REPOSITORY)
		    .withRegistryPassword(BusinessIntegrationServiceImpl.DOCKER_PASSWORD_REPOSITORY)
		    .withRegistryEmail(BusinessIntegrationServiceImpl.DOCKER_EMAIL_REPOSITORY)
		    .build();

		this.dockerClient = DockerClientBuilder.getInstance(config).build();
		
		this.log.info(" ================ Trying to do a ping in docker soc");
		try {
			ListVolumesResponse volumes = this.dockerClient.listVolumesCmd().exec();
			volumes.getVolumes();
		} catch (Exception e) {
			this.log.info(" ============= ERROR: {}", e.getMessage());
			
			e.printStackTrace();
		}
```

ERROR OUTPUT:
```
2019-05-02 16:55:08.451  INFO 22790 --- [  restartedMain] b.c.k.s.admin.config.WebConfigurer       : Web application configuration, using profiles: swagger
2019-05-02 16:55:08.451 DEBUG 22790 --- [  restartedMain] b.c.k.s.admin.config.WebConfigurer       : Initializing Metrics registries
2019-05-02 16:55:08.452 DEBUG 22790 --- [  restartedMain] b.c.k.s.admin.config.WebConfigurer       : Registering Metrics Filter
2019-05-02 16:55:08.452 DEBUG 22790 --- [  restartedMain] b.c.k.s.admin.config.WebConfigurer       : Registering Metrics Servlet
2019-05-02 16:55:08.454  INFO 22790 --- [  restartedMain] b.c.k.s.admin.config.WebConfigurer       : Web application fully configured
2019-05-02 16:55:08.840  WARN 22790 --- [  restartedMain] o.f.core.internal.command.DbMigrate      : outOfOrder mode is active. Migration of schema "public" may not be reproducible.
2019-05-02 16:55:11.819  INFO 22790 --- [  restartedMain] k.s.a.s.i.BusinessIntegrationServiceImpl :  ================ Trying to do a ping in docker soc
2019-05-02 16:55:11.835  WARN 22790 --- [  restartedMain] ationConfigEmbeddedWebApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'businessIntegrationServiceImpl' defined in file [/home/kaztor/projetos/ksc-showcase-cloud/ksc-admin-services/bin/br/com/kaztor/showcase/admin/service/impl/BusinessIntegrationServiceImpl.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [br.com.kaztor.showcase.admin.service.impl.BusinessIntegrationServiceImpl]: Constructor threw exception; nested exception is java.lang.NoSuchMethodError: javax.ws.rs.core.MultivaluedMap.addAll(Ljava/lang/Object;[Ljava/lang/Object;)V
2019-05-02 16:55:11.837  WARN 22790 --- [  restartedMain] c.h.h.instance.HazelcastInstanceFactory  : hibernate.cache.hazelcast.shutdown_on_session_factory_close property is set to 'false'. Leaving current HazelcastInstance active! (Warning: Do not disable Hazelcast hazelcast.shutdownhook.enabled property!)
2019-05-02 16:55:11.844  INFO 22790 --- [  restartedMain] b.c.k.s.admin.config.CacheConfiguration  : Closing Cache Manager
2019-05-02 16:55:11.858  WARN 22790 --- [  restartedMain] .s.c.a.CommonAnnotationBeanPostProcessor : Invocation of destroy method failed on bean with name 'scopedTarget.eurekaClient': org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'amazonS3': Cannot resolve reference to bean 'org.springframework.cloud.aws.core.credentials.CredentialsProviderFactoryBean.BEAN_NAME' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationNotAllowedException: Error creating bean with name 'credentialsProvider': Singleton bean creation not allowed while singletons of this factory are in destruction (Do not request a bean from a BeanFactory in a destroy method implementation!)
2019-05-02 16:55:11.875 ERROR 22790 --- [  restartedMain] o.s.boot.SpringApplication               : Application startup failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'businessIntegrationServiceImpl' defined in file [/home/kaztor/projetos/ksc-showcase-cloud/ksc-admin-services/bin/br/com/kaztor/showcase/admin/service/impl/BusinessIntegrationServiceImpl.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [br.com.kaztor.showcase.admin.service.impl.BusinessIntegrationServiceImpl]: Constructor threw exception; nested exception is java.lang.NoSuchMethodError: javax.ws.rs.core.MultivaluedMap.addAll(Ljava/lang/Object;[Ljava/lang/Object;)V
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:279)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1193)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1095)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:513)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
	at br.com.kaztor.showcase.admin.AdminApp.main(AdminApp.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [br.com.kaztor.showcase.admin.service.impl.BusinessIntegrationServiceImpl]: Constructor threw exception; nested exception is java.lang.NoSuchMethodError: javax.ws.rs.core.MultivaluedMap.addAll(Ljava/lang/Object;[Ljava/lang/Object;)V
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:154)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:122)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:271)
	... 21 common frames omitted
Caused by: java.lang.NoSuchMethodError: javax.ws.rs.core.MultivaluedMap.addAll(Ljava/lang/Object;[Ljava/lang/Object;)V
	at org.glassfish.jersey.client.ClientRequest.accept(ClientRequest.java:336)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.accept(JerseyInvocation.java:240)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.accept(JerseyInvocation.java:163)
	at com.github.dockerjava.jaxrs.ListVolumesCmdExec.execute(ListVolumesCmdExec.java:34)
	at com.github.dockerjava.jaxrs.ListVolumesCmdExec.execute(ListVolumesCmdExec.java:16)
	at com.github.dockerjava.jaxrs.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:23)
	at com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:35)
	at br.com.kaztor.showcase.admin.service.impl.BusinessIntegrationServiceImpl.<init>(BusinessIntegrationServiceImpl.java:173)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:142)
	... 23 common frames omitted
```

The DockerClient is configured and the method is called just in Spring Bean initialization time of this class.

Hope to helps anyone with this error report.

**Comment by odravison** [comment]
I solve this issue.
The problem was jersey dependency conflict. I meaning ... my project was using an older jersey version that doesn't have a such method.

In case of someone have this problem too, solution is:
Add jersey-client, jersey-server, jersey-commons,dependency in 2.27 version with `force = true` flag
I'm talking about Gradle Projects

Like this:
```
        compile('org.glassfish.jersey.core:jersey-client:2.27'){
		force = true
	}
	compile('org.glassfish.jersey.core:jersey-server:2.27'){
		force = true
	}
	
	compile('org.glassfish.jersey.core:jersey-common:2.27') {
		force = true
	}
    
``` 

Closing this issue.
