### ISSUE TITLE
DockerClientBuilder.getInstance("tcp://XXXX:2375").build() ClassNotFoundException

### ISSUE THREAD

**Issue by Chenberg** [docker-java/docker-java#1227]
docker-java 3.0.14
DockerClient dockerClient 1 = DockerClientBuilder. getInstance ("tcp://XXXX:2375"). build ();
Execution is normal in main method, but error is reported in Web environment:
========================
java.lang.RuntimeException: java.lang.ClassNotFoundException: Provider org.glassfish.jersey.internal.RuntimeDelegateImpl could not be instantiated: java.lang.ClassCastException: org.jvnet.hk2.internal.ServiceLocatorImpl cannot be cast to org.jvnet.hk2.internal.JrServiceLocator
	at javax.ws.rs.ext.RuntimeDelegate.findDelegate(RuntimeDelegate.java:152)
	at javax.ws.rs.ext.RuntimeDelegate.getInstance(RuntimeDelegate.java:120)
	at javax.ws.rs.core.UriBuilder.newInstance(UriBuilder.java:95)
	at javax.ws.rs.core.UriBuilder.fromUri(UriBuilder.java:119)
	at org.glassfish.jersey.client.JerseyWebTarget.<init>(JerseyWebTarget.java:71)
	at org.glassfish.jersey.client.JerseyClient.target(JerseyClient.java:290)
	at org.glassfish.jersey.client.JerseyClient.target(JerseyClient.java:76)
	at com.github.dockerjava.jaxrs.JerseyDockerCmdExecFactory.init(JerseyDockerCmdExecFactory.java:237)
	at com.github.dockerjava.core.DockerClientImpl.withDockerCmdExecFactory(DockerClientImpl.java:161)
	at com.github.dockerjava.core.DockerClientBuilder.build(DockerClientBuilder.java:47)
Caused by: java.lang.ClassNotFoundException: Provider org.glassfish.jersey.internal.RuntimeDelegateImpl could not be instantiated: java.lang.ClassCastException: org.jvnet.hk2.internal.ServiceLocatorImpl cannot be cast to org.jvnet.hk2.internal.JrServiceLocator
	at javax.ws.rs.ext.FactoryFinder.newInstance(FactoryFinder.java:122)
	at javax.ws.rs.ext.FactoryFinder.find(FactoryFinder.java:225)
	at javax.ws.rs.ext.RuntimeDelegate.findDelegate(RuntimeDelegate.java:135)
	... 40 more
Caused by: java.lang.ClassCastException: org.jvnet.hk2.internal.ServiceLocatorImpl cannot be cast to org.jvnet.hk2.internal.JrServiceLocator
	at org.jvnet.hk2.external.generator.ServiceLocatorGeneratorImpl.create(ServiceLocatorGeneratorImpl.java)
	at org.glassfish.hk2.internal.ServiceLocatorFactoryImpl.internalCreate(ServiceLocatorFactoryImpl.java:289)
	at org.glassfish.hk2.internal.ServiceLocatorFactoryImpl.create(ServiceLocatorFactoryImpl.java:270)
	at org.glassfish.jersey.internal.inject.Injections._createLocator(Injections.java:138)
	at org.glassfish.jersey.internal.inject.Injections.createLocator(Injections.java:109)
	at org.glassfish.jersey.internal.RuntimeDelegateImpl.<init>(RuntimeDelegateImpl.java:63)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at javax.ws.rs.ext.FactoryFinder.newInstance(FactoryFinder.java:118)
	... 42 more

**Comment by KostyaSha** [comment]
3.0 is not supported anymore
