### ISSUE TITLE
java.lang.ClassCastException: org.jvnet.hk2.internal.ServiceLocatorImpl cannot be cast to org.jvnet.hk2.internal.JrServiceLocator

### ISSUE THREAD

**Issue by Chenberg** [docker-java/docker-java#1229]
docker-java 3.1.5
List<Container> containerList=dockerClient.listContainersCmd().exec();
Execution is normal in main method, but error is reported in Web environment:

2019-07-30 08:56:06,049 - com.github.dockerjava.core.command.AbstrDockerCmd -121431 [http-apr-8081-exec-6] 34 DEBUG  - Cmd: -1,<null>,false,<null>,<null>,com.github.dockerjava.core.util.FiltersBuilder@0,com.github.dockerjava.jaxrs.ListContainersCmdExec@443a56ac
2019-07-30 08:56:06,061 - com.github.dockerjava.jaxrs.ListContainersCmdExec -121443 [http-apr-8081-exec-6] 45 TRACE  - GET: JerseyWebTarget { http://X.X.X.X:2375/containers/json }
2019-07-30 08:56:07,645 - com.originsys.eapcode.action.CgComponentList -123027 [http-apr-8081-exec-6] 103 ERROR  - e
java.lang.ClassCastException: org.jvnet.hk2.internal.ServiceLocatorImpl cannot be cast to org.jvnet.hk2.internal.JrServiceLocator
	at org.jvnet.hk2.external.generator.ServiceLocatorGeneratorImpl.create(ServiceLocatorGeneratorImpl.java)
	at org.glassfish.hk2.internal.ServiceLocatorFactoryImpl.internalCreate(ServiceLocatorFactoryImpl.java:289)
	at org.glassfish.hk2.internal.ServiceLocatorFactoryImpl.create(ServiceLocatorFactoryImpl.java:245)
	at org.glassfish.jersey.inject.hk2.AbstractHk2InjectionManager.createLocator(AbstractHk2InjectionManager.java:114)
	at org.glassfish.jersey.inject.hk2.AbstractHk2InjectionManager.<init>(AbstractHk2InjectionManager.java:86)
	at org.glassfish.jersey.inject.hk2.ImmediateHk2InjectionManager.<init>(ImmediateHk2InjectionManager.java:62)
	at org.glassfish.jersey.inject.hk2.Hk2InjectionManagerFactory$Hk2InjectionManagerStrategy$1.createInjectionManager(Hk2InjectionManagerFactory.java:79)
	at org.glassfish.jersey.inject.hk2.Hk2InjectionManagerFactory.create(Hk2InjectionManagerFactory.java:97)
	at org.glassfish.jersey.internal.inject.InjectionManagerFactory.create(InjectionManagerFactory.java:56)
	at org.glassfish.jersey.internal.inject.Injections.createInjectionManager(Injections.java:68)
	at org.glassfish.jersey.client.ClientConfig$State.initRuntime(ClientConfig.java:432)
	at org.glassfish.jersey.internal.util.collection.Values$LazyValueImpl.get(Values.java:341)
	at org.glassfish.jersey.client.ClientConfig.getRuntime(ClientConfig.java:826)
	at org.glassfish.jersey.client.ClientRequest.getConfiguration(ClientRequest.java:285)
	at org.glassfish.jersey.client.JerseyInvocation.validateHttpMethodAndEntity(JerseyInvocation.java:143)
	at org.glassfish.jersey.client.JerseyInvocation.<init>(JerseyInvocation.java:112)
	at org.glassfish.jersey.client.JerseyInvocation.<init>(JerseyInvocation.java:108)
	at org.glassfish.jersey.client.JerseyInvocation.<init>(JerseyInvocation.java:99)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:438)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.get(JerseyInvocation.java:329)
	at com.github.dockerjava.jaxrs.ListContainersCmdExec.execute(ListContainersCmdExec.java:47)
	at com.github.dockerjava.jaxrs.ListContainersCmdExec.execute(ListContainersCmdExec.java:19)
	at com.github.dockerjava.jaxrs.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:23)
	at com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:35)
	at com.originsys.eapcode.action.CgComponentList.execute(CgComponentList.java:100)
http://X.X.X.X:2375/containers/json -- This url returns the correct JSON data
CreateContainerResponse container = CgComponentList.dockerClient.createContainerCmd("eap4base")
			                .withName(cgComponent.getComponent_id())
			                .withVolumes(volume1)
			                .withHostConfig(new HostConfig().withPortBindings(portBindings))
			                .withBinds(new Bind("/www/eapcode/eap4-common/classes", volume1))
			                .withExposedPorts(tcp8080).exec();
This command also throws errors:
2019-07-30 09:25:54,027 - com.github.dockerjava.jaxrs.CreateContainerCmdExec -1909409 [http-apr-8081-exec-10] 31 TRACE  - POST: JerseyWebTarget { http://X.X.X.X:2375/containers/create?name=testttt } 
2019-07-30 09:25:54,064 - com.originsys.eapcode.action.CgComponentPost -1909446 [http-apr-8081-exec-10] 214 ERROR  - sql错误：
java.lang.ClassCastException: org.jvnet.hk2.internal.ServiceLocatorImpl cannot be cast to org.jvnet.hk2.internal.JrServiceLocator
	at org.jvnet.hk2.external.generator.ServiceLocatorGeneratorImpl.create(ServiceLocatorGeneratorImpl.java)
	at org.glassfish.hk2.internal.ServiceLocatorFactoryImpl.internalCreate(ServiceLocatorFactoryImpl.java:289)
	at org.glassfish.hk2.internal.ServiceLocatorFactoryImpl.create(ServiceLocatorFactoryImpl.java:245)
Thank you very much.

**Comment by Chenberg** [comment]
I found the reason, because I used Jrebel, a hot deployment plug-in, which is caused by some kind of classloader mechanism, in the production environment will not be a problem, close the problem, thank you.
