### ISSUE TITLE
DockerClient crashes on JDK 11.0.4/12.0.2 on macOS only

### ISSUE THREAD

**Issue by nicholas-s-perkins** [docker-java/docker-java#1233]
Hello,
We use testcontainers for running some tests, and when we tried to update to the latest JDK 12 we were having issues, but only for our macOS people.  We tried this with jdk 12.0.2 on Windows 10 and Ubuntu 16.04 and it seemed to work fine.

**docker-java:** 1.3.5
**macOs:** Mojave
**jdk:** adoptopenjdk:12.0.2/11.0.4

I created a small repo that does something basic to reproduce the error if that's interesting: https://github.com/nicholas-s-perkins/test-docker-java.

I attempting to create a `DockerClient` in the same way that testcontainers does for mac.
Checking the [12.0.2 release notes](https://www.oracle.com/technetwork/java/javase/12-0-2-relnotes-5480112.html), there was a security patch at affected other java versions, and I found that also updating to the latest `11.0.4` causes it to break on mac as well with this jdk to crash matrix:

| Code runs ✅   |Code crashes ❌  |
| ------------- | ------------- |
| 11.0.3  | 11.0.4  |
| 12.0.1  | 12.0.2 |

This is the basic code:
```java
DockerClientConfig config = DefaultDockerClientConfig.createDefaultConfigBuilder()
        .withDockerHost("unix:///var/run/docker.sock")
        .withDockerTlsVerify(false)
        .withRegistryUrl("https://index.docker.io/v1/")
        .build();

DockerClient client = DockerClientBuilder.getInstance(config).build();
client.listImagesCmd().exec().forEach(System.out::println);

```
This is the output error:
```
Exception in thread "main" javax.ws.rs.ProcessingException: java.io.IOException: Couldn't load native library
	at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:496)
	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:278)
	at org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$2(JerseyInvocation.java:787)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:316)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:298)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:229)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:414)
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:785)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:438)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.get(JerseyInvocation.java:329)
	at com.github.dockerjava.jaxrs.ListImagesCmdExec.execute(ListImagesCmdExec.java:43)
	at com.github.dockerjava.jaxrs.ListImagesCmdExec.execute(ListImagesCmdExec.java:19)
	at com.github.dockerjava.jaxrs.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:23)
	at com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:35)
	at com.test.dockerjava.Main.main(Main.java:22)
Caused by: java.io.IOException: Couldn't load native library
	at org.newsclub.net.unix.AFUNIXSocket.setIsCreated(AFUNIXSocket.java:56)
	at org.newsclub.net.unix.AFUNIXSocket.<init>(AFUNIXSocket.java:48)
	at org.newsclub.net.unix.AFUNIXSocket.newInstance(AFUNIXSocket.java:77)
	at org.newsclub.net.unix.AFUNIXSocket.newInstance(AFUNIXSocket.java:72)
	at com.github.dockerjava.jaxrs.ApacheUnixSocket.<init>(ApacheUnixSocket.java:51)
	at com.github.dockerjava.jaxrs.UnixConnectionSocketFactory.createSocket(UnixConnectionSocketFactory.java:66)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:119)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:373)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:394)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
	at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:450)
	... 14 more
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.newsclub.net.unix.NativeUnixSocket
	at org.newsclub.net.unix.AFUNIXSocket.setIsCreated(AFUNIXSocket.java:54)
	... 29 more
```

We can work around this right now by not updating to latest jdk for our mac users, but I figured I would try to report this if it would help.

**Comment by nicholas-s-perkins** [comment]
So, after a bit more research, this is probably a bug in adoptopenjdk's builds:
https://github.com/AdoptOpenJDK/openjdk-build/issues/1211
