### ISSUE TITLE
Add wildcard support

### ISSUE THREAD

**Issue by cmoro-deusto** [docker-java/docker-java#129]
Hi!

   I have a Dockerfile that issues the following command:

```
ADD ./build/libs/*.war /opt/tomcat/webapps/
```
The Dockerfile works correctly if I use the docker cli, but fails if docker-java is used to launch the docker build image.

I have tested it with the Gradle Docker plugin (https://github.com/bmuschko/gradle-docker-plugin), which 
uses docker-java lib. 

Here is the relevant part of the stack trace:

```
Caused by: com.github.dockerjava.api.DockerClientException: Source file /Users/carlos/Code/sla/berri/spring/boot/build/libs/*.war doesn't exist
	at com.github.dockerjava.core.command.BuildImageCmdImpl.buildDockerFolderTar(BuildImageCmdImpl.java:241)
	at com.github.dockerjava.core.command.BuildImageCmdImpl.<init>(BuildImageCmdImpl.java:51)
	at com.github.dockerjava.core.DockerClientImpl.buildImageCmd(DockerClientImpl.java:248)
	at com.github.dockerjava.api.DockerClient$buildImageCmd.call(Unknown Source)
```

Thanks very much!

**Comment by marcuslinke** [comment]
@cmoro-deusto Thanks for finding! This should be fixed with https://github.com/docker-java/docker-java/commit/60fb248a7acc4e6bedbe56503d5ae142862b68f5.

**Comment by cmoro-deusto** [comment]
Awesome! Thanks a lot @marcuslinke :)
