### ISSUE TITLE
Docker attach stdin support

### ISSUE THREAD

**Issue by Derkades** [docker-java/docker-java#1346]
```
Error occured in API request
java.lang.UnsupportedOperationException: Passing stdin to the container is currently not supported.
```

**Comment by KostyaSha** [comment]
What transport do you use? Jersey?

**Comment by baymoe** [comment]
yes

**Comment by bsideup** [comment]
@Derkades Jersey does not support stdin attach, use OkHttp transport (or Netty).

**Comment by Derkades** [comment]
Thanks for the quick reply, I'll try

**Comment by Derkades** [comment]
DockerClientBuilder was no longer available so I did this thing:
```java
Constructor<NettyDockerCmdExecFactory> constructor = NettyDockerCmdExecFactory.class.getConstructor();
constructor.setAccessible(true);
NettyDockerCmdExecFactory factory = constructor.newInstance();
factory.init(DefaultDockerClientConfig.createDefaultConfigBuilder().build());
		
docker = DockerClientImpl.getInstance(DefaultDockerClientConfig.createDefaultConfigBuilder().build())
				.withDockerCmdExecFactory(factory);
```

this is definitely not the right way of doing it, but now if anyone finds this using google at least they'll have a wrong (working) answer.

**Comment by bsideup** [comment]
Umm.... this is not how you instantiate it. Use:
```java
DockerClient client = DockerClientImpl.getInstance()
    .withDockerCmdExecFactory(new NettyDockerCmdExecFactory())
    .build();
```

**Comment by bsideup** [comment]
`DockerClientBuilder` is still available in `docker-java`, but not in `docker-java-api` nor `docker-java-core`

**Comment by bsideup** [comment]
Also, I highly recommend trying OkHttp-based transport first.

**Comment by Derkades** [comment]
Sorry to bother you again, now with OkHttp I am getting the following error:
```
Exception in thread "Thread-15" java.lang.RuntimeException: java.io.IOException: native write() failed : Bad file descriptor
	at com.github.dockerjava.okhttp.OkHttpInvocationBuilder.lambda$null$1(OkHttpInvocationBuilder.java:193)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.io.IOException: native write() failed : Bad file descriptor
	at com.github.dockerjava.okhttp.UnixDomainSocket$UnixSocketOutputStream.write(UnixDomainSocket.java:300)
	at com.github.dockerjava.okhttp.UnixSocketFactory$1$2.write(UnixSocketFactory.java:54)
	at okio.Okio$1.write(Okio.java:79)
	at okio.AsyncTimeout$1.write(AsyncTimeout.java:180)
	at okio.RealBufferedSink.emit(RealBufferedSink.java:186)
	at com.github.dockerjava.okhttp.OkHttpInvocationBuilder.lambda$null$1(OkHttpInvocationBuilder.java:188)
	... 1 more
	Suppressed: java.io.IOException: native write() failed : Bad file descriptor
		at com.github.dockerjava.okhttp.UnixDomainSocket$UnixSocketOutputStream.write(UnixDomainSocket.java:300)
		at com.github.dockerjava.okhttp.UnixSocketFactory$1$2.write(UnixSocketFactory.java:54)
		at okio.Okio$1.write(Okio.java:79)
		at okio.AsyncTimeout$1.write(AsyncTimeout.java:180)
		at okio.RealBufferedSink.close(RealBufferedSink.java:241)
		at com.github.dockerjava.okhttp.OkHttpInvocationBuilder.lambda$null$1(OkHttpInvocationBuilder.java:191)
		... 1 more
```
with the code
```java
final ResultCallback<Frame> callback = new ResultCallback<Frame>() {

	@Override
	public void close() throws IOException {
		System.out.println("close");
	}

	@Override
	public void onStart(final Closeable closeable) {
		System.out.println("start");
	}

	@Override
	public void onNext(final Frame object) {
		System.out.println("next");
	}

	@Override
	public void onError(final Throwable throwable) {
		throwable.printStackTrace();
	}

	@Override
	public void onComplete() {
		System.out.println("complete");
	}
};

final InputStream stdin = new ByteArrayInputStream("test");
dockerClient.attachContainerCmd(container.getId()).withStdIn(stdin).exec(callback);
```

I'm trying to simulate `docker attach container`, typing something and exiting.

This monstrosity does work, so I know the container is capable of receiving data on stdin:
```java
Process process =
		new ProcessBuilder()
		.command("socat", "EXEC:\"docker attach " + id + "\",pty", "STDIN")
		.start();
OutputStreamWriter writer = new OutputStreamWriter(process.getOutputStream());
writer.write("test\n");
writer.flush();
writer.close();
```

**Comment by bsideup** [comment]
@Derkades see this test:
https://github.com/docker-java/docker-java/blob/c3d03d6bc2770cf57769479bcfa07ca32344ecda/docker-java/src/test/java/com/github/dockerjava/cmd/AttachContainerCmdIT.java#L46

**Comment by Derkades** [comment]
I am getting the same issue with code that now more closely resembles these tests. I've tried it with containers with and without tty (`-i` and `-it`)

```java
final ResultCallback.Adapter<Frame> callback = new ResultCallback.Adapter<Frame>() {

	@Override
	public void close() throws IOException {
		System.out.println("close");
	}

	@Override
	public void onStart(final Closeable closeable) {
		System.out.println("start");
	}

	@Override
	public void onNext(final Frame object) {
		System.out.println("next");
	}

	@Override
	public void onError(final Throwable throwable) {
		throwable.printStackTrace();
	}

	@Override
	public void onComplete() {
		System.out.println("complete");
	}
};

final PipedOutputStream out = new PipedOutputStream();
final PipedInputStream in = new PipedInputStream(out);

dockerClient.attachContainerCmd(container.getId())
	.withFollowStream(false)
	.withStdOut(true)
	.withStdErr(true)
	.withStdIn(in)
	.exec(callback);

out.write((command + "\n").getBytes());
out.flush();

callback.awaitCompletion();
callback.close();

System.out.println("it never reaches here");
```
output:
```
start
complete
Exception in thread "Thread-16" java.lang.RuntimeException: java.io.IOException: native write() failed : Bad file descriptor
	at com.github.dockerjava.okhttp.OkHttpInvocationBuilder.lambda$null$1(OkHttpInvocationBuilder.java:193)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.io.IOException: native write() failed : Bad file descriptor
	at com.github.dockerjava.okhttp.UnixDomainSocket$UnixSocketOutputStream.write(UnixDomainSocket.java:300)
	at com.github.dockerjava.okhttp.UnixSocketFactory$1$2.write(UnixSocketFactory.java:54)
	at okio.Okio$1.write(Okio.java:79)
	at okio.AsyncTimeout$1.write(AsyncTimeout.java:180)
	at okio.RealBufferedSink.emit(RealBufferedSink.java:186)
	at com.github.dockerjava.okhttp.OkHttpInvocationBuilder.lambda$null$1(OkHttpInvocationBuilder.java:188)
	... 1 more
	Suppressed: java.io.IOException: native write() failed : Bad file descriptor
		at com.github.dockerjava.okhttp.UnixDomainSocket$UnixSocketOutputStream.write(UnixDomainSocket.java:300)
		at com.github.dockerjava.okhttp.UnixSocketFactory$1$2.write(UnixSocketFactory.java:54)
		at okio.Okio$1.write(Okio.java:79)
		at okio.AsyncTimeout$1.write(AsyncTimeout.java:180)
		at okio.RealBufferedSink.close(RealBufferedSink.java:241)
		at com.github.dockerjava.okhttp.OkHttpInvocationBuilder.lambda$null$1(OkHttpInvocationBuilder.java:191)
		... 1 more
```

This is on linux connecting to `unix:///var/run/docker.sock`

**Comment by Derkades** [comment]
Ignore the comment above, I had to set `withFollowStream` to true.
