### ISSUE TITLE
100% CPU after using attachContainerCmd with follow stream and stdin

### ISSUE THREAD

**Issue by Derkades** [docker-java/docker-java#1350]
After a few hours, my program starts using 100% cpu on multiple cores. Most of the time only ~400%, but I've seen it go to 1200%.

```
"Thread-13" #35 daemon prio=5 os_prio=0 cpu=10232608.27ms elapsed=10255.83s tid=0x00007f98b0003000 nid=0x38 runnable  [0x00007f98bb8f4000]
   java.lang.Thread.State: RUNNABLE
	at com.github.dockerjava.okhttp.OkHttpInvocationBuilder.lambda$null$1(OkHttpInvocationBuilder.java:190)
	at com.github.dockerjava.okhttp.OkHttpInvocationBuilder$$Lambda$129/0x00000008002b8440.run(Unknown Source)
	at java.lang.Thread.run(java.base@11.0.6/Unknown Source)

"tc-okhttp-stream-393979772" #37 daemon prio=5 os_prio=0 cpu=1.38ms elapsed=10254.61s tid=0x00007f98ac003000 nid=0x3a runnable

[..]

"Thread-38" #1546 daemon prio=5 os_prio=0 cpu=7701737.33ms elapsed=7718.98s tid=0x00007f98e000b800 nid=0x61f runnable  [0x00007f994cf73000]
   java.lang.Thread.State: RUNNABLE
	at com.github.dockerjava.okhttp.OkHttpInvocationBuilder.lambda$null$1(OkHttpInvocationBuilder.java:190)
	at com.github.dockerjava.okhttp.OkHttpInvocationBuilder$$Lambda$129/0x00000008002b8440.run(Unknown Source)
	at java.lang.Thread.run(java.base@11.0.6/Unknown Source)
```

If this can be an issue with my program, please let me know. I am fairly sure I am closing everything though, and callbacks should stop after the timeout. I can post the full thread dump and program source code if that helps.

Possibly related to https://github.com/docker-java/docker-java/issues/1074, I do use stats. I also use list, restart, send, start, stop, log, attach (stdin).

**Comment by bsideup** [comment]
Hi @Derkades,

Could you share a reproducer?

> I am fairly sure I am closing everything though

Worth double checking. The hijacking is done only for `attach (stdin)`, you can focus on it

**Comment by Derkades** [comment]
I am using attach to stdin here: <https://github.com/Derkades/dockerpanel/blob/master/src/xyz/derkades/dockerpanel/api/SendCommand.java#L51-L73>

**Comment by bsideup** [comment]
@Derkades you should *at least* use `try {} finally {}` (or `try-with-resources`). Otherwise, an error thrown from `out.write` will leave the callback unclosed.

Also, it is weird that you first close the callback and then use `awaitCompletion`...

**Comment by Derkades** [comment]
That makes sense, thanks

**Comment by Derkades** [comment]
I made [some changes](https://github.com/Derkades/dockerpanel/blob/master/src/xyz/derkades/dockerpanel/api/SendCommand.java#L50-L69) but I can still reproduce the issue.

I can now confirm that it happens every time this code is run, no matter if the container is stopped afterwards or not.

**Comment by Derkades** [comment]
I have no idea what is going on. My code:
```
try (final PipedOutputStream out = new PipedOutputStream()) {
	final PipedInputStream in = new PipedInputStream(out);

	final ResultCallbackTemplate<?, Frame> callback = dockerClient.attachContainerCmd(container.getId())
			.withFollowStream(true)
			.withStdIn(in).start();

	out.write((command + "\n").getBytes());
	out.flush();
	out.close();
	callback.close();
}
```
Every time this code is ran the program maxes out one more CPU core. If I remove `withFollowStream(true)` I get this error:
```
Exception in thread "Thread-11" java.lang.RuntimeException: java.io.IOException: native write() failed : Bad file descriptor
	at com.github.dockerjava.okhttp.OkHttpInvocationBuilder.lambda$null$1(OkHttpInvocationBuilder.java:193)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.io.IOException: native write() failed : Bad file descriptor
	at com.github.dockerjava.okhttp.UnixDomainSocket$UnixSocketOutputStream.write(UnixDomainSocket.java:300)
	at com.github.dockerjava.okhttp.UnixSocketFactory$1$2.write(UnixSocketFactory.java:54)
	at okio.Okio$1.write(Okio.java:79)
	at okio.AsyncTimeout$1.write(AsyncTimeout.java:180)
	at okio.RealBufferedSink.emit(RealBufferedSink.java:186)
	at com.github.dockerjava.okhttp.OkHttpInvocationBuilder.lambda$null$1(OkHttpInvocationBuilder.java:188)
	... 1 more
	Suppressed: java.io.IOException: native write() failed : Bad file descriptor
		at com.github.dockerjava.okhttp.UnixDomainSocket$UnixSocketOutputStream.write(UnixDomainSocket.java:300)
		at com.github.dockerjava.okhttp.UnixSocketFactory$1$2.write(UnixSocketFactory.java:54)
		at okio.Okio$1.write(Okio.java:79)
		at okio.AsyncTimeout$1.write(AsyncTimeout.java:180)
		at okio.RealBufferedSink.close(RealBufferedSink.java:241)
		at com.github.dockerjava.okhttp.OkHttpInvocationBuilder.lambda$null$1(OkHttpInvocationBuilder.java:191)
		... 1 more
```

**Comment by bsideup** [comment]
@Derkades could you please try the newly introduced Apache HttpClient5 transport?

**Comment by Derkades** [comment]
The 100% cpu issue is gone, but it seems something is still keeping connections busy. After using my stdin method 5 times (in a period of a couple of seconds) the API becomes unresponsive indefinitely. The java application requires a hard kill (instead of SIGINT) to close.

The first 5 times the code completes successfully (a print statement at the end of docker API calls runs), later it will hang (in this particular case at listContainersCmd(), but I suspect it would hang at any API method).

There are five threads like this:
```
"docker-java-stream--1079232089" #65 daemon prio=5 os_prio=0 cpu=1.45ms elapsed=174.24s tid=0x00007fdfc400a800 nid=0x51 runnable  [0x00007fdfa72e9000]
   java.lang.Thread.State: RUNNABLE
        at com.github.dockerjava.httpclient5.UnixDomainSocket.read(Native Method)
        at com.github.dockerjava.httpclient5.UnixDomainSocket$UnixSocketInputStream.read(UnixDomainSocket.java:256)
        at org.apache.hc.core5.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:149)
        at org.apache.hc.core5.http.impl.io.SessionInputBufferImpl.read(SessionInputBufferImpl.java:172)
        at org.apache.hc.core5.http.impl.io.IdentityInputStream.read(IdentityInputStream.java:87)
        at org.apache.hc.core5.http.io.EofSensorInputStream.read(EofSensorInputStream.java:118)
        at com.github.dockerjava.core.FramedInputStreamConsumer.accept(FramedInputStreamConsumer.java:30)
        at com.github.dockerjava.core.FramedInputStreamConsumer.accept(FramedInputStreamConsumer.java:12)
        at com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$0(DefaultInvocationBuilder.java:250)
        at com.github.dockerjava.core.DefaultInvocationBuilder$$Lambda$140/0x0000000800b91440.run(Unknown Source)
        at java.lang.Thread.run(java.base@14.0.1/Unknown Source)
```
and my waiting thread:
```
"qtp169833205-34" #34 prio=5 os_prio=0 cpu=27.51ms elapsed=27.17s tid=0x00007fdfcc002000 nid=0x33 in Object.wait()  [0x00007fdfa77ec000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
        at java.lang.Object.wait(java.base@14.0.1/Native Method)
        - waiting on <0x0000000713fb40e0> (a org.apache.hc.core5.concurrent.BasicFuture)
        at org.apache.hc.core5.concurrent.BasicFuture.get(BasicFuture.java:101)
        - locked <0x0000000713fb40e0> (a org.apache.hc.core5.concurrent.BasicFuture)
        at org.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManager$1.get(PoolingHttpClientConnectionManager.java:278)
        - locked <0x0000000713fb4170> (a org.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManager$1)
at org.apache.hc.client5.http.impl.classic.InternalExecRuntime.acquireEndpoint(InternalExecRuntime.java:113)
        at org.apache.hc.client5.http.impl.classic.ConnectExec.execute(ConnectExec.java:118)
        at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
        at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
        at org.apache.hc.client5.http.impl.classic.ProtocolExec.execute(ProtocolExec.java:165)
        at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
        at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
        at org.apache.hc.client5.http.impl.classic.HttpRequestRetryExec.execute(HttpRequestRetryExec.java:93)
        at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
        at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
        at org.apache.hc.client5.http.impl.classic.RedirectExec.execute(RedirectExec.java:116)
        at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
        at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
        at org.apache.hc.client5.http.impl.classic.ContentCompressionExec.execute(ContentCompressionExec.java:128)
        at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
        at org.apache.hc.client5.http.impl.classic.InternalHttpClient.doExecute(InternalHttpClient.java:178)
        at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:67)
        at com.github.dockerjava.httpclient5.ApacheDockerHttpClientImpl.execute(ApacheDockerHttpClientImpl.java:149)
        at com.github.dockerjava.httpclient5.ApacheDockerHttpClient.execute(ApacheDockerHttpClient.java:8)
        at com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:207)
        at com.github.dockerjava.core.DefaultInvocationBuilder.get(DefaultInvocationBuilder.java:191)
        at com.github.dockerjava.core.DefaultInvocationBuilder.get(DefaultInvocationBuilder.java:74)
        at com.github.dockerjava.core.exec.ListContainersCmdExec.execute(ListContainersCmdExec.java:44)
        at com.github.dockerjava.core.exec.ListContainersCmdExec.execute(ListContainersCmdExec.java:15)
        at com.github.dockerjava.core.exec.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:21)
        at com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:35)
        at xyz.derkades.dockerpanel.App.getContainers(App.java:141)
        [..]
```

**Comment by Derkades** [comment]
Leaving a comment to prevent the issue being closed

**Comment by Derkades** [comment]
This issue is not solved
