### ISSUE TITLE
RESTEASY003145: Unable to find a MessageBodyReader of content-type application/json and type class java.io.InputStream

### ISSUE THREAD

**Issue by danielborges93** [docker-java/docker-java#1355]
I am trying to use the docker-java lib inside a Spring Boot application but I am getting the following error when I try to do any request:

```
javax.ws.rs.ProcessingException: RESTEASY003145: Unable to find a MessageBodyReader of content-type application/json and type class java.io.InputStream
	at org.jboss.resteasy.core.interception.ClientReaderInterceptorContext.throwReaderNotFound(ClientReaderInterceptorContext.java:37) ~[resteasy-jaxrs-3.9.1.Final.jar:3.9.1.Final]
	at org.jboss.resteasy.core.interception.AbstractReaderInterceptorContext.getReader(AbstractReaderInterceptorContext.java:80) ~[resteasy-jaxrs-3.9.1.Final.jar:3.9.1.Final]
	at org.jboss.resteasy.core.interception.AbstractReaderInterceptorContext.proceed(AbstractReaderInterceptorContext.java:53) ~[resteasy-jaxrs-3.9.1.Final.jar:3.9.1.Final]
	at org.jboss.resteasy.client.jaxrs.internal.ClientResponse.readFrom(ClientResponse.java:211) ~[resteasy-client-3.9.1.Final.jar:3.9.1.Final]
	at org.jboss.resteasy.specimpl.BuiltResponse.readEntity(BuiltResponse.java:88) ~[resteasy-jaxrs-3.9.1.Final.jar:3.9.1.Final]
	at org.jboss.resteasy.specimpl.AbstractBuiltResponse.readEntity(AbstractBuiltResponse.java:262) ~[resteasy-jaxrs-3.9.1.Final.jar:3.9.1.Final]
	at com.github.dockerjava.jaxrs.JerseyInvocationBuilder.get(JerseyInvocationBuilder.java:67) ~[docker-java-transport-jersey-3.2.1.jar:na]
	at com.github.dockerjava.core.exec.InfoCmdExec.exec(InfoCmdExec.java:24) ~[docker-java-core-3.2.1.jar:na]
	at com.github.dockerjava.core.exec.InfoCmdExec.exec(InfoCmdExec.java:14) ~[docker-java-core-3.2.1.jar:na]
	at com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:35) ~[docker-java-core-3.2.1.jar:na]
...
```

My `DockerClient`:
```
public DockerClient dockerClient() {
    return DockerClientBuilder.getInstance("tcp://localhost:2375").build();
}
```

My code where happens the exception:
```
Info info = dockerClient.infoCmd().exec();
System.out.print(info);
```

The remote api is up and working. When I do a GET request to `http://localhost:2375/info` I get a response, and it is not empty.

I am doing something wrong, or it is missing something? Thanks!

**Comment by Mikarnage** [comment]
Hello,
I had the same problem inside JBoss (Resteasy is its default jax-rs provider).

Using Netty transport instead of the default one fixed the problem for me.

**Comment by bsideup** [comment]
You seems to have a classpath conflict. Consider using a transport that is not conflicting with the rest of your app:
https://github.com/docker-java/docker-java/blob/master/docs/transports.md
