### ISSUE TITLE
NullPointerException in DefaultDockerClientConfig.checkDockerHostScheme

### ISSUE THREAD

**Issue by zadoli** [docker-java/docker-java#1365]
Hi, I just updated Intellij and now getting connection problem in docker services window. Logs from docker.log:

> 2020-04-16 16:44:54,480 [      1]  ERROR - .intellij.docker.agent.ApiTask - com.intellij.docker.agent.DockerAgentImpl$1@6460ab49
java.lang.NullPointerException
	at com.github.dockerjava.core.DefaultDockerClientConfig.checkDockerHostScheme(DefaultDockerClientConfig.java:101)
	at com.github.dockerjava.core.DefaultDockerClientConfig.<init>(DefaultDockerClientConfig.java:90)
	at com.github.dockerjava.core.DefaultDockerClientConfig$Builder.build(DefaultDockerClientConfig.java:432)
	at com.github.dockerjava.netty.NettyInvocationBuilder.<init>(NettyInvocationBuilder.java:88)

Im using TCP socket to connect the docker daemon, my Engine API URL is like : http://env-ozadori.hu:2375

**Comment by bsideup** [comment]
Please consider reporting it in IntelliJ IDEA's bug tracker.
