### ISSUE TITLE
Caused by: java.lang.NoSuchMethodError: 'com.github.dockerjava.api.model.AuthConfig

### ISSUE THREAD

**Issue by entitystream** [docker-java/docker-java#1452]
Trying to create a container using 3.2.2 and 3.2.5 using the http5 transport:

CreateContainerResponse container = dockerClient.createContainerCmd(hostedInstance.getPodImage())
			.withName(hostedInstance.getRegistration())
			.withHostName(hostedInstance.getRegistration())
			.withEnv(hostedInstance.getEnvironment())
			.withLabels(hostedInstance.getLabels())
			.withVolumes(hostedInstance.getVolumes())
			.exec();

Throws exception 

Caused by: java.lang.NoSuchMethodError: 'com.github.dockerjava.api.model.AuthConfig com.github.dockerjava.api.command.CreateContainerCmd.getAuthConfig()'
	at com.github.dockerjava.core.exec.CreateContainerCmdExec.execute(CreateContainerCmdExec.java:31)
	at com.github.dockerjava.core.exec.CreateContainerCmdExec.execute(CreateContainerCmdExec.java:13)
	at com.github.dockerjava.core.exec.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:21)
	at com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:35)
	at com.github.dockerjava.core.command.CreateContainerCmdImpl.exec(CreateContainerCmdImpl.java:595)
	at com.entitystream.memento.action.home.ManageActionBean.buildPod(ManageActionBean.java:506)

There is some abstract classes and the implementation has a method of this name, but it is hidden by the abstract classes.

**Comment by entitystream** [comment]
Previous version was conflicting in classpath, mvn clean solved.
