### ISSUE TITLE
"Could not pull image" seen using docker-java 3.1.5.2

### ISSUE THREAD

**Issue by davidhay1969** [docker-java/docker-java#1457]
Hi

We have a Jenkins Plugin using `docker-java-api-plugin` version `3.1.5.2` via `docker-plugin` version `1.2.0`.

Alas I'm seeing: -

```text
com.github.dockerjava.api.exception.DockerClientException: Could not pull image
	at com.github.dockerjava.core.command.PullImageResultCallback.checkDockerClientPullSuccessful(PullImageResultCallback.java:94)
	at com.github.dockerjava.core.command.PullImageResultCallback.throwFirstError(PullImageResultCallback.java:111)
	at com.github.dockerjava.core.async.ResultCallbackTemplate.awaitCompletion(ResultCallbackTemplate.java:94)
	at com.nirima.jenkins.plugins.docker.DockerTemplate.pullImage(DockerTemplate.java:508)
	at com.nirima.jenkins.plugins.docker.DockerTemplate.provisionNode(DockerTemplate.java:527)
	at com.nirima.jenkins.plugins.docker.DockerCloud$1.run(DockerCloud.java:370)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

I believe this is coming from the `checkDockerClientPullSuccessful` method in [com.github.dockerjava.core.command.PullImageResultCallback.java](https://github.com/docker-java/docker-java/blob/master/docker-java-core/src/main/java/com/github/dockerjava/core/command/PullImageResultCallback.java) specifically this: -

```java
    private void checkDockerClientPullSuccessful() {
        if (latestItem == null) {
            throw new DockerClientException("Could not pull image");
        } else if (!latestItem.isPullSuccessIndicated()) {
            throw new DockerClientException("Could not pull image: " + messageFromPullResult(latestItem));
        }
    }
```

I'm making this assumption because the exception only throws `Could not pull image` i.e. with no other debug after the message itself.

What's making my head hurt is where `latestItem` actually gets set ....

Our code implements `PullImageCmd.Exec` so my **assumption** is that we should be setting something on the callback, via `resultCallback` but ...

For the record, the image pull completes without error, and I can see that on the remote Docker box, so I'm also wondering if I need to do something wrt the `PullResponseItem` as my remote Docker box ( REST API ) returns a non-standard JSON response

Any clue as to what I'm doing wrong ?

**Comment by davidhay1969** [comment]
Hi, anyone able to give me a clue ? Appreciate it's probably me "holding it wrong" but any ideas are great ideas 🙇 

@KostyaSha would really appreciate any insights you can offer - again, thanks in advance 🙇‍♂️

**Comment by KostyaSha** [comment]
Sorry, i'm not interested in jenkins `docker-plugin`
