### ISSUE TITLE
https protocol is not supported while conencting to gcr

### ISSUE THREAD

**Issue by 244079916** [docker-java/docker-java#1458]
Hi, I am getting the following error when I was trying to connect to gcr with docker java client:

14:00:28.271 [http-nio-9091-exec-1] INFO  o.a.http.impl.execchain.RetryExec - I/O exception (org.apache.http.conn.UnsupportedSchemeException) caught when processing request to {s}->https://eu.gcr.io:443: https protocol is not supported
14:00:28.271 [http-nio-9091-exec-1] INFO  o.a.http.impl.execchain.RetryExec - Retrying request to {s}->https://eu.gcr.io:443
14:00:28.274 [http-nio-9091-exec-1] INFO  o.a.http.impl.execchain.RetryExec - I/O exception (org.apache.http.conn.UnsupportedSchemeException) caught when processing request to {s}->https://eu.gcr.io:443: https protocol is not supported
14:00:28.274 [http-nio-9091-exec-1] INFO  o.a.http.impl.execchain.RetryExec - Retrying request to {s}->https://eu.gcr.io:443
14:00:28.278 [http-nio-9091-exec-1] INFO  o.a.http.impl.execchain.RetryExec - I/O exception (org.apache.http.conn.UnsupportedSchemeException) caught when processing request to {s}->https://eu.gcr.io:443: https protocol is not supported
14:00:28.279 [http-nio-9091-exec-1] INFO  o.a.http.impl.execchain.RetryExec - Retrying request to {s}->https://eu.gcr.io:443
14:00:53.557 [HikariPool-1 housekeeper] WARN  com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=51s246ms560µs780ns).
14:00:53.573 [http-nio-9091-exec-1] ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [/api/v0] threw exception [Request processing failed; nested exception is javax.ws.rs.ProcessingException: org.apache.http.conn.UnsupportedSchemeException: https protocol is not supported] with root cause
org.apache.http.conn.UnsupportedSchemeException: https protocol is not supported
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:109)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
	at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:478)
	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:254)
	at org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$0(JerseyInvocation.java:736)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:205)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:390)
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:735)
	at com.github.dockerjava.jaxrs.JerseyDockerHttpClient.execute(JerseyDockerHttpClient.java:297)
	at com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:228)
	at com.github.dockerjava.core.DefaultInvocationBuilder.get(DefaultInvocationBuilder.java:202)
	at com.github.dockerjava.core.DefaultInvocationBuilder.get(DefaultInvocationBuilder.java:75)
	at com.github.dockerjava.core.exec.ListContainersCmdExec.execute(ListContainersCmdExec.java:44)
	at com.github.dockerjava.core.exec.ListContainersCmdExec.execute(ListContainersCmdExec.java:15)
	at com.github.dockerjava.core.exec.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:21)
	at com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:35)

My code is attached as following:

DefaultDockerClientConfig.Builder config = DefaultDockerClientConfig.createDefaultConfigBuilder();
    config.withDockerHost("tcp://" + hostName + "/v2/")
        .withDockerConfig("/home/xxx/.docker")
        .withDockerCertPath("/home/xxx/.docker")
        .withRegistryUrl("http://" + hostName + "/" + projectId + "/")
        .withDockerTlsVerify("1");
    List<String> images = new ArrayList<>();
    DockerClient dockerClient = DockerClientBuilder.getInstance(config.build()).build();
    List<Container> containers = dockerClient.listContainersCmd().exec();

Anyone could help?

**Comment by bsideup** [comment]
GCR is a registry, not a Docker Engine. You can't connect a Docker client to it.

**Comment by 244079916** [comment]
> GCR is a registry, not a Docker Engine. You can't connect a Docker client to it.

I am wondering if I can fetch a list of images from a registry?

**Comment by bsideup** [comment]
See https://docs.docker.com/registry/spec/api/
