### ISSUE TITLE
Add a timeout to awaitCompletion()

### ISSUE THREAD

**Issue by mat1e** [docker-java/docker-java#1468]
We are using the Jenkins docker-plugin, and a call of docker host API is waiting indefinitly. Our docker host was saturated but that should return an error rather than block the thread.

For that reason I would like to add a timeout property to the awaitCompletion() method of ResultCallbackTemplate.

What do you think about this ?

Here is the stacktrace caught with a thread dump : 

```
Computer.threadPoolForRemoting [#7341]" id=157047 (0x26577) state=WAITING cpu=69%
    - waiting on <0x0f6ab72c> (a java.util.concurrent.CountDownLatch$Sync)
    - locked <0x0f6ab72c> (a java.util.concurrent.CountDownLatch$Sync)
    at java.base@11.0.5/jdk.internal.misc.Unsafe.park(Native Method)
    at java.base@11.0.5/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
    at java.base@11.0.5/java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:885)
    at java.base@11.0.5/java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1039)
    at java.base@11.0.5/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1345)
    at java.base@11.0.5/java.util.concurrent.CountDownLatch.await(CountDownLatch.java:232)
    at com.github.dockerjava.core.async.ResultCallbackTemplate.awaitCompletion(ResultCallbackTemplate.java:92)
    at com.github.dockerjava.netty.NettyInvocationBuilder$ResponseCallback.awaitResult(NettyInvocationBuilder.java:60)
    at com.github.dockerjava.netty.NettyInvocationBuilder.get(NettyInvocationBuilder.java:139)
    at com.github.dockerjava.core.exec.ListContainersCmdExec.execute(ListContainersCmdExec.java:44)
    at com.github.dockerjava.core.exec.ListContainersCmdExec.execute(ListContainersCmdExec.java:15)
    at com.github.dockerjava.core.exec.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:21)
    at com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:35)
    at com.nirima.jenkins.plugins.docker.DockerCloud.countContainersInDocker(DockerCloud.java:615)
    at com.nirima.jenkins.plugins.docker.DockerCloud.canAddProvisionedSlave(DockerCloud.java:633)
    at com.nirima.jenkins.plugins.docker.DockerCloud.provision(DockerCloud.java:352)
    at io.jenkins.docker.FastNodeProvisionerStrategy.applyFoCloud(FastNodeProvisionerStrategy.java:72)
    at io.jenkins.docker.FastNodeProvisionerStrategy.apply(FastNodeProvisionerStrategy.java:44)
    at hudson.slaves.NodeProvisioner.update(NodeProvisioner.java:334)
    at hudson.slaves.NodeProvisioner.lambda$suggestReviewNow$1(NodeProvisioner.java:183)
    at hudson.slaves.NodeProvisioner$$Lambda$495/0x00000007c14ca040.run(Unknown Source)
    at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
    at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
    at java.base@11.0.5/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
    at java.base@11.0.5/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.base@11.0.5/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base@11.0.5/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base@11.0.5/java.lang.Thread.run(Thread.java:834)
```

**Context** 
- Docker 1.13.1
- Jenkins 2.235.5
- OpenJDK 11.0.5 headless
- **docker-plugin 1.2.0 which integrates docker-java 3.1.5**

**Comment by bsideup** [comment]
There is `awaitCompletion(long, TimeUnit)` already.

**Comment by mat1e** [comment]
It does not return same than awaitCompletion() : 

```
    /**
     * Blocks until {@link ResultCallback#onComplete()} was called
     */
    @SuppressWarnings("unchecked")
    public RC_T awaitCompletion() throws InterruptedException {
        try {
            completed.await();
            // eventually (re)throws RuntimeException
            throwFirstError();
            return (RC_T) this;
        } finally {
            try {
                close();
            } catch (IOException e) {
                LOGGER.debug("Failed to close", e);
            }
        }
    }

    /**
     * Blocks until {@link ResultCallback#onComplete()} was called or the given timeout occurs
     * @return {@code true} if completed and {@code false} if the waiting time elapsed
     *         before {@link ResultCallback#onComplete()} was called.
     */
    public boolean awaitCompletion(long timeout, TimeUnit timeUnit) throws InterruptedException {
        try {
            boolean result = completed.await(timeout, timeUnit);
            throwFirstError();
            return result;
        } finally {
            try {
                close();
            } catch (IOException e) {
                LOGGER.debug("Failed to close", e);
            }
        }
    }
```
