### ISSUE TITLE
Redirect error

### ISSUE THREAD

**Issue by gabeki** [docker-java/docker-java#147]
I am writing a maven plugin for private registry.  0.10.5 doesn't seem to follow redirect.  Should it be supported by configuration?

```
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	... 19 more
Caused by: com.github.dockerjava.api.DockerException: <html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.7.7</center>
</body>
</html>

	at com.github.dockerjava.jaxrs.util.ResponseStatusExceptionFilter.filter(ResponseStatusExceptionFilter.java:56)
	at org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply(ClientFilteringStages.java:134)
	at org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply(ClientFilteringStages.java:123)
	at org.glassfish.jersey.process.internal.Stages.process(Stages.java:171)
	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:251)
	at org.glassfish.jersey.client.JerseyInvocation$2.call(JerseyInvocation.java:683)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:424)
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:679)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:435)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:338)
	at com.github.dockerjava.jaxrs.BuildImageCmdExec.execute(BuildImageCmdExec.java:49)
```

**Comment by marcuslinke** [comment]
@gabeki Just pushed a fix. Please test and close the issue. Thanks!

**Comment by gabeki** [comment]
It seems like it just silences it.  It doesn't really redirect.

**Comment by marcuslinke** [comment]
According to documentation following redirects is the default behavior so i thought disabling exception in this case should solve the issue.  Maybe enabling "follow redirects" explicitly is needed then. I will prepare a new commit.

**Comment by marcuslinke** [comment]
@gabeki Does this redirect issue affects all docker commands. Maybe it is limited to POST based commands only?

**Comment by marcuslinke** [comment]
Looking at https://github.com/jersey/jersey/blob/master/connectors/apache-connector/src/test/java/org/glassfish/jersey/apache/connector/FollowRedirectsTest.java it seems following redirects should work for GET requests without any explicit configuration...

**Comment by gabeki** [comment]
This is what I thought too.  But if it redirects successfully, shouldn't ResponseStatusExceptionFilter get a updated status code automatically?

**Comment by marcuslinke** [comment]
@gabeki I would guess redirect is done internally in apache http client so ```ResponseStatusExceptionFilter```should receive 200 OK then. However, could you check if this issue affects POST based commands only please?

**Comment by albers** [comment]
I suppose redirecting POST requests does not work for 301 redirects (as appears in your stacktrace). It might work for 307, though.
See http://programmers.stackexchange.com/questions/99894/why-doesnt-http-have-post-redirect

**Comment by gabeki** [comment]
It makes senses.  I have a workaround using a Redirect301Filter.  I could make a merge request if needed.  Thanks.

**Comment by marcuslinke** [comment]
Nice! Please create a merge request. Thanks!

**Comment by marcuslinke** [comment]
Just for the files: http://hc.apache.org/httpcomponents-client-ga/httpclient/apidocs/org/apache/http/impl/client/DefaultRedirectStrategy.html explains the redirection logic of apache httpclient. Sadly we can't change this behavior like described in the class comment because ```ApacheConnectorProvider``` doesn't allow it. So the workaround via filter will be the only way to implement it.
