### ISSUE TITLE
Tag validation. Connection reset by broken pipe/connection reset by peer

### ISSUE THREAD

**Issue by Monax111** [docker-java/docker-java#1502]
I try to create image with dockerjava.api 3.2.5.
I suggest adding tag validation OR exeption with description IF it possible
if I set tage like this: docker-internal.ru/bpm/JiraHelper, acync  process hangs(more then 20 minutes)  in ResultCallbackTemplate.awaitCompletion() - completed.await().
In my docker log i see 
```
[13:53:49.460][ApiProxy          ][Info   ] msg="proxy >> POST /build?t=docker-internal.ru%2Fbpm%2FJiraHelper%3Alocal&rm=true\n"
[13:53:49.993][VpnKitBridge      ][Info   ] msg="error copying: write unix @->/run/guest-services/docker.sock: write: broken pipe"
[13:53:50.003][VpnKitBridge      ][Info   ] msg="error copying: read unix @->/run/guest-services/docker.sock: read: connection reset by peer"
[13:53:50.003][ApiProxy          ][Info   ] msg="error forwarding client's request to Docker: The pipe is being closed."
[13:53:50.003][ApiProxy          ][Info   ] msg="proxy << POST /build?t=docker-internal.ru%2Fbpm%2FJiraHelper%3Alocal&rm=true (542.7552ms)\n"
```
if i change tag on docker-internal.ru/bpm/jira-helper, it work.

```
Client: Docker Engine - Community
 Cloud integration: 1.0.2
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:00:27 2020
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:07:04 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by bsideup** [comment]
I just tried (docker-java 3.2.6) and got the following exception:
```
com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"invalid reference format: repository name must be lowercase"}

	at com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247)
	at com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269)
	at java.lang.Thread.run(Thread.java:748)

```

so it looks like the error is raised. Do you have a reproducer that we can use to test your issue?

**Comment by Monax111** [comment]
It's magic !!! If i remove kotlin-reflect it's work! i see error.
But with kotlin-reflect it's hangs( I need kotlin-reflect for my library(((
I create reproducer. I use [plugin ](https://github.com/bmuschko/gradle-docker-plugin) for user friendly dsl. Plugin calls docker-java in this [line ](https://github.com/bmuschko/gradle-docker-plugin/blob/master/src/main/groovy/com/bmuschko/gradle/docker/tasks/image/DockerBuildImage.groovy#L295) if it matters

**Comment by bsideup** [comment]
Doesn't seem bo be docker-java's issue. Consider reporting to Gradle Docker plugin.
