### ISSUE TITLE
Error trying to run execute docker command on Docker for Windows from WSL2

### ISSUE THREAD

**Issue by GeorgHoffmeyer** [docker-java/docker-java#1520]
When I'm trying to execute a docker command from a WSL2 Distibution on my Docker running on Windows 10, I get the following error:
```
Caused by: javax.ws.rs.ProcessingException: org.apache.http.conn.HttpHostConnectException: Connect to localhost:2375 [localhost/127.0.0.1] failed: Connection refused (Connection refused)
        at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:528)
        at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:296)
        at org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$0(JerseyInvocation.java:609)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:205)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:390)
        at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:608)
        at com.github.dockerjava.jaxrs.JerseyDockerHttpClient.execute(JerseyDockerHttpClient.java:297)
        at com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:228)
        at com.github.dockerjava.core.DefaultInvocationBuilder.get(DefaultInvocationBuilder.java:202)
        at com.github.dockerjava.core.DefaultInvocationBuilder.get(DefaultInvocationBuilder.java:75)
        at com.github.dockerjava.core.exec.InspectNetworkCmdExec.execute(InspectNetworkCmdExec.java:26)
        at com.github.dockerjava.core.exec.InspectNetworkCmdExec.execute(InspectNetworkCmdExec.java:12)
        at com.github.dockerjava.core.exec.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:21)
        at com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:35)
        at com.github.dockerjava.core.command.InpectNetworkCmdImpl.exec(InpectNetworkCmdImpl.java:7)
        at com.github.dockerjava.api.command.InspectNetworkCmd$exec$0.call(Unknown Source)
```

Docker port is exposed. Running them same from Powershell under Windows works fine.

**Comment by GeorgHoffmeyer** [comment]
Any update on this issue?

**Comment by bsideup** [comment]
Connection refused means that Docker isn't listening on localhost:2375

Please check your configuration.
