### ISSUE TITLE
MismatchedInputException with inspectContainerCmd 

### ISSUE THREAD

**Issue by gionn** [docker-java/docker-java#1521]
I get:

```
java.lang.RuntimeException: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `java.util.LinkedHashMap` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('/etc/folder')
 at [Source: (com.github.dockerjava.zerodep.shaded.org.apache.hc.core5.http.io.EofSensorInputStream); line: 1, column: 3869] (through reference chain: com.github.dockerjava.api.command.InspectContainerResponse["Mounts"]->java.util.ArrayList[0]->com.github.dockerjava.api.command.InspectContainerResponse$Mount["Destination"])

	at com.github.dockerjava.core.DefaultInvocationBuilder.get(DefaultInvocationBuilder.java:77)
	at com.github.dockerjava.core.exec.InspectContainerCmdExec.execute(InspectContainerCmdExec.java:31)
	at com.github.dockerjava.core.exec.InspectContainerCmdExec.execute(InspectContainerCmdExec.java:13)
	at com.github.dockerjava.core.exec.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:21)
	at com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:35)
	at com.github.dockerjava.core.command.InspectContainerCmdImpl.exec(InspectContainerCmdImpl.java:52)
```

when:

```
            try ( DockerClient client = getDockerClient() )
            {
                client.inspectContainerCmd( getContainerName() ).exec();
            }
```

with a container created with:

```
        try ( DockerClient docker = getDockerClient() )
        {
            HostConfig hostconfig = HostConfig.newHostConfig()
                    .withNetworkMode( "host" )
                    .withMemory( getMemory() )
                    .withBinds( new Bind( "/etc/folder", new Volume( "/etc/folder" ), AccessMode.ro ) );

            CreateContainerResponse container = docker.createContainerCmd( getContainerURL() )
                    .withName( getContainerName() )
                    .withEnv( getEnv() )
                    .withHostConfig( hostconfig )
                    .exec();

            docker.startContainerCmd( container.getId() ).exec();
        }
```

docker-java 3.2.7
docker-ce `5:19.03.8~3-0~ubuntu-bionic`

**Comment by gionn** [comment]
may be related to https://github.com/docker-java/docker-java/issues/1509#issuecomment-740985349
