### ISSUE TITLE
buildImageCmd error

### ISSUE THREAD

**Issue by wuziyangGitHub** [docker-java/docker-java#1529]
code:
String dockerFile = "FROM nginx:1.17.0-alpine RUN echo 'hello world' > /usr/share/nginx/html/index.html";
        ByteArrayInputStream is = new ByteArrayInputStream(dockerFile.getBytes());
        String imageId = dockerClient.buildImageCmd(is).start().awaitImageId();
        dockerClient.tagImageCmd(imageId, repositoryName, tag)
                .withForce().exec();
codeMessage:
com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: unexpected EOF
	at com.github.dockerjava.jaxrs.filter.ResponseStatusExceptionFilter.filter(ResponseStatusExceptionFilter.java:68)
	at org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply(ClientFilteringStages.java:131)
	at org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply(ClientFilteringStages.java:119)
	at org.glassfish.jersey.process.internal.Stages.process(Stages.java:147)
	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:259)
	at org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$0(JerseyInvocation.java:736)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:205)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:390)
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:735)
	at com.github.dockerjava.jaxrs.JerseyDockerHttpClient.execute(JerseyDockerHttpClient.java:297)
	at com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:228)
	at com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269)
	at java.lang.Thread.run(Thread.java:748)

**Comment by bsideup** [comment]
The input stream must be in TAR format, see https://github.com/docker-java/docker-java/blob/master/docker-java/src/test/java/com/github/dockerjava/cmd/BuildImageCmdIT.java
