### ISSUE TITLE
exec()  happen  Error closing message content input stream

### ISSUE THREAD

**Issue by pandab0y** [docker-java/docker-java#1535]
This is a problem with releases after 3.1.5
execute InfoCmd.exec()

**Comment by bsideup** [comment]
@pandab0y could you please provide a reproducer?

**Comment by pandab0y** [comment]
My Source
DockerClient dockerClient =
DockerClientBuilder.getInstance(server.getDockerStageConnectInfo()).build();
dockerClient.infoCmd().exec();

Exception in thread "main" javax.ws.rs.ProcessingException: Error closing message content input stream.
	at org.glassfish.jersey.message.internal.EntityInputStream.close(EntityInputStream.java:162)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._closeInput(UTF8StreamJsonParser.java:228)
	at com.fasterxml.jackson.core.base.ParserBase.close(ParserBase.java:368)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4021)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3077)
	at com.github.dockerjava.jaxrs.JerseyInvocationBuilder.get(JerseyInvocationBuilder.java:67)
	at com.github.dockerjava.core.exec.InfoCmdExec.exec(InfoCmdExec.java:24)
	at com.github.dockerjava.core.exec.InfoCmdExec.exec(InfoCmdExec.java:14)
	at com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:35)
	at com.geostar.ai.common.utils.DockerUtil.main(DockerUtil.java:177)
Caused by: org.apache.http.MalformedChunkCodingException: CRLF expected at end of chunk
	at org.apache.http.impl.io.ChunkedInputStream.getChunkSize(ChunkedInputStream.java:250)
	at org.apache.http.impl.io.ChunkedInputStream.nextChunk(ChunkedInputStream.java:222)
	at org.apache.http.impl.io.ChunkedInputStream.read(ChunkedInputStream.java:183)
	at org.apache.http.impl.io.ChunkedInputStream.read(ChunkedInputStream.java:210)
	at org.apache.http.impl.io.ChunkedInputStream.close(ChunkedInputStream.java:312)
	at org.apache.http.impl.execchain.ResponseEntityProxy.streamClosed(ResponseEntityProxy.java:142)
	at org.apache.http.conn.EofSensorInputStream.checkClose(EofSensorInputStream.java:228)
	at org.apache.http.conn.EofSensorInputStream.close(EofSensorInputStream.java:172)
	at java.io.BufferedInputStream.close(BufferedInputStream.java:483)
	at java.io.FilterInputStream.close(FilterInputStream.java:181)
	at org.glassfish.jersey.apache.connector.ApacheConnector$2.close(ApacheConnector.java:659)
	at java.io.FilterInputStream.close(FilterInputStream.java:181)
	at org.glassfish.jersey.apache.connector.ApacheConnector$HttpClientResponseInputStream.close(ApacheConnector.java:636)
	at org.glassfish.jersey.message.internal.EntityInputStream.close(EntityInputStream.java:159)
	... 9 more

**Comment by pandab0y** [comment]
dockerClient.loadImageCmd(inputstream).exec()  also has the Exception

**Comment by pandab0y** [comment]
@bsideup

**Comment by bsideup** [comment]
@pandab0y this code runs fine, so it must be something specific about your environment.

Note that exception says "CRLF expected at end of chunk", so it looks like the Docker daemon isn't sending valid chunks. Do you have some proxy between you & Docker, perhaps? Also, have you tried other transports?

**Comment by pandab0y** [comment]
@bsideup  i tried connect other Docker,  and  the  version  of 3.1.5 is ok ,   version of   3.2.0 have the Exception.

**Comment by bsideup** [comment]
@pandab0y have you tried the latest release (`3.2.7`)?

**Comment by bsideup** [comment]
Also, please try other transports (Apache HttpClient5, OkHttp), as you're using (old and soon to be deprecated) Jersey

**Comment by pandab0y** [comment]
@bsideup Thank you, the problem is solved;  the project of jars conflict,  “docker-java-transport-netty” omitted for duplicate
