### ISSUE TITLE
Error : org/newsclub/net/unix/AFUNIXSocketException

### ISSUE THREAD

**Issue by Nathan-Guillaume** [docker-java/docker-java#1540]
Hello, 

I have a error with Docker-java.

```
Exception in thread "main" javax.ws.rs.ProcessingException: org/newsclub/net/unix/AFUNIXSocketException
        at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:261)
        at org.glassfish.jersey.client.JerseyInvocation$2.call(JerseyInvocation.java:701)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:444)
        at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:697)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:448)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:349)
        at com.github.dockerjava.jaxrs.CreateContainerCmdExec.execute(CreateContainerCmdExec.java:34)
        at com.github.dockerjava.jaxrs.CreateContainerCmdExec.execute(CreateContainerCmdExec.java:15)
        at com.github.dockerjava.jaxrs.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:23)
        at com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:35)
        at com.github.dockerjava.core.command.CreateContainerCmdImpl.exec(CreateContainerCmdImpl.java:177)
        at io.hydroker.hydro.docker.containers.DockerContainer.createContainer(DockerContainer.java:28)
        at io.hydroker.hydro.docker.HydroDocker.main(HydroDocker.java:52)
Caused by: java.lang.NoClassDefFoundError: org/newsclub/net/unix/AFUNIXSocketException
        at org.newsclub.net.unix.AFUNIXSocket.newInstance(AFUNIXSocket.java:78)
        at org.newsclub.net.unix.AFUNIXSocket.newInstance(AFUNIXSocket.java:74)
        at com.github.dockerjava.jaxrs.ApacheUnixSocket.<init>(ApacheUnixSocket.java:51)
        at com.github.dockerjava.jaxrs.UnixConnectionSocketFactory.createSocket(UnixConnectionSocketFactory.java:66)
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:118)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:71)
        at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:435)
        at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:252)
        ... 15 more
Caused by: java.lang.ClassNotFoundException: org.newsclub.net.unix.AFUNIXSocketException
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 30 more
```

I am in java 8, and it gives me this error when I try to start a container
Can you help me? Thank you

**Comment by bsideup** [comment]
Check your classpath, one of the transitive dependencies (`com.kohlschutter.junixsocket:junixsocket-common`) is missing.

**Comment by Nathan-Guillaume** [comment]
the depend is already in pox.xml
```
        <dependency>
            <groupId>com.kohlschutter.junixsocket</groupId>
            <artifactId>junixsocket-common</artifactId>
            <version>2.3.2</version>
        </dependency>
```
