### ISSUE TITLE
Support for Docker Buildkit !

### ISSUE THREAD

**Issue by scila1996** [docker-java/docker-java#1657]
Hi ! Please add support to Docker Buildkit, i was enable 

`{ "features": { "buildkit": true } }`

but it not work if my Dockerfile have `RUN --mount ...` command

```
Step 5/12 : RUN --mount=type=cache,target=/root/.m2 mvn -B dependency:go-offline
```

> com.github.dockerjava.api.exception.DockerClientException: Could not build image: the --mount option requires BuildKit. Refer to https://docs.docker.com/go/buildkit/ to learn how to build images with BuildKit enabled
	at com.github.dockerjava.core.command.BuildImageResultCallback.getImageId(BuildImageResultCallback.java:79)
	at com.github.dockerjava.core.command.BuildImageResultCallback.awaitImageId(BuildImageResultCallback.java:51)
	at com.nirima.jenkins.plugins.docker.builder.DockerBuilderPublisher$Run.buildImage(DockerBuilderPublisher.java:370)
	at com.nirima.jenkins.plugins.docker.builder.DockerBuilderPublisher$Run.run(DockerBuilderPublisher.java:310)
	at com.nirima.jenkins.plugins.docker.builder.DockerBuilderPublisher.perform(DockerBuilderPublisher.java:451)
	at jenkins.tasks.SimpleBuildStep.perform(SimpleBuildStep.java:123)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:80)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:803)
	at hudson.model.Build$BuildExecution.build(Build.java:197)
	at hudson.model.Build$BuildExecution.doRun(Build.java:163)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:513)
	at hudson.model.Run.execute(Run.java:1906)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)

**Comment by bmuschko** [comment]
AFAIKT, there's no support for BuildKit from the API. BuildKit really is its own executable.

@bsideup This has come up as a feature request for my Gradle plugin as well. Do you have any additional insight on support for BuildKit from the Docker Java library?

**Comment by bsideup** [comment]
@bmuschko TBH I have no plans to support it - it is literally a massive Golang-based client-side subsystem of Docker, IIRC they even had to rewrite Docker Compose from Python to Golang to support it, and, given that docker-java is a thin-ish wrapper around **Docker's API**, one could say that "BuildKit for Java" is a project on its own and is outside of docker-java's scope.

**Comment by bmuschko** [comment]
@bsideup Agreed. Yeah, that's kind of how I see it. It's somewhat strange that they didn't think about the API when designing multi-architecture image support.

**Comment by sschuberth** [comment]
> It's somewhat strange that they didn't think about the API when designing multi-architecture image support.

Indeed.

Anyway, if you're up for an adventure @bmuschko, we could consider continuing the work on https://github.com/batect/docker-client which uses the Golang libraries underneath and *does* support BuildKit...

**Comment by sschuberth** [comment]
Can we reopen this now that the [Docker API supports BuildKit](https://github.com/moby/moby/commit/0c3b8ccda7fd71a9d90b29848dce4a2010bced7e)?

**Comment by sschuberth** [comment]
> There is already #1381 - maybe that one and close this as duplicate.

There are several duplicates and all of them are closed... so it does not really matter which one to reopen.

**Comment by tkrah** [comment]
> > There is already #1381 - maybe that one and close this as duplicate.
> 
> There are several duplicates and all of them are closed... so it does not really matter which one to reopen.

I would say take the oldest but you're right, it does not really matter, the PR however is attached to #1381 at the moment.
