### ISSUE TITLE
Native builds (GraalVM) run into UnsatisfiedLinkError libjnidispatch.so

### ISSUE THREAD

**Issue by tgeens** [docker-java/docker-java#1714]
I'm trying to build a native image, using the Spring Native toolchain, from my application that is using `docker-java`.

At runtime, when trying to connect to the docker socket, I'm running into:

```
Exception in thread "docker-java-stream-1584126278" java.lang.UnsatisfiedLinkError: Native library (com/sun/jna/linux-x86-64/libjnidispatch.so) not found in resource path ()
        at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:1033)
        at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:989)
        at com.sun.jna.Native.<clinit>(Native.java:195)
        at com.oracle.svm.core.classinitialization.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:375)
        at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:295)
        at com.github.dockerjava.transport.DomainSocket.<clinit>(DomainSocket.java:54)
        at com.oracle.svm.core.classinitialization.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:375)
        at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:295)
        at com.github.dockerjava.httpclient5.ApacheDockerHttpClientImpl$2.createSocket(ApacheDockerHttpClientImpl.java:123)
        at org.apache.hc.client5.http.impl.io.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:125)
        at org.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:409)
        at org.apache.hc.client5.http.impl.classic.InternalExecRuntime.connectEndpoint(InternalExecRuntime.java:168)
        at org.apache.hc.client5.http.impl.classic.InternalExecRuntime.connectEndpoint(InternalExecRuntime.java:178)
        at org.apache.hc.client5.http.impl.classic.ConnectExec.execute(ConnectExec.java:135)
```

I acknowledge this is most probably not a bug in docker-java, but I was hoping to open a constructive discussion about `docker-java`+`GraalVM` here.

If anyone has some pointers, that would be much appreciated ;-)

**Comment by tgeens** [comment]
After adding `jna` dependency:
```
implementation 'net.java.dev.jna:jna:5.9.0'
```

and providing a `@ResourceHint`:
```
@ResourceHint(patterns = {"com/sun/jna/linux-x86-64/libjnidispatch.so" })
```

we're a step further, but JNA prints the following line: 
```
JNA: Problems loading core IDs: java.lang.Object
```

and stops working, which leads me to this issue:
https://github.com/java-native-access/jna/issues/1172

**Comment by tgeens** [comment]
GraalVM allows you to provide a JNI configuration: https://www.graalvm.org/reference-manual/native-image/JNI/

Spring Native provides the `@TypeHint` annotation to help you generate that configuration:
```
@TypeHint(access = AccessBits.JNI, types = { Object.class })
```

and this has sent me now down the rabbit hole of discovering which classes it needs through trial and error.

Current list of JNI type-hints:
```
@TypeHint(access = AccessBits.JNI, types = {
            // java primitives and base classes
            Object.class, Class.class, Method.class, Buffer.class, ByteBuffer.class,
            String.class, Void.class, Boolean.class, Byte.class, Character.class, Short.class,
            Integer.class, Long.class, Float.class, Double.class,
            CharBuffer.class, ShortBuffer.class, IntBuffer.class, LongBuffer.class, FloatBuffer.class,
            DoubleBuffer.class,

            // JNA classes
            Pointer.class, Native.class, Structure.class, Structure.ByValue.class, Structure.ByReference.class,
            Callback.class, CallbackReference.class
    }, typeNames = {
            // package visible
            "com.sun.jna.CallbackReference.AttachOptions"
    })
```

**Comment by pshirshov** [comment]
In fact this is still not solved.

**Comment by bsideup** [comment]
@pshirshov this looks like an issue with JNA - consider reporting to them.

**Comment by pshirshov** [comment]
I'll submit them a ticket though I'm not sure if that would be correct. Other libraries which rely on JNA (e.g. posgresql driver, netty, etc) work w/o any issues. So far I've found just one dependency in my classpath which is broken on native-image :)

**Comment by bsideup** [comment]
@pshirshov other libraries may not be using that specific API. Also, the error clearly comes from JNA, and other projects seems to be having a similar issue:
https://github.com/scala/bug/issues/12491

**Comment by pshirshov** [comment]
Well, that particular issue seems to be not related to native-image. Seems like they've fixed the problem by bumping jna version.

**Comment by pshirshov** [comment]
@bsideup : JNA developers recommend to use sockets w/o direct mapping: https://github.com/java-native-access/jna/issues/1412#issuecomment-1026114112

Could you try?..

**Comment by bsideup** [comment]
@pshirshov TBH I am not sure what to try here (not sure I understood the suggestion by @matthiasblaesing). I am open if you wish to contribute it!

**Comment by pshirshov** [comment]
I would be happy to but I have no expertise in these low-level socket thingies nor JNA.

**Comment by pshirshov** [comment]
JFYI, the legacy netty transport works fine on GraalVM. It's really sad that it is deprecated/unmaintained while there is no viable alternative.
