### ISSUE TITLE
the authentication config of registry not working with searchImagesCmd

### ISSUE THREAD

**Issue by zhanglinqiang** [docker-java/docker-java#1733]
I'm using sonatype/nexus3 as my docker registry (anonymous access was disabled), I want to interact with my registry through DockerClient, e.g. search, pull, push and other operations. But the authentication information of the registry has no effect.
BTW: Testing Code in the below works well if anonymous access was enabled.

Here is my code example： 

```
try {
            DockerClientConfig config = DefaultDockerClientConfig.createDefaultConfigBuilder()
                    .withDockerHost("tcp://tbm.com.cn:4243")
                    .withDockerTlsVerify(true)
                    .withDockerCertPath("/home/leen/dev/ca/client")
                    .withRegistryUsername("dep")
                    .withRegistryPassword("dep2021")
                    .withRegistryEmail("test.user.com")
                    .withRegistryUrl("tbm.nx")
                    .build();

            DockerHttpClient httpClient = new ApacheDockerHttpClient.Builder()
                    .dockerHost(config.getDockerHost())
                    .sslConfig(config.getSSLConfig())
                    .maxConnections(100)
                    .connectionTimeout(Duration.ofSeconds(30))
                    .responseTimeout(Duration.ofSeconds(45))
                    .build();

            DockerClient dockerClient = DockerClientImpl.getInstance(config, httpClient);

            final AuthCmd authCmd = dockerClient.authCmd();
            final AuthResponse response = authCmd.exec();
            System.out.printf("status: %s\n", response.getStatus());
            System.out.printf("identityToken: %s\n", response.getIdentityToken());
            System.out.printf("rawValues: %s\n", response.getRawValues());

            final SearchImagesCmd searchCmd = dockerClient.searchImagesCmd("tbm.nx/tbmos");
            final List<SearchItem> exec = searchCmd.exec();
            exec.forEach(System.out::println);
        } catch (Exception e) {
            e.printStackTrace();
        }
```

java version:

```
openjdk version "1.8.0_312"
OpenJDK Runtime Environment (build 1.8.0_312-b07)
OpenJDK 64-Bit Server VM (build 25.312-b07, mixed mode)
```

client version:

```
<dependency>
            <groupId>com.github.docker-java</groupId>
            <artifactId>docker-java-core</artifactId>
            <version>3.2.12</version>
        </dependency>
        <dependency>
            <groupId>com.github.docker-java</groupId>
            <artifactId>docker-java-transport-httpclient5</artifactId>
            <version>3.2.12</version>
        </dependency>
```

Stack trace:

```
Connected to the target VM, address: '127.0.0.1:53245', transport: 'socket'
18:48:57.050 [main] DEBUG com.github.dockerjava.core.command.AbstrDockerCmd - Cmd: AuthConfig(username=dep, email=test.user.com, registryAddress=dep.nx, stackOrchestrator=null)
18:48:57.122 [main] DEBUG org.apache.hc.client5.http.impl.classic.InternalHttpClient - ex-00000001: preparing request execution
18:48:57.126 [main] DEBUG org.apache.hc.client5.http.protocol.RequestAddCookies - Cookie spec selected: strict
18:48:57.130 [main] DEBUG org.apache.hc.client5.http.protocol.RequestAuthCache - Auth cache not set in the context
18:48:57.130 [main] DEBUG org.apache.hc.client5.http.impl.classic.ProtocolExec - ex-00000001: target auth state: UNCHALLENGED
18:48:57.130 [main] DEBUG org.apache.hc.client5.http.impl.classic.ProtocolExec - ex-00000001: proxy auth state: UNCHALLENGED
18:48:57.130 [main] DEBUG org.apache.hc.client5.http.impl.classic.ConnectExec - ex-00000001: acquiring connection with route {s}->https://tbm.com.cn:4243
18:48:57.130 [main] DEBUG org.apache.hc.client5.http.impl.classic.InternalHttpClient - ex-00000001: acquiring endpoint (3 MINUTES)
18:48:57.132 [main] DEBUG org.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManager - ex-00000001: endpoint lease request (3 MINUTES) [route: {s}->https://tbm.com.cn:4243][total available: 0; route allocated: 0 of 100; total allocated: 0 of 100]
18:48:57.135 [main] DEBUG org.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManager - ex-00000001: endpoint leased [route: {s}->https://tbm.com.cn:4243][total available: 0; route allocated: 1 of 100; total allocated: 1 of 100]
18:48:57.142 [main] DEBUG org.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManager - ex-00000001: acquired ep-00000000
18:48:57.142 [main] DEBUG org.apache.hc.client5.http.impl.classic.InternalHttpClient - ex-00000001: acquired endpoint ep-00000000
18:48:57.142 [main] DEBUG org.apache.hc.client5.http.impl.classic.ConnectExec - ex-00000001: opening connection {s}->https://tbm.com.cn:4243
18:48:57.143 [main] DEBUG org.apache.hc.client5.http.impl.classic.InternalHttpClient - ep-00000000: connecting endpoint (30000000000 NANOSECONDS)
18:48:57.143 [main] DEBUG org.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManager - ep-00000000: connecting endpoint to https://tbm.com.cn:4243 (30000000000 NANOSECONDS)
18:48:57.146 [main] DEBUG org.apache.hc.client5.http.impl.io.DefaultHttpClientConnectionOperator - http-outgoing-0: connecting to tbm.com.cn/127.0.0.1:4243
18:48:57.146 [main] DEBUG org.apache.hc.client5.http.ssl.SSLConnectionSocketFactory - Connecting socket to tbm.com.cn/127.0.0.1:4243 with timeout 30000000000 NANOSECONDS
18:48:57.167 [main] DEBUG org.apache.hc.client5.http.ssl.SSLConnectionSocketFactory - Enabled protocols: [TLSv1.2]
18:48:57.167 [main] DEBUG org.apache.hc.client5.http.ssl.SSLConnectionSocketFactory - Enabled cipher suites: [TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, TLS_DHE_RSA_WITH_AES_256_GCM_SHA384, TLS_DHE_DSS_WITH_AES_256_GCM_SHA384, TLS_DHE_RSA_WITH_AES_128_GCM_SHA256, TLS_DHE_DSS_WITH_AES_128_GCM_SHA256, TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384, TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256, TLS_DHE_RSA_WITH_AES_256_CBC_SHA256, TLS_DHE_DSS_WITH_AES_256_CBC_SHA256, TLS_DHE_RSA_WITH_AES_128_CBC_SHA256, TLS_DHE_DSS_WITH_AES_128_CBC_SHA256, TLS_ECDH_ECDSA_WITH_AES_256_GCM_SHA384, TLS_ECDH_RSA_WITH_AES_256_GCM_SHA384, TLS_ECDH_ECDSA_WITH_AES_128_GCM_SHA256, TLS_ECDH_RSA_WITH_AES_128_GCM_SHA256, TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA384, TLS_ECDH_RSA_WITH_AES_256_CBC_SHA384, TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA256, TLS_ECDH_RSA_WITH_AES_128_CBC_SHA256, TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA, TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA, TLS_DHE_RSA_WITH_AES_256_CBC_SHA, TLS_DHE_DSS_WITH_AES_256_CBC_SHA, TLS_DHE_RSA_WITH_AES_128_CBC_SHA, TLS_DHE_DSS_WITH_AES_128_CBC_SHA, TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA, TLS_ECDH_RSA_WITH_AES_256_CBC_SHA, TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA, TLS_ECDH_RSA_WITH_AES_128_CBC_SHA, TLS_RSA_WITH_AES_256_GCM_SHA384, TLS_RSA_WITH_AES_128_GCM_SHA256, TLS_RSA_WITH_AES_256_CBC_SHA256, TLS_RSA_WITH_AES_128_CBC_SHA256, TLS_RSA_WITH_AES_256_CBC_SHA, TLS_RSA_WITH_AES_128_CBC_SHA, TLS_EMPTY_RENEGOTIATION_INFO_SCSV]
18:48:57.167 [main] DEBUG org.apache.hc.client5.http.ssl.SSLConnectionSocketFactory - Starting handshake
18:48:57.279 [main] DEBUG org.apache.hc.client5.http.ssl.SSLConnectionSocketFactory - Secure session established
18:48:57.279 [main] DEBUG org.apache.hc.client5.http.ssl.SSLConnectionSocketFactory -  negotiated protocol: TLSv1.2
18:48:57.279 [main] DEBUG org.apache.hc.client5.http.ssl.SSLConnectionSocketFactory -  negotiated cipher suite: TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
18:48:57.279 [main] DEBUG org.apache.hc.client5.http.ssl.SSLConnectionSocketFactory -  peer principal: CN=tbm.com.cn, OU=tbm, O=tbm, L=Beijing, ST=Beijing, C=CN
18:48:57.279 [main] DEBUG org.apache.hc.client5.http.ssl.SSLConnectionSocketFactory -  issuer principal: CN=tbm, OU=tbm, O=tbm, L=Beijing, ST=Beijing, C=CN
18:48:57.283 [main] DEBUG org.apache.hc.client5.http.impl.io.DefaultHttpClientConnectionOperator - http-outgoing-0: connection established 127.0.0.1:37506<->127.0.0.1:4243
18:48:57.283 [main] DEBUG org.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManager - ep-00000000: connected http-outgoing-0
18:48:57.283 [main] DEBUG org.apache.hc.client5.http.impl.classic.InternalHttpClient - ep-00000000: endpoint connected
18:48:57.284 [main] DEBUG org.apache.hc.client5.http.impl.classic.MainClientExec - ex-00000001: executing POST /auth HTTP/1.1
18:48:57.284 [main] DEBUG org.apache.hc.client5.http.impl.io.DefaultManagedHttpClientConnection - http-outgoing-0: set socket timeout to 45000000000 NANOSECONDS
18:48:57.284 [main] DEBUG org.apache.hc.client5.http.impl.classic.InternalHttpClient - ep-00000000: start execution ex-00000001
18:48:57.284 [main] DEBUG org.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManager - ep-00000000: executing exchange ex-00000001 over http-outgoing-0
18:48:57.285 [main] DEBUG org.apache.hc.client5.http.headers - http-outgoing-0 >> POST /auth HTTP/1.1
18:48:57.285 [main] DEBUG org.apache.hc.client5.http.headers - http-outgoing-0 >> accept: application/json
18:48:57.285 [main] DEBUG org.apache.hc.client5.http.headers - http-outgoing-0 >> content-type: application/json
18:48:57.285 [main] DEBUG org.apache.hc.client5.http.headers - http-outgoing-0 >> Accept-Encoding: gzip, x-gzip, deflate
18:48:57.285 [main] DEBUG org.apache.hc.client5.http.headers - http-outgoing-0 >> Content-Length: 173
18:48:57.285 [main] DEBUG org.apache.hc.client5.http.headers - http-outgoing-0 >> Host: tbm.com.cn:4243
18:48:57.285 [main] DEBUG org.apache.hc.client5.http.headers - http-outgoing-0 >> Connection: keep-alive
18:48:57.285 [main] DEBUG org.apache.hc.client5.http.headers - http-outgoing-0 >> User-Agent: Apache-HttpClient/5.0.3 (Java/1.8.0_312)
18:48:57.285 [main] DEBUG org.apache.hc.client5.http.wire - http-outgoing-0 >> "POST /auth HTTP/1.1[\r][\n]"
18:48:57.286 [main] DEBUG org.apache.hc.client5.http.wire - http-outgoing-0 >> "accept: application/json[\r][\n]"
18:48:57.286 [main] DEBUG org.apache.hc.client5.http.wire - http-outgoing-0 >> "content-type: application/json[\r][\n]"
18:48:57.286 [main] DEBUG org.apache.hc.client5.http.wire - http-outgoing-0 >> "Accept-Encoding: gzip, x-gzip, deflate[\r][\n]"
18:48:57.286 [main] DEBUG org.apache.hc.client5.http.wire - http-outgoing-0 >> "Content-Length: 173[\r][\n]"
18:48:57.286 [main] DEBUG org.apache.hc.client5.http.wire - http-outgoing-0 >> "Host: tbm.com.cn:4243[\r][\n]"
18:48:57.286 [main] DEBUG org.apache.hc.client5.http.wire - http-outgoing-0 >> "Connection: keep-alive[\r][\n]"
18:48:57.286 [main] DEBUG org.apache.hc.client5.http.wire - http-outgoing-0 >> "User-Agent: Apache-HttpClient/5.0.3 (Java/1.8.0_312)[\r][\n]"
18:48:57.286 [main] DEBUG org.apache.hc.client5.http.wire - http-outgoing-0 >> "[\r][\n]"
18:48:57.286 [main] DEBUG org.apache.hc.client5.http.wire - http-outgoing-0 >> "{"username":"tbmdep","password":"tbmdep2021","email":"test.user.com","serveraddress":"tbm.nx","auth":null,"registrytoken":null,"identitytoken":null,"stackOrchestrator":null}"
18:48:57.306 [main] DEBUG org.apache.hc.client5.http.wire - http-outgoing-0 << "HTTP/1.1 200 OK[\r][\n]"
18:48:57.306 [main] DEBUG org.apache.hc.client5.http.wire - http-outgoing-0 << "Api-Version: 1.41[\r][\n]"
18:48:57.306 [main] DEBUG org.apache.hc.client5.http.wire - http-outgoing-0 << "Content-Type: application/json[\r][\n]"
18:48:57.306 [main] DEBUG org.apache.hc.client5.http.wire - http-outgoing-0 << "Docker-Experimental: false[\r][\n]"
18:48:57.307 [main] DEBUG org.apache.hc.client5.http.wire - http-outgoing-0 << "Ostype: linux[\r][\n]"
18:48:57.307 [main] DEBUG org.apache.hc.client5.http.wire - http-outgoing-0 << "Server: Docker/20.10.8 (linux)[\r][\n]"
18:48:57.307 [main] DEBUG org.apache.hc.client5.http.wire - http-outgoing-0 << "Date: Tue, 09 Nov 2021 10:48:57 GMT[\r][\n]"
18:48:57.307 [main] DEBUG org.apache.hc.client5.http.wire - http-outgoing-0 << "Content-Length: 48[\r][\n]"
18:48:57.307 [main] DEBUG org.apache.hc.client5.http.wire - http-outgoing-0 << "[\r][\n]"
18:48:57.307 [main] DEBUG org.apache.hc.client5.http.wire - http-outgoing-0 << "{"IdentityToken":"","Status":"Login Succeeded"}[\n]"
18:48:57.309 [main] DEBUG org.apache.hc.client5.http.headers - http-outgoing-0 << HTTP/1.1 200 OK
18:48:57.309 [main] DEBUG org.apache.hc.client5.http.headers - http-outgoing-0 << Api-Version: 1.41
18:48:57.309 [main] DEBUG org.apache.hc.client5.http.headers - http-outgoing-0 << Content-Type: application/json
18:48:57.309 [main] DEBUG org.apache.hc.client5.http.headers - http-outgoing-0 << Docker-Experimental: false
18:48:57.309 [main] DEBUG org.apache.hc.client5.http.headers - http-outgoing-0 << Ostype: linux
18:48:57.309 [main] DEBUG org.apache.hc.client5.http.headers - http-outgoing-0 << Server: Docker/20.10.8 (linux)
18:48:57.309 [main] DEBUG org.apache.hc.client5.http.headers - http-outgoing-0 << Date: Tue, 09 Nov 2021 10:48:57 GMT
18:48:57.309 [main] DEBUG org.apache.hc.client5.http.headers - http-outgoing-0 << Content-Length: 48
18:48:57.313 [main] DEBUG org.apache.hc.client5.http.impl.classic.MainClientExec - ex-00000001: connection can be kept alive for 3 MINUTES
18:48:57.361 [main] DEBUG org.apache.hc.client5.http.impl.classic.InternalHttpClient - ep-00000000: releasing valid endpoint
18:48:57.361 [main] DEBUG org.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManager - ep-00000000: releasing endpoint
18:48:57.361 [main] DEBUG org.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManager - ep-00000000: connection http-outgoing-0 can be kept alive for 3 MINUTES
18:48:57.362 [main] DEBUG org.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManager - ep-00000000: connection released [route: {s}->https://tbm.com.cn:4243][total available: 1; route allocated: 1 of 100; total allocated: 1 of 100]
status: Login Succeeded
identityToken: 
rawValues: {Status=Login Succeeded, IdentityToken=}
18:48:57.363 [main] DEBUG com.github.dockerjava.core.command.AbstrDockerCmd - Cmd: tbm.nx/tbmos,<null>
18:48:57.378 [main] DEBUG org.apache.hc.client5.http.impl.classic.InternalHttpClient - ex-00000002: preparing request execution
18:48:57.378 [main] DEBUG org.apache.hc.client5.http.protocol.RequestAddCookies - Cookie spec selected: strict
18:48:57.378 [main] DEBUG org.apache.hc.client5.http.protocol.RequestAuthCache - Auth cache not set in the context
18:48:57.380 [main] DEBUG org.apache.hc.client5.http.impl.classic.ProtocolExec - ex-00000002: target auth state: UNCHALLENGED
18:48:57.380 [main] DEBUG org.apache.hc.client5.http.impl.classic.ProtocolExec - ex-00000002: proxy auth state: UNCHALLENGED
18:48:57.380 [main] DEBUG org.apache.hc.client5.http.impl.classic.ConnectExec - ex-00000002: acquiring connection with route {s}->https://tbm.com.cn:4243
18:48:57.380 [main] DEBUG org.apache.hc.client5.http.impl.classic.InternalHttpClient - ex-00000002: acquiring endpoint (3 MINUTES)
18:48:57.380 [main] DEBUG org.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManager - ex-00000002: endpoint lease request (3 MINUTES) [route: {s}->https://tbm.com.cn:4243][total available: 1; route allocated: 1 of 100; total allocated: 1 of 100]
18:48:57.381 [main] DEBUG org.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManager - ex-00000002: endpoint leased [route: {s}->https://tbm.com.cn:4243][total available: 0; route allocated: 1 of 100; total allocated: 1 of 100]
18:48:57.381 [main] DEBUG org.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManager - ex-00000002: acquired ep-00000001
18:48:57.381 [main] DEBUG org.apache.hc.client5.http.impl.classic.InternalHttpClient - ex-00000002: acquired endpoint ep-00000001
18:48:57.381 [main] DEBUG org.apache.hc.client5.http.impl.classic.MainClientExec - ex-00000002: executing GET /images/search?term=tbm.nx%2Ftbmos HTTP/1.1
18:48:57.381 [main] DEBUG org.apache.hc.client5.http.impl.io.DefaultManagedHttpClientConnection - http-outgoing-0: set socket timeout to 45000000000 NANOSECONDS
18:48:57.381 [main] DEBUG org.apache.hc.client5.http.impl.classic.InternalHttpClient - ep-00000001: start execution ex-00000002
18:48:57.381 [main] DEBUG org.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManager - ep-00000001: executing exchange ex-00000002 over http-outgoing-0
18:48:57.381 [main] DEBUG org.apache.hc.client5.http.headers - http-outgoing-0 >> GET /images/search?term=tbm.nx%2Ftbmos HTTP/1.1
18:48:57.381 [main] DEBUG org.apache.hc.client5.http.headers - http-outgoing-0 >> accept: application/json
18:48:57.381 [main] DEBUG org.apache.hc.client5.http.headers - http-outgoing-0 >> Accept-Encoding: gzip, x-gzip, deflate
18:48:57.381 [main] DEBUG org.apache.hc.client5.http.headers - http-outgoing-0 >> Host: tbm.com.cn:4243
18:48:57.381 [main] DEBUG org.apache.hc.client5.http.headers - http-outgoing-0 >> Connection: keep-alive
18:48:57.381 [main] DEBUG org.apache.hc.client5.http.headers - http-outgoing-0 >> User-Agent: Apache-HttpClient/5.0.3 (Java/1.8.0_312)
18:48:57.381 [main] DEBUG org.apache.hc.client5.http.wire - http-outgoing-0 >> "GET /images/search?term=tbm.nx%2Ftbmos HTTP/1.1[\r][\n]"
18:48:57.381 [main] DEBUG org.apache.hc.client5.http.wire - http-outgoing-0 >> "accept: application/json[\r][\n]"
18:48:57.381 [main] DEBUG org.apache.hc.client5.http.wire - http-outgoing-0 >> "Accept-Encoding: gzip, x-gzip, deflate[\r][\n]"
18:48:57.381 [main] DEBUG org.apache.hc.client5.http.wire - http-outgoing-0 >> "Host: tbm.com.cn:4243[\r][\n]"
18:48:57.381 [main] DEBUG org.apache.hc.client5.http.wire - http-outgoing-0 >> "Connection: keep-alive[\r][\n]"
18:48:57.381 [main] DEBUG org.apache.hc.client5.http.wire - http-outgoing-0 >> "User-Agent: Apache-HttpClient/5.0.3 (Java/1.8.0_312)[\r][\n]"
18:48:57.381 [main] DEBUG org.apache.hc.client5.http.wire - http-outgoing-0 >> "[\r][\n]"
18:48:57.391 [main] DEBUG org.apache.hc.client5.http.wire - http-outgoing-0 << "HTTP/1.1 500 Internal Server Error[\r][\n]"
18:48:57.391 [main] DEBUG org.apache.hc.client5.http.wire - http-outgoing-0 << "Api-Version: 1.41[\r][\n]"
18:48:57.391 [main] DEBUG org.apache.hc.client5.http.wire - http-outgoing-0 << "Content-Type: application/json[\r][\n]"
18:48:57.391 [main] DEBUG org.apache.hc.client5.http.wire - http-outgoing-0 << "Docker-Experimental: false[\r][\n]"
18:48:57.391 [main] DEBUG org.apache.hc.client5.http.wire - http-outgoing-0 << "Ostype: linux[\r][\n]"
18:48:57.391 [main] DEBUG org.apache.hc.client5.http.wire - http-outgoing-0 << "Server: Docker/20.10.8 (linux)[\r][\n]"
18:48:57.391 [main] DEBUG org.apache.hc.client5.http.wire - http-outgoing-0 << "Date: Tue, 09 Nov 2021 10:48:57 GMT[\r][\n]"
18:48:57.391 [main] DEBUG org.apache.hc.client5.http.wire - http-outgoing-0 << "Content-Length: 41[\r][\n]"
18:48:57.391 [main] DEBUG org.apache.hc.client5.http.wire - http-outgoing-0 << "[\r][\n]"
18:48:57.391 [main] DEBUG org.apache.hc.client5.http.wire - http-outgoing-0 << "{"message":"Unexpected status code 401"}[\n]"
18:48:57.391 [main] DEBUG org.apache.hc.client5.http.headers - http-outgoing-0 << HTTP/1.1 500 Internal Server Error
18:48:57.391 [main] DEBUG org.apache.hc.client5.http.headers - http-outgoing-0 << Api-Version: 1.41
18:48:57.391 [main] DEBUG org.apache.hc.client5.http.headers - http-outgoing-0 << Content-Type: application/json
18:48:57.391 [main] DEBUG org.apache.hc.client5.http.headers - http-outgoing-0 << Docker-Experimental: false
18:48:57.391 [main] DEBUG org.apache.hc.client5.http.headers - http-outgoing-0 << Ostype: linux
18:48:57.391 [main] DEBUG org.apache.hc.client5.http.headers - http-outgoing-0 << Server: Docker/20.10.8 (linux)
18:48:57.391 [main] DEBUG org.apache.hc.client5.http.headers - http-outgoing-0 << Date: Tue, 09 Nov 2021 10:48:57 GMT
18:48:57.391 [main] DEBUG org.apache.hc.client5.http.headers - http-outgoing-0 << Content-Length: 41
18:48:57.392 [main] DEBUG org.apache.hc.client5.http.impl.classic.MainClientExec - ex-00000002: connection can be kept alive for 3 MINUTES
18:48:57.394 [main] DEBUG org.apache.hc.client5.http.impl.classic.InternalHttpClient - ep-00000001: releasing valid endpoint
18:48:57.394 [main] DEBUG org.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManager - ep-00000001: releasing endpoint
18:48:57.395 [main] DEBUG org.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManager - ep-00000001: connection http-outgoing-0 can be kept alive for 3 MINUTES
18:48:57.395 [main] DEBUG org.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManager - ep-00000001: connection released [route: {s}->https://tbm.com.cn:4243][total available: 1; route allocated: 1 of 100; total allocated: 1 of 100]
com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"Unexpected status code 401"}

	at com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247)
	at com.github.dockerjava.core.DefaultInvocationBuilder.get(DefaultInvocationBuilder.java:202)
	at com.github.dockerjava.core.DefaultInvocationBuilder.get(DefaultInvocationBuilder.java:74)
	at com.github.dockerjava.core.exec.SearchImagesCmdExec.execute(SearchImagesCmdExec.java:34)
	at com.github.dockerjava.core.exec.SearchImagesCmdExec.execute(SearchImagesCmdExec.java:15)
	at com.github.dockerjava.core.exec.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:21)
	at com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:35)
	at com.topsec.docker.client.LocalDockerClient.main(LocalDockerClient.java:53)
```

**Comment by GregoryIvo** [comment]
I will post more information soon, but I also seem to be having a similar issue. Cant pull any authenticated containers period?
