### ISSUE TITLE
Multiple LogContainerCmd / Connection Leak ?

### ISSUE THREAD

**Issue by marcust** [docker-java/docker-java#181]
When trying to do two LogContainerCmds the second one waits forever on 

    at org.apache.http.pool.PoolEntryFuture.await(PoolEntryFuture.java:133)
    at org.apache.http.pool.AbstractConnPool.getPoolEntryBlocking(AbstractConnPool.java:282)

unless ``MaxPerRouteConnections`` is set to a higher value.

Now I'm wondering if this is on purpose or an issue. I am calling close on the stream returned by ``LogContainerCmd.exec`` and close on the command, but neither does seem to actually release the underlying connection.

**Comment by marcuslinke** [comment]
@marcust Currently all ```InputStream```s returned from docker-java commands must be read until the end to prevent connection leaks. Closing the ```InputStream``` sadly isn't enough.

**Comment by marcust** [comment]
@marcuslinke And how do I read a Log `InputStream` that is set to `withFollowStream` till the end?

But now I know that it is not supposed to be like this and can have a look if I run into the issue again.

**Comment by marcuslinke** [comment]
@marcust I'm sure we can solve this by returning an  ```InputStream``` wrapper that does handle the connection cleanup when it is closed. Stay tuned. Thanks for reporting anyway!

**Comment by marcuslinke** [comment]
Fixed with https://github.com/docker-java/docker-java/commit/3dff2eaf5e345ba1faec290b0a5223d5b8b81ef8

**Comment by marcust** [comment]
I think we made the situation worse, I see a hang now at
   ``java.lang.Thread.State: RUNNABLE
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.read(SocketInputStream.java:150)
	at java.net.SocketInputStream.read(SocketInputStream.java:121)
	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:136)
	at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:152)
	at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:270)
	at org.apache.http.impl.io.ChunkedInputStream.getChunkSize(ChunkedInputStream.java:240)
	at org.apache.http.impl.io.ChunkedInputStream.nextChunk(ChunkedInputStream.java:206)
	at org.apache.http.impl.io.ChunkedInputStream.read(ChunkedInputStream.java:169)
	at org.apache.http.impl.io.ChunkedInputStream.read(ChunkedInputStream.java:198)
	at org.apache.http.impl.io.ChunkedInputStream.close(ChunkedInputStream.java:287)
	at org.apache.http.impl.execchain.ResponseEntityWrapper.streamClosed(ResponseEntityWrapper.java:120)
	at org.apache.http.conn.EofSensorInputStream.checkClose(EofSensorInputStream.java:227)
	at org.apache.http.conn.EofSensorInputStream.close(EofSensorInputStream.java:174)
	at java.io.BufferedInputStream.close(BufferedInputStream.java:483)
	at java.io.FilterInputStream.close(FilterInputStream.java:181)
	at org.glassfish.jersey.apache.connector.ApacheConnector$HttpClientResponseInputStream.close(ApacheConnector.java:643)
	at org.glassfish.jersey.message.internal.EntityInputStream.close(EntityInputStream.java:157)
	at org.glassfish.jersey.message.internal.InboundMessageContext$EntityContent.close(InboundMessageContext.java:151)
	at org.glassfish.jersey.message.internal.InboundMessageContext.close(InboundMessageContext.java:909)
	at org.glassfish.jersey.client.InboundJaxrsResponse.close(InboundJaxrsResponse.java:163)
	at com.github.dockerjava.jaxrs.util.WrappedResponseInputStream.close(WrappedResponseInputStream.java:54)
	at sun.nio.cs.StreamDecoder.implClose(StreamDecoder.java:378)
	at sun.nio.cs.StreamDecoder.close(StreamDecoder.java:193)
	- locked <0x00000000f7633890> (a java.io.InputStreamReader)
	at java.io.InputStreamReader.close(InputStreamReader.java:199)
	at java.io.BufferedReader.close(BufferedReader.java:525)
``

**Comment by marcuslinke** [comment]
@marcust Unfortunately this is an issue with jersey apache connector. See https://github.com/docker-java/docker-java/issues/196
