### ISSUE TITLE
Doesn't cannot connect to unix://localhost:80 when compiled with GraalVM

### ISSUE THREAD

**Issue by peterschmidt85** [docker-java/docker-java#1820]
Without GraalVM, all is working fine.
When compiled with `native-image` (GraalVM 22.0.0.2, Java 11), it fails to connect to `unix://localhost:80`.
The connection is discarded.

Logs:
```
16:15:03.249 [main] DEBUG com.github.dockerjava.core.command.AbstrDockerCmd - Cmd: ListImagesCmdImpl[]
16:15:03.460 [main] DEBUG com.github.dockerjava.jaxrs.JerseyDockerHttpClient - 1 * Sending client request on thread main
1 > GET unix://localhost:80/images/json
1 > accept: application/json

16:15:03.473 [main] DEBUG org.apache.http.client.protocol.RequestAddCookies - CookieSpec selected: default
16:15:03.479 [main] DEBUG org.apache.http.client.protocol.RequestAuthCache - Auth cache not set in the context
16:15:03.480 [main] DEBUG com.github.dockerjava.jaxrs.JerseyDockerHttpClient$1 - Connection request: [route: {}->unix://localhost:80][total available: 0; route allocated: 0 of 2147483647; total allocated: 0 of 100]
16:15:03.483 [main] DEBUG com.github.dockerjava.jaxrs.JerseyDockerHttpClient$1 - Connection leased: [id: 0][route: {}->unix://localhost:80][total available: 0; route allocated: 1 of 2147483647; total allocated: 1 of 100]
16:15:03.484 [main] DEBUG org.apache.http.impl.execchain.MainClientExec - Opening connection {}->unix://localhost:80
16:15:03.507 [main] DEBUG org.apache.http.impl.conn.DefaultManagedHttpClientConnection - http-outgoing-0: Shutdown connection
16:15:03.507 [main] DEBUG org.apache.http.impl.execchain.MainClientExec - Connection discarded
16:15:03.508 [main] DEBUG com.github.dockerjava.jaxrs.JerseyDockerHttpClient$1 - Connection released: [id: 0][route: {}->unix://localhost:80][total available: 0; route allocated: 0 of 2147483647; total allocated: 0 of 100]
16:15:03.509 [main] INFO org.apache.http.impl.execchain.RetryExec - I/O exception (java.net.SocketException) caught when processing request to {}->unix://localhost:80: Socket is closed
16:15:03.511 [main] DEBUG org.apache.http.impl.execchain.RetryExec - Socket is closed
java.net.SocketException: Socket is closed
        at java.net.Socket.setSoTimeout(Socket.java:1155)
        at com.github.dockerjava.jaxrs.ApacheUnixSocket.lambda$setSoTimeout$3(ApacheUnixSocket.java:170)
        at com.github.dockerjava.jaxrs.ApacheUnixSocket.setSocketOption(ApacheUnixSocket.java:119)
        at com.github.dockerjava.jaxrs.ApacheUnixSocket.setSoTimeout(ApacheUnixSocket.java:170)
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:120)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
        at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:480)
        at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:296)
        at org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$0(JerseyInvocation.java:609)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:205)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:390)
        at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:608)
        at com.github.dockerjava.jaxrs.JerseyDockerHttpClient.execute(JerseyDockerHttpClient.java:297)
        at com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:228)
        at com.github.dockerjava.core.DefaultInvocationBuilder.get(DefaultInvocationBuilder.java:202)
        at com.github.dockerjava.core.DefaultInvocationBuilder.get(DefaultInvocationBuilder.java:74)
        at com.github.dockerjava.core.exec.ListImagesCmdExec.execute(ListImagesCmdExec.java:41)
        at com.github.dockerjava.core.exec.ListImagesCmdExec.execute(ListImagesCmdExec.java:16)
        at com.github.dockerjava.core.exec.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:21)
        at com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:35)
```

**Comment by pshirshov** [comment]
Still important

**Comment by pshirshov** [comment]
Still important

**Comment by pshirshov** [comment]
Duplicate of #1714

**Comment by eddumelendez** [comment]
spring team contributed with https://github.com/oracle/graalvm-reachability-metadata/pull/130

**Comment by NicklasWallgren** [comment]
Still an issue. `com.github.dockerjava.api.model.Info` is missing type hints.

```
Could not find a valid Docker environment. Please check configuration. Attempted configurations were:
        UnixSocketClientProviderStrategy: failed with exception RuntimeException (org.testcontainers.shaded.com.fasterxml.jackson.databind.JsonMappingException: Can not construct instance of com.github.dockerjava.api.model.Info: no suitable constructor found, can not deserialize from Object value (missing default constructor or creator, or perhaps need to add/enable type information?)
```
