### ISSUE TITLE
java.net.SocketTimeoutException: Read timed out

### ISSUE THREAD

**Issue by SmallWhite-yp** [docker-java/docker-java#1878]
09:44:09.679 ERROR c.g.d.api.async.ResultCallbackTemplate   : Error during callback

java.net.SocketTimeoutException: Read timed out
	at java.base/java.net.SocketInputStream.socketRead0(Native Method)
	at java.base/java.net.SocketInputStream.socketRead(SocketInputStream.java:115)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:168)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
	at org.apache.hc.core5.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:149)
	at org.apache.hc.core5.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:280)
	at org.apache.hc.core5.http.impl.io.ChunkedInputStream.getChunkSize(ChunkedInputStream.java:261)
	at org.apache.hc.core5.http.impl.io.ChunkedInputStream.nextChunk(ChunkedInputStream.java:222)

**Comment by SmallWhite-yp** [comment]
buildImageCmd   callback   error

**Comment by Double327** [comment]
i have a same question, have any solution?
