### ISSUE TITLE
Cannot locate specified Dockerfile

### ISSUE THREAD

**Issue by oubaydos** [docker-java/docker-java#1882]
i am using this code to build an image from a dockerfile
```java
public static void main(String[] args) throws Exception {
        File DockerFile = new File("Dockerfile");
        BuildImageCmd temporaryjava = getInstance()
                .buildImageCmd()
                .withDockerfilePath("C:/Users/myUser/Desktop/projects/MyProject/SubDir/Dockerfile");
        execBuild(temporaryjava);
    }
    private static void execBuild(BuildImageCmd buildImageCmd) throws Exception {
        String imageId = buildImageCmd.start().awaitImageId();
        CreateContainerResponse container = getInstance().createContainerCmd(imageId).exec();
        getInstance().startContainerCmd(container.getId()).exec();
        getInstance().waitContainerCmd(container.getId()).start().awaitStatusCode();

    }
```
the dockerfile exists on that path, but i get an error 
```
Exception in thread "main" com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"Cannot locate specified Dockerfile: C:/Users/myUser/Desktop/projects/MyProject/SubDir/Dockerfile"}

	at com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247)
	at com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269)
	at java.base/java.lang.Thread.run(Thread.java:833)
```
ps: getInstance is returning a DockerClient with my configuration

**Comment by oubaydos** [comment]
for anyone interested, i was able to create the docker image using the methods in this repository [https://github.com/oubaydos/DevOpsify/blob/012b7d5dbb70c2b8ad131d31db5231cf8a8493d8/devopsify-backend/src/main/java/com/winchesters/devopsify/service/technologies/docker/repositorydocker/DockerImage.java](devopsify-docker)
