### ISSUE TITLE
Unknown image error (HTTP 500) when trying to pull image (Docker Desktop 4.13.x)

### ISSUE THREAD

**Issue by hesamgha** [docker-java/docker-java#1990]
This issue only happens with `Docker Desktop 4.13.x` on MacOS and using the latest version of `com.github.docker-java:docker-java:3.2.13`.   The code to pull the image:
```java
dockerClient.pullImageCmd("mongo:3.6").exec(PullImageResultCallback())
            .awaitCompletion(300, TimeUnit.SECONDS)
```

The following error is shown:
```
com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: unknown image in /images/create?fromImage=mongo%3A3.6
        at app//com.github.dockerjava.jaxrs.filter.ResponseStatusExceptionFilter.filter(ResponseStatusExceptionFilter.java:68)
        at app//org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply(ClientFilteringStages.java:172)
        at app//org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply(ClientFilteringStages.java:160)
        at app//org.glassfish.jersey.process.internal.Stages.process(Stages.java:147)
        at app//org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:302)
        at app//org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$0(JerseyInvocation.java:662)
        at app//org.glassfish.jersey.client.JerseyInvocation.call(JerseyInvocation.java:697)
        at app//org.glassfish.jersey.client.JerseyInvocation.lambda$runInScope$3(JerseyInvocation.java:691)
        at app//org.glassfish.jersey.internal.Errors.process(Errors.java:292)
        at app//org.glassfish.jersey.internal.Errors.process(Errors.java:274)
        at app//org.glassfish.jersey.internal.Errors.process(Errors.java:205)
        at app//org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:390)
        at app//org.glassfish.jersey.client.JerseyInvocation.runInScope(JerseyInvocation.java:691)
        at app//org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:661)
        at app//com.github.dockerjava.jaxrs.JerseyDockerHttpClient.execute(JerseyDockerHttpClient.java:297)
        at app//com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:228)
        at app//com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269)
        at java.base@11.0.16.1/java.lang.Thread.run(Thread.java:829)
```

Verified the issue does not happen with `Docker Desktop 4.12.0`.

**Comment by joschi** [comment]
See https://github.com/docker/for-mac/issues/6540.

**Comment by joschi** [comment]
@hesamgha As a workaround, you can pull the image using its SHA-256 manifest:
```
mongo@sha256:146c1fd999a660e697aac40bc6da842b005c7868232eb0b7d8996c8f3545b05d
```

**Comment by eddumelendez** [comment]
Thanks for the info @joschi !
