### ISSUE TITLE
On MacOS: ResultCallbackTemplate.onError:52]Error during callback 

### ISSUE THREAD

**Issue by CCcn** [docker-java/docker-java#1992]
```sh
11-04 12:00:25.092.+0800 [ERROR][][docker-java-stream--1412222048][c.g.d.a.a.ResultCallbackTemplate.onError:52]Error during callback
com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"Get \"https://registry.cn-chengdu.aliyuncs.com/v2/\": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"}

	at com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247) ~[docker-java-core-3.2.13.jar:?]
	at com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269) ~[docker-java-core-3.2.13.jar:?]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
11-04 12:00:25.120.+0800 [ERROR][][docker-java-stream--1412222048][c.z.a.a.AIDockerHelper.onError:651]pull image error:Status 500: {"message":"Get \"https://registry.cn-chengdu.aliyuncs.com/v2/\": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"}

com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"Get \"https://registry.cn-chengdu.aliyuncs.com/v2/\": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"}

	at com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247) ~[docker-java-core-3.2.13.jar:?]
	at com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269) ~[docker-java-core-3.2.13.jar:?]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
11-04 12:00:25.121.+0800 [ERROR][][scheduling-1][c.z.a.a.AIDockerHelper._pullImage:506]pull image:registry.cn-chengdu.aliyuncs.com/zpcloud/flowai:dev fail with error:Status 500: {"message":"Get \"https://registry.cn-chengdu.aliyuncs.com/v2/\": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"}

com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"Get \"https://registry.cn-chengdu.aliyuncs.com/v2/\": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"}

	at com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247) ~[docker-java-core-3.2.13.jar:?]
	at com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269) ~[docker-java-core-3.2.13.jar:?]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]


```

**Comment by neandrake** [comment]
This looks like the registry you're pulling from is not responding correctly. The behavior from docker-java seems expected given how the registry is behaving. What behavior do you see when using the equivalent `docker` command?

**Comment by neandrake** [comment]
Or you could be running into #1990

**Comment by eddumelendez** [comment]
Follow #1990
