### ISSUE TITLE
Continue listening to Docker events in face of failure

### ISSUE THREAD

**Issue by yaronr** [docker-java/docker-java#201]
Hi
Cool project!!!

I'm listening to Docker events.
There's a bug in my code, that tries to inspect a container that doesn't exist.
This, in turn, triggers the onException EventCallback. So far so good.

But then, it seems, that further events are not being processed by the system.
Stack trace:

com.github.dockerjava.api.NotFoundException: no such id: 169a73abaea40908efb169f96f37bd365c02a09c5389c97f424ff0ff5b869963

	at com.github.dockerjava.core.util.ResponseStatusExceptionFilter.filter(ResponseStatusExceptionFilter.java:48) ~[docker-java-1.2.0.jar:na]
	at org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply(ClientFilteringStages.java:134) ~[jersey-client-2.13.jar:na]
	at org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply(ClientFilteringStages.java:123) ~[jersey-client-2.13.jar:na]
	at org.glassfish.jersey.process.internal.Stages.process(Stages.java:171) ~[jersey-common-2.13.jar:na]
	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:251) ~[jersey-client-2.13.jar:na]
	at org.glassfish.jersey.client.JerseyInvocation$2.call(JerseyInvocation.java:683) ~[jersey-client-2.13.jar:na]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315) ~[jersey-common-2.13.jar:na]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297) ~[jersey-common-2.13.jar:na]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:228) ~[jersey-common-2.13.jar:na]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:424) ~[jersey-common-2.13.jar:na]
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:679) ~[jersey-client-2.13.jar:na]
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:408) ~[jersey-client-2.13.jar:na]
	at org.glassfish.jersey.client.JerseyInvocation$Builder.get(JerseyInvocation.java:308) ~[jersey-client-2.13.jar:na]
	at com.github.dockerjava.jaxrs.InspectContainerCmdExec.execute(InspectContainerCmdExec.java:27) ~[docker-java-1.2.0.jar:na]
	at com.github.dockerjava.jaxrs.InspectContainerCmdExec.execute(InspectContainerCmdExec.java:13) ~[docker-java-1.2.0.jar:na]
	at com.github.dockerjava.jaxrs.AbstrDockerCmdExec.exec(AbstrDockerCmdExec.java:57) ~[docker-java-1.2.0.jar:na]
	at com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:29) ~[docker-java-1.2.0.jar:na]
	at com.github.dockerjava.core.command.InspectContainerCmdImpl.exec(InspectContainerCmdImpl.java:43) ~[docker-java-1.2.0.jar:na]
	at io.multicloud.agent.Agent$1.onEvent(Agent.java:175) ~[agent.jar:0.1]
	at com.github.dockerjava.jaxrs.EventsCmdExec$EventNotifier.call(EventsCmdExec.java:73) [docker-java-1.2.0.jar:na]
	at com.github.dockerjava.jaxrs.EventsCmdExec$EventNotifier.call(EventsCmdExec.java:46) [docker-java-1.2.0.jar:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_45]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]

**Comment by jtnord** [comment]
see also issue #196 - which is why you are not getting an onComplete callback.

**Comment by marcuslinke** [comment]
Should be fixed. Please test.
