### ISSUE TITLE
Spring boot 3.x jersey upgrade to 3.1.0 namespace changed

### ISSUE THREAD

**Issue by liuruibin** [docker-java/docker-java#2049]
```
java.lang.NoClassDefFoundError: javax/ws/rs/core/Configuration

	at com.github.dockerjava.jaxrs.JerseyDockerHttpClient$Builder.build(JerseyDockerHttpClient.java:120)
	at com.github.dockerjava.core.DockerClientBuilder.build(DockerClientBuilder.java:106)
	at io.metersphere.node.util.DockerClientService.connectDocker(DockerClientService.java:54)
```

**Comment by eddumelendez** [comment]
As you can see [here](https://github.com/docker-java/docker-java/blob/master/docs/transports.md#jersey) there is no plan maintain this module.

> Since Apache HttpClient 5-based transport is available now, there is no reason to keep Jersey and it will eventually be removed.
