### ISSUE TITLE
CreateContainerCmd with HealthCheck cause always error

### ISSUE THREAD

**Issue by nauni77** [docker-java/docker-java#2086]
Hello, I always got this error - if I try to create a container with healthcheck.

```
com.github.dockerjava.api.exception.BadRequestException: Status 400: {"message":"Interval in Healthcheck cannot be less than 1ms"}
	at com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:237)
	at com.github.dockerjava.core.DefaultInvocationBuilder.post(DefaultInvocationBuilder.java:124)
	at com.github.dockerjava.core.exec.CreateContainerCmdExec.execute(CreateContainerCmdExec.java:37)
	at com.github.dockerjava.core.exec.CreateContainerCmdExec.execute(CreateContainerCmdExec.java:13)
	at com.github.dockerjava.core.exec.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:21)
	at com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:35)
	at com.github.dockerjava.core.command.CreateContainerCmdImpl.exec(CreateContainerCmdImpl.java:608)
```
Maybe the reason is: "running a really old version of the docker-api gem. "
( https://github.com/upserve/docker-api/issues/342 )

My example code adding the healthcheck, which causes the exception:
```
    HealthCheck hc = new HealthCheck();
    List<String> healthCheckCommands = new LinkedList<>();
    healthCheckCommands.add("curl --fail http://127.0.0.1:8080/example/say/your/name/");
    healthCheckCommands.add("exit 1");
    hc.withTest(healthCheckCommands);
    hc.withRetries(3);
    hc.withInterval(100L);
    hc.withTimeout(100L);
    hc.withStartPeriod(100L);
    cmdCreate.withHealthcheck(hc);
```
Best reagards, Oli

**Comment by freddyNesa** [comment]
@nauni77 

I had the same issue and found a workaround:

`    hc.withInterval(10000000000L);
    hc.withTimeout(10000000000L);
    hc.withStartPeriod(10000000000L);`

Apparently it expects nanoseconds.

**Comment by eddumelendez** [comment]
From [Docker API](https://docs.docker.com/engine/api/v1.43/#tag/Container/operation/ContainerCreate)

> Interval | integer <int64> The time to wait between checks in nanoseconds. It should be 0 or at least 1000000 (1 ms). 0 means inherit.
> Timeout | integer <int64> The time to wait before considering the check to have hung. It should be 0 or at least 1000000 (1 ms). 0 means inherit.
> StartPeriod | integer <int64> Start period for the container to initialize before starting health-retries countdown in nanoseconds. It should be 0 or at least 1000000 (1 ms). 0 means inherit.

Javadocs can help. PR is welcome.
