### ISSUE TITLE
Incompatibility between org.springframework.boot@3.0.5 and com.github.docker-java@3.3.0

### ISSUE THREAD

**Issue by RuiRocha1991** [docker-java/docker-java#2108]
Hi all,
I'm creating an app that is being developed with spring boot and your plugin.
The app has been around for some time and I started to develop it in Java 8, org.springframework.boot@2.X.X and com.github.docker-java@2.X.X and everything worked correctly.
But I updated the app to use Java 19 and had to update the org.springframework.boot version to the latest one available, for security reasons. With that I also updated yours and since then practically the things that had it working stopped working correctly.
I've been investigating creating new projects with different versions of Java and Spring boot from Spring.io and whenever I used the 3.x.x version of Spring everything stopped working. I was looking at what changes were made and found that it no longer supports Javax, and now they are using Jakarta.

Are you planning to resolve this issue?
Is there any workaround I can do to resolve this on my end?

Regards,
Rui

**Comment by AlohaJava** [comment]
save error

**Comment by eddumelendez** [comment]
@RuiRocha1991 thanks for raising the issue. May I ask, are you using docker-java directly or through Testcontainers? I guess using it directly but want to confirm

**Comment by RuiRocha1991** [comment]
Hi @eddumelendez, I'm using docker-java directly. For now, I am using this framework to calculate the space occupied by containers and images and prune containers.

**Comment by rwanderc** [comment]
I didn't get very deep in the investigation but it seems it's due to the migration to Jakarta in Spring Boot 3.
`docker-java-transport-jersey` seems yet to depend on `javax`.

```
Caused by: java.lang.NoClassDefFoundError: javax/ws/rs/core/Configuration
	at com.github.dockerjava.jaxrs.JerseyDockerHttpClient$Builder.build(JerseyDockerHttpClient.java:124) ~[docker-java-transport-jersey-3.3.0.jar:na]
	at com.github.dockerjava.core.DockerClientBuilder.build(DockerClientBuilder.java:106) ~[docker-java-3.3.0.jar:na]
	at test.config.DockerConfig.dockerClient(DockerConfig.java:19) ~[classes/:na]
	at test.config.DockerConfig$$SpringCGLIB$$0.CGLIB$dockerClient$0(<generated>) ~[classes/:na]
	at test.config.DockerConfig$$SpringCGLIB$$2.invoke(<generated>) ~[classes/:na]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:258) ~[spring-core-6.0.8.jar:6.0.8]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331) ~[spring-context-6.0.8.jar:6.0.8]
	at test.config.DockerConfig$$SpringCGLIB$$0.dockerClient(<generated>) ~[classes/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:139) ~[spring-beans-6.0.8.jar:6.0.8]
	... 25 common frames omitted
Caused by: java.lang.ClassNotFoundException: javax.ws.rs.core.Configuration
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[na:na]
	... 38 common frames omitted
```

**Comment by Nowheresly** [comment]
I had the same issue and fixed it by migrating to the httpclient5 transport as explained [here](https://github.com/docker-java/docker-java/blob/main/docs/transports.md#apache-httpclient-5).
The documentation is pretty clear about the fact that the jersey transport is no more the recommended approach.

**Comment by jinsuichen** [comment]
> I had the same issue and fixed it by migrating to the httpclient5 transport as explained [here](https://github.com/docker-java/docker-java/blob/main/docs/transports.md#apache-httpclient-5). The documentation is pretty clear about the fact that the jersey transport is no more the recommended approach.

You're right. This approach can solve the problem, but the project migration will require a lot of effort :(

**Comment by garikhgh** [comment]
I have the same problem. and could not find any code snippet to resolve the issue.

**Comment by rwanderc** [comment]
Did you try excluding `docker-java-transport-jersey` from classpath and adding `docker-java-transport-httpclient5`?
Snippet will not help much as it depends on your specific dependencies (e.g. if other libs are bringing the broken one to the classpath).
You can run `mvn dependency:tree` (or the plugin Maven Helper for IntelliJ, which is very useful) to check whether the broken lib is contained in any of the libraries you are using, and make an explicit exclusion like this:
```
<project>
    ...
    <dependencies>
        ...
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-text</artifactId>
            <version>1.1</version>
            <exclusions>
                <exclusion>
                    <groupId>org.apache.commons</groupId>
                    <artifactId>commons-lang3</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
    </dependencies>
    ...
</project>
```

**Comment by eddumelendez** [comment]
As mentioned in the [docs](https://github.com/docker-java/docker-java/blob/main/docs/transports.md#apache-httpclient-5), Apache HttpClient 5 is the recommended transport.
