### ISSUE TITLE
Roundtrip of InspectContainerResponse fails (VolumeBinds)

### ISSUE THREAD

**Issue by oleg-nenashev** [docker-java/docker-java#211]
Seems <code>@JsonIgnore</code> does not work as expected.

Reproduction steps (use <code>ObjectMapper</code>):
1) Import <code>InspectContainerResponse</code> from an external <code>docker inspect containerId</code> output
2) Export <code>InspectContainerResponse</code> to a string
3) Import <code>InspectContainerResponse</code> again. An exception happens 

Error happens during the serialization of InspectContainerResponse.volumes:
* Expected JSON output: <code>"Volumes":{}</code>
* Actual JSON output: <code>"Volumes":{"binds":[]}</code>

Error could be handled on deserialization side as well.

Exception:
```
Expected path for 'binds'in host but got '[]'.
 at [Source: java.io.StringReader@3c07e830; line: 1, column: 2244] (through reference chain: com.github.dockerjava.api.command.InspectContainerResponse["Volumes"])
com.fasterxml.jackson.databind.JsonMappingException
 at [Source: java.io.StringReader@3c07e830; line: 1, column: 2244] (through reference chain: com.github.dockerjava.api.command.InspectContainerResponse["Volumes"])
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:164)
	at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:608)
	at com.github.dockerjava.api.model.VolumeBinds$Deserializer.deserialize(VolumeBinds.java:43)
	at com.github.dockerjava.api.model.VolumeBinds$Deserializer.deserialize(VolumeBinds.java:31)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:375)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:107)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:308)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:121)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:147)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:18)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:2797)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:1943)
	at 
```

**Comment by marcuslinke** [comment]
```InspectContainerResponse``` especially its sub object  ```VolumeBinds``` is not intended to be serialized back to a json string. There is no ```JsonSerializer``` for ```VolumeBinds``` implemented.

See https://github.com/docker-java/docker-java/blob/master/src/main/java/com/github/dockerjava/api/model/VolumeBinds.java#L20

```@JsonIgnore``` [here](https://github.com/docker-java/docker-java/blob/master/src/main/java/com/github/dockerjava/api/command/InspectContainerResponse.java#L122) is only to prevent serialization/deserialization of the ```getVolumes()``` method/member which hides the private ```volumes```member and is of type array of  ```VolumeBind```. But the "volumes" property must not be handled as array. With ```@JsonIgnore``` instead the private ```volumes``` member is used which is a ```VolumeBinds``` object with its own ```JsonDeserializer```.

**Comment by oleg-nenashev** [comment]
@marcuslinke 
i consider implementing <code>JsonSerializer</code> in <code>VolueBinds</code>. According to my docker-java use-case, I may need to implement missing serializers in all child objects of <code> InspectContainerResponse</code> and <code> InspectImageResponse</code> .

Would be such PR acceptable if I provide appropriate unit tests?

**Comment by marcuslinke** [comment]
Sure. Awaiting your PR... Closing for now.
