### ISSUE TITLE
 Unable to locate JNA native support library

### ISSUE THREAD

**Issue by godfather1103** [docker-java/docker-java#2141]
Exception in thread "docker-java-stream-1432687647" java.lang.UnsatisfiedLinkError: Unable to locate JNA native support library
	at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:1018)
	at com.sun.jna.Native.<clinit>(Native.java:221)
	at com.github.dockerjava.transport.DomainSocket.<clinit>(DomainSocket.java:54)
	at com.github.dockerjava.transport.UnixSocket.get(UnixSocket.java:29)
	at com.github.dockerjava.okhttp.UnixSocketFactory.createSocket(UnixSocketFactory.java:21)
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:257)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:183)
	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.java:224)
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.java:108)
	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.java:88)
	at okhttp3.internal.connection.Transmitter.newExchange(Transmitter.java:169)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:41)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
	at okhttp3.RealCall.execute(RealCall.java:81)
	at com.github.dockerjava.okhttp.OkDockerHttpClient$OkResponse.<init>(OkDockerHttpClient.java:260)
	at com.github.dockerjava.okhttp.OkDockerHttpClient.execute(OkDockerHttpClient.java:234)
	at com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:228)
	at com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by godfather1103** [comment]
I use docker-Java in the Gradle plugin,When I enable the Gradle domain, it can succeed the first time and report an error the second time.

**Comment by godfather1103** [comment]
docker-java-core:3.3.2

**Comment by eddumelendez** [comment]
can you provide more info? os, arch?

**Comment by godfather1103** [comment]
MacBook Pro
Intel Core i7
macOS 13.4.1 (22F82)

**Comment by godfather1103** [comment]
docker-java-transport-netty is OK.

docker-java-transport-okhttp and docker-java-transport-httpclient5 report error.

**Comment by godfather1103** [comment]
Perhaps it was a problem with the system environment at that time, and the relevant issues cannot be reproduced now
