### ISSUE TITLE
java.lang.NoClassDefFoundError: com/github/dockerjava/core/DockerClientConfig when moved to 3.2.9 or later version during application boot up

### ISSUE THREAD

**Issue by prashant-kahalkar-bh** [docker-java/docker-java#2167]
Hi,
In my maven spring-boot application have docker-java lib version 3.2.8 which works well however when I try update the version to 3.2.9 or later version, I get NoClassDefFoundException. 
`     at com.ge.ogd.pipeline.control.service.PipelineControlServiceBootApplication.main(PipelineControlServiceBootApplication.java:75) [pipeline-control-service-1.1.1.jar:1.1.1]
Caused by: java.lang.NoClassDefFoundError: com/github/dockerjava/core/DockerClientConfig
        at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?]
        at java.lang.Class.privateGetDeclaredMethods(Unknown Source) ~[?:?]
        at java.lang.Class.getDeclaredMethods(Unknown Source) ~[?:?]
        at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:465) ~[spring-core-6.0.9.jar:6.0.9]
        ... 21 more
Caused by: java.lang.ClassNotFoundException: com.github.dockerjava.core.DockerClientConfig
        at jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source) ~[?:?]`
        

Below is my config class code where I am creating the bean at application start 
` @ Bean
  public DockerClient getDefaultDockerClient() {
      DefaultDockerClientConfig clientConfig = DefaultDockerClientConfig.createDefaultConfigBuilder().build();

	  DockerHttpClient httpClient = new ApacheDockerHttpClient.Builder()
			    .dockerHost(clientConfig.getDockerHost())
			    .build();

	  return DockerClientBuilder.getInstance(clientConfig)
			  .withDockerHttpClient(httpClient)
			  .build();
  } `
And this is my docker file looks like (I didn't capture all content in docker file)
![image](https://github.com/docker-java/docker-java/assets/96828575/233b9e99-e10f-4f82-891b-92388396c0c0)

Below are dependencies used for docker client.
![image](https://github.com/docker-java/docker-java/assets/96828575/6ca6e8f5-8dae-4457-8612-a2861e3121d5)

Spring-boot version  - 3.1.0
JRE  - 17

Can someone please help me understand the possible cause for it and any suggestions for remediation?

**Comment by eddumelendez** [comment]
Hi, make sure all your docker java dependencies are using the same version

**Comment by eddumelendez** [comment]
Closing due to lack of activity. @prashant-kahalkar-bh if still have the issue feel free to reopen.
