### ISSUE TITLE
connect docker has error

### ISSUE THREAD

**Issue by lyon-wz** [docker-java/docker-java#2290]
caught when processing  request to {}->unix://localhost:2375 ,but my host config is unix://var/run/docker.sock ,so where is localhost:2375

**Comment by SeBBBe** [comment]
Seeing something similar in a Spring Boot project when upgrading to Spring Boot 3.2.1:

```
java.lang.RuntimeException: org.apache.hc.client5.http.HttpHostConnectException: Connect to unix://localhost:2375 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused

	at com.github.dockerjava.httpclient5.ApacheDockerHttpClientImpl.execute(ApacheDockerHttpClientImpl.java:195)
	at com.github.dockerjava.httpclient5.ApacheDockerHttpClient.execute(ApacheDockerHttpClient.java:9)
	at com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:228)
	at com.github.dockerjava.core.DefaultInvocationBuilder.get(DefaultInvocationBuilder.java:202)
	at com.github.dockerjava.core.DefaultInvocationBuilder.get(DefaultInvocationBuilder.java:74)
	at com.github.dockerjava.core.exec.ListContainersCmdExec.execute(ListContainersCmdExec.java:44)
	at com.github.dockerjava.core.exec.ListContainersCmdExec.execute(ListContainersCmdExec.java:15)
	at com.github.dockerjava.core.exec.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:21)
	at com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:33)
```

**Comment by azuenko** [comment]
Same issue here.

**Comment by lyon-wz** [comment]
[request processing failed;nested exception is java.lang.RuntimeException:java.io.IOException: docker-java com.sun.jna.LasteErrorException:[2] No such file or directory ] with root cause

**Comment by Sineaggi** [comment]
I've opened a PR with a fix for this here https://github.com/docker-java/docker-java/pull/2294

**Comment by izian** [comment]
We just landed here because we upgraded spring boot plugin for Gradle to 3.2.1 and the world came crashing down in our build pipeline as a result of the new apache code pulled in.
