### ISSUE TITLE
Build from Dockerfile gives Exception in thread "main" com.github.dockerjava.api.InternalServerErrorException: unexpected EOF

### ISSUE THREAD

**Issue by derzaicheg** [docker-java/docker-java#236]
Hi!

I am trying to create an image from Dockerfile and getting exception:	
public class DockerHelper { 
protected final Logger logger;
	private DockerClient dockerClient;
	private String host;
	
	public DockerHelper(Logger logger) throws PropertyNotExistsException, IOException{
		this.logger = logger;
		TestSettings testSettings = new TestSettings(logger);
		this.host = testSettings
				.getProperty(JCTestProperties.DOCKER_SERVER_HOST);
		this.dockerClient = DockerClientBuilder.getInstance("http://" + this.host + ":2375").build();
	}	

public void buildFromDockerfile() throws IOException{
		final InputStream input = getClass().getClassLoader().getResourceAsStream("dockerfiles/centos");
		InputStream response = dockerClient.buildImageCmd(input).exec();
		StringWriter logwriter = new StringWriter();
		
		try {
		    LineIterator itr = IOUtils.lineIterator(response, "UTF-8");
		    while (itr.hasNext()) {
		        String line = itr.next();
		        logwriter.write(line);
		        logger.info(line);
		    }
		} finally {
		    IOUtils.closeQuietly(response);
		}
	}
}

gives an exception:

01:35:39.410 [main] DEBUG c.g.d.core.command.AbstrDockerCmd - Cmd: build 
01:35:39.418 [main] DEBUG c.g.d.jaxrs.BuildImageCmdExec - POST: JerseyWebTarget { http://192.168.0.108:2375/build }
Exception in thread "main" com.github.dockerjava.api.InternalServerErrorException: unexpected EOF

	at com.github.dockerjava.core.util.ResponseStatusExceptionFilter.filter(ResponseStatusExceptionFilter.java:54)
	at org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply(ClientFilteringStages.java:134)
	at org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply(ClientFilteringStages.java:123)
	at org.glassfish.jersey.process.internal.Stages.process(Stages.java:171)
	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:251)
	at org.glassfish.jersey.client.JerseyInvocation$2.call(JerseyInvocation.java:683)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:424)
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:679)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:435)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:338)
	at com.github.dockerjava.jaxrs.BuildImageCmdExec.execute(BuildImageCmdExec.java:66)
	at com.github.dockerjava.jaxrs.BuildImageCmdExec.execute(BuildImageCmdExec.java:25)
	at com.github.dockerjava.jaxrs.AbstrDockerCmdExec.exec(AbstrDockerCmdExec.java:57)
	at com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:29)
	at com.irdeto.control.common.helpers.DockerHelper.buildFromDockerfile(DockerHelper.java:39)
	at com.irdeto.control.common.helpers.DockerHelper.main(DockerHelper.java:61)

**Comment by yamateh** [comment]
why close the issue? @derzaicheg

**Comment by KostyaSha** [comment]
I think API was changed and i see no issues with building dockerfile. 
@yamateh do you still has this issue?

**Comment by derzaicheg** [comment]
I was able to void this problem, maybe I missused this functionality. 
The working example how did I use you can find here:
[example](https://github.com/derzaicheg/JavaDockerApi/blob/master/src/main/java/com/skozlov/breed/common/helpers/docker/DockerHelperImpl.java)

**Comment by lusains** [comment]
I met the same problem，building dockerfile with inputstream~ but change to file works.
I don‘t know way~ maybe System formatting problem~ (linux & windows).
