### ISSUE TITLE
DockerClient.inspectContainerCmd() fails when Capabilities are not in uppercase

### ISSUE THREAD

**Issue by defung** [docker-java/docker-java#2365]
### Version Information
com.github.docker-java:docker-java-core:3.4.0
com.github.docker-java:docker-java-transport-httpclient5:3.4.0

Docker version:
```
Client:
 Version:           27.2.0
 API version:       1.47
 Go version:        go1.21.13
 Git commit:        3ab4256
 Built:             Tue Aug 27 14:14:45 2024
 OS/Arch:           darwin/arm64
 Context:           desktop-linux

Server: Docker Desktop 4.34.0 (165256)
 Engine:
  Version:          27.2.0
  API version:      1.47 (minimum version 1.24)
  Go version:       go1.21.13
  Git commit:       3ab5c7d
  Built:            Tue Aug 27 14:15:41 2024
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.7.20
  GitCommit:        8fc6bcff51318944179630522a095cc9dbf9f353
 runc:
  Version:          1.1.13
  GitCommit:        v1.1.13-0-g58aa920
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### Steps to reproduce
1. Create a container with the following command:
    ```
    docker run --rm --cap-add net_admin -d nginx
    ```
2. Compile and run the following java code:
    ```
    import com.github.dockerjava.api.DockerClient;
    import com.github.dockerjava.core.*;
    import com.github.dockerjava.httpclient5.ApacheDockerHttpClient;
    import com.github.dockerjava.transport.DockerHttpClient;
    
    import java.net.URI;
    
    public class DockerTest {
      public static void main(String[] args) {
        DockerClientConfig config = DefaultDockerClientConfig.createDefaultConfigBuilder()
          .withDockerHost("unix:///var/run/docker.sock")
          .withDockerTlsVerify(false)
          .withApiVersion(RemoteApiVersion.VERSION_1_42)
          .build();
    
        DockerHttpClient httpClient = new ApacheDockerHttpClient.Builder()
          .dockerHost(URI.create("unix:///var/run/docker.sock"))
          .build();
    
        DockerClient client = DockerClientImpl.getInstance(config, httpClient);
    
        client.inspectContainerCmd("<container_id>").exec();  // replace this with actual container id
      }
    }
    ```
3. The following exception is thrown:
    ```
    Exception in thread "main" java.lang.RuntimeException: com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `com.github.dockerjava.api.model.Capability` from String "net_admin": not one of the values accepted for Enum class: [ALL, SYS_BOOT, DAC_OVERRIDE, NET_RAW, BLOCK_SUSPEND, FOWNER, IPC_LOCK, IPC_OWNER, SYS_PACCT, NET_BIND_SERVICE, WAKE_ALARM, FSETID, DAC_READ_SEARCH, SYS_CHROOT, AUDIT_READ, SYS_RAWIO, SYS_ADMIN, KILL, MAC_ADMIN, SYS_RESOURCE, CHOWN, PERFMON, SETPCAP, SYS_PTRACE, NET_ADMIN, SETFCAP, SYS_NICE, LINUX_IMMUTABLE, BPF, AUDIT_CONTROL, LEASE, AUDIT_WRITE, SYS_MODULE, MKNOD, SYSLOG, MAC_OVERRIDE, SYS_TIME, SETGID, SETUID, CHECKPOINT_RESTORE, SYS_TTY_CONFIG, NET_BROADCAST]
    at [Source: UNKNOWN; byte offset: #UNKNOWN] (through reference chain: com.github.dockerjava.api.command.InspectContainerResponse["HostConfig"]->com.github.dockerjava.api.model.HostConfig["CapAdd"]->java.lang.Object[][0])
    at com.github.dockerjava.core.DefaultInvocationBuilder.get(DefaultInvocationBuilder.java:77)
    at com.github.dockerjava.core.exec.InspectContainerCmdExec.execute(InspectContainerCmdExec.java:31)
    at com.github.dockerjava.core.exec.InspectContainerCmdExec.execute(InspectContainerCmdExec.java:13)
    at com.github.dockerjava.core.exec.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:21)
    at com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:33)
    at com.github.dockerjava.core.command.InspectContainerCmdImpl.exec(InspectContainerCmdImpl.java:51)
    at dockerbug.DockerTest.main(DockerTest.java:24)

    ```
5. Start another container with the following:
    ```
    docker run --rm --cap-add NET_ADMIN -d nginx
    ```
7. Run the java program again with the new id from step 5, and now it runs without error.
8. Same issue is seen using `--cap-drop net_admin`

**Comment by corrosive4354** [comment]
When creating a container, make sure to use uppercase capability names. For example:
docker run --rm --cap-add NET_ADMIN -d nginx
This way, you won't encounter deserialization issues when calling Java code.

Seeing that you are using docker, I would like to recommend [Servbay](servbay.com) to you, which is more professional and easy to use than docker on mac

**Comment by defung** [comment]
@corrosive4354 if I was the one creating the container, then yes, I could avoid this issue by making it all caps. I recently have been playing around with nomad, and containers created from nomad seems to add/drop capabilities internally using lowercase. I don't have as much control over those unfortunately. But regardless, docker itself does support capabilities lists in lowercase, so I feel this library should too.

Appreciate the recommendation for Servbay, will definitely take a look!

**Comment by eddumelendez** [comment]
Fixed via #2418
