### ISSUE TITLE
Search Result Showing the image, however while creating container Error message "No Such Images"

### ISSUE THREAD

**Issue by kapilag** [docker-java/docker-java#285]
Hi
I am trying to create few containers of selenium using docker-java library however facing a very unusual behavior.
Below is the code 
`
DockerClient dockerClient = DockerClientBuilder.getInstance("unix:///var/run/docker.sock").build();
Info info = dockerClient.infoCmd().exec();
List<SearchItem> dockerSearch = dockerClient.searchImagesCmd("selenium/node-chrome").exec();
System.out.println("Search returned:"+dockerSearch.get(0).getName());
CreateContainerResponse container2 = dockerClient.createContainerCmd("selenium/node-chrome").withName("Chrome").exec();
dockerClient.startContainerCmd(container2.getId());
`

while running this search results are returning the image name, however while creating container below error message is thrown

` 
Search returned:selenium/node-chrome
Exception in thread "main" com.github.dockerjava.api.NotFoundException: No such image: selenium/node-chrome (tag: latest)
at com.github.dockerjava.jaxrs.filter.ResponseStatusExceptionFilter.filter(ResponseStatusExceptionFilter.java:47)
	at org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply(ClientFilteringStages.java:134)
	at org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply(ClientFilteringStages.java:123)
	at org.glassfish.jersey.process.internal.Stages.process(Stages.java:171)
	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:251)
	at org.glassfish.jersey.client.JerseyInvocation$2.call(JerseyInvocation.java:683)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:424)
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:679)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:435)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:338)
	at com.github.dockerjava.jaxrs.CreateContainerCmdExec.execute(CreateContainerCmdExec.java:32)
	at com.github.dockerjava.jaxrs.CreateContainerCmdExec.execute(CreateContainerCmdExec.java:14)
	at com.github.dockerjava.jaxrs.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:24)
	at com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:33)
	at com.github.dockerjava.core.command.CreateContainerCmdImpl.exec(CreateContainerCmdImpl.java:143)
	at DockerMain.main(DockerMain.java:31)

`

**Comment by kapilag** [comment]
How silly of me, forgot to pull the image :(
