### ISSUE TITLE
Unrecognized field "stream"

### ISSUE THREAD

**Issue by akostadinov** [docker-java/docker-java#321]
I'm sorry for the spam, wrong bug tracker. Please close the issue.

FYI moved this report to proper place https://issues.jenkins-ci.org/browse/JENKINS-30422

Trying docker plugin with docker 1.8.1.fc22 and docker plug-in 0.13.0 and jenkins LTS 1.609.3

You'll see error below. One more strange thing I see is that in jenkins system configuration I see "Credentials" under docker cloud. But I can select no creadentials. It gives only "none" as an option. Under image template I see credentials and I can select them so perhaps it is ok.

The error jenkins system log is:
```
Sep 11, 2015 4:10:33 PM INFO com.nirima.jenkins.plugins.docker.DockerCloud provision

Asked to provision 1 slave(s) for: docker&&cucushift_v3

Sep 11, 2015 4:10:33 PM INFO com.nirima.jenkins.plugins.docker.DockerCloud provision

Will provision 'docker-registry.example.com/cryan/cucushift:latest', for label: 'docker&&cucushift_v3', in cloud: 'MTV Docker VM'

Sep 11, 2015 4:10:33 PM INFO com.nirima.jenkins.plugins.docker.DockerCloud addProvisionedSlave

Provisioning 'docker-registry.example.com/cryan/cucushift:latest' number '0' on 'MTV Docker VM'; Total containers: '0'

Sep 11, 2015 4:10:33 PM INFO hudson.slaves.NodeProvisioner$StandardStrategyImpl apply

Started provisioning Image of docker-registry.example.com/cryan/cucushift:latest from MTV Docker VM with 1 executors. Remaining excess workload: 0

Sep 11, 2015 4:10:34 PM INFO com.nirima.jenkins.plugins.docker.DockerCloud pullImage

Pulling image 'docker-registry.example.com/cryan/cucushift:latest' again. This may take awhile...

Sep 11, 2015 4:10:34 PM SEVERE com.github.dockerjava.core.async.ResultCallbackTemplate onError

Error during callback
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "stream" (class com.github.dockerjava.api.model.PullResponseItem), not marked as ignorable (6 known properties: , "status", "error", "errorDetail", "id", "progress", "progressDetail"])
 at [Source: com.github.dockerjava.jaxrs.util.WrappedResponseInputStream@391533f1; line: 1, column: 12] (through reference chain: com.github.dockerjava.api.model.PullResponseItem["stream"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:79)
	at com.fasterxml.jackson.databind.DeserializationContext.reportUnknownProperty(DeserializationContext.java:579)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:672)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:906)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:328)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:121)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:2769)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:1478)
	at com.github.dockerjava.core.async.JsonStreamProcessor.processResponseStream(JsonStreamProcessor.java:44)
	at com.github.dockerjava.jaxrs.async.AbstractCallbackNotifier.call(AbstractCallbackNotifier.java:62)
	at com.github.dockerjava.jaxrs.async.AbstractCallbackNotifier.call(AbstractCallbackNotifier.java:22)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

Sep 11, 2015 4:10:34 PM SEVERE com.nirima.jenkins.plugins.docker.DockerCloud$1 call

Error in provisioning; template='DockerTemplate{configVersion=2, labelString='cucushift_v3 docker', launcher=com.nirima.jenkins.plugins.docker.launcher.DockerComputerSSHLauncher@6525604d, remoteFsMapping='', remoteFs='/home/robot/workspace', instanceCap=2147483647, mode=NORMAL, retentionStrategy=com.nirima.jenkins.plugins.docker.strategy.DockerOnceRetentionStrategy@dad0f97, numExecutors=1, dockerTemplateBase=DockerTemplateBase{image=docker-registry.example.com/cryan/cucushift:latest}, removeVolumes=false, pullStrategy=PULL_LATEST}' for cloud='MTV Docker VM'
com.github.dockerjava.api.DockerClientException: Could not pull image
	at com.github.dockerjava.core.command.PullImageResultCallback.awaitSuccess(PullImageResultCallback.java:44)
	at com.nirima.jenkins.plugins.docker.DockerCloud.pullImage(DockerCloud.java:336)
	at com.nirima.jenkins.plugins.docker.DockerCloud.provisionWithWait(DockerCloud.java:343)
	at com.nirima.jenkins.plugins.docker.DockerCloud.access$000(DockerCloud.java:58)
	at com.nirima.jenkins.plugins.docker.DockerCloud$1.call(DockerCloud.java:233)
	at com.nirima.jenkins.plugins.docker.DockerCloud$1.call(DockerCloud.java:230)
	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

Sep 11, 2015 4:10:43 PM WARNING hudson.slaves.NodeProvisioner$2 run

Provisioned slave Image of docker-registry.example.com/cryan/cucushift:latest failed to launch
com.github.dockerjava.api.DockerClientException: Could not pull image
	at com.github.dockerjava.core.command.PullImageResultCallback.awaitSuccess(PullImageResultCallback.java:44)
	at com.nirima.jenkins.plugins.docker.DockerCloud.pullImage(DockerCloud.java:336)
	at com.nirima.jenkins.plugins.docker.DockerCloud.provisionWithWait(DockerCloud.java:343)
	at com.nirima.jenkins.plugins.docker.DockerCloud.access$000(DockerCloud.java:58)
	at com.nirima.jenkins.plugins.docker.DockerCloud$1.call(DockerCloud.java:233)
	at com.nirima.jenkins.plugins.docker.DockerCloud$1.call(DockerCloud.java:230)
	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

Sep 11, 2015 4:10:43 PM INFO com.nirima.jenkins.plugins.docker.DockerCloud provision

Asked to provision 1 slave(s) for: docker&&cucushift_v3

Sep 11, 2015 4:10:43 PM INFO com.nirima.jenkins.plugins.docker.DockerCloud provision

Will provision 'docker-registry.example.com/cryan/cucushift:latest', for label: 'docker&&cucushift_v3', in cloud: 'MTV Docker VM'

Sep 11, 2015 4:10:43 PM INFO com.nirima.jenkins.plugins.docker.DockerCloud addProvisionedSlave

Provisioning 'docker-registry.example.com/cryan/cucushift:latest' number '0' on 'MTV Docker VM'; Total containers: '0'

Sep 11, 2015 4:10:43 PM INFO hudson.slaves.NodeProvisioner$StandardStrategyImpl apply

Started provisioning Image of docker-registry.example.com/cryan/cucushift:latest from MTV Docker VM with 1 executors. Remaining excess workload: 0

Sep 11, 2015 4:10:44 PM INFO com.nirima.jenkins.plugins.docker.DockerCloud pullImage

Pulling image 'docker-registry.example.com/cryan/cucushift:latest' again. This may take awhile...

Sep 11, 2015 4:10:44 PM SEVERE com.github.dockerjava.core.async.ResultCallbackTemplate onError

Error during callback
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "stream" (class com.github.dockerjava.api.model.PullResponseItem), not marked as ignorable (6 known properties: , "status", "error", "errorDetail", "id", "progress", "progressDetail"])
 at [Source: com.github.dockerjava.jaxrs.util.WrappedResponseInputStream@476db9dd; line: 1, column: 12] (through reference chain: com.github.dockerjava.api.model.PullResponseItem["stream"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:79)
	at com.fasterxml.jackson.databind.DeserializationContext.reportUnknownProperty(DeserializationContext.java:579)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:672)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:906)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:328)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:121)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:2769)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:1478)
	at com.github.dockerjava.core.async.JsonStreamProcessor.processResponseStream(JsonStreamProcessor.java:44)
	at com.github.dockerjava.jaxrs.async.AbstractCallbackNotifier.call(AbstractCallbackNotifier.java:62)
	at com.github.dockerjava.jaxrs.async.AbstractCallbackNotifier.call(AbstractCallbackNotifier.java:22)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

Sep 11, 2015 4:10:44 PM SEVERE com.nirima.jenkins.plugins.docker.DockerCloud$1 call

Error in provisioning; template='DockerTemplate{configVersion=2, labelString='cucushift_v3 docker', launcher=com.nirima.jenkins.plugins.docker.launcher.DockerComputerSSHLauncher@6525604d, remoteFsMapping='', remoteFs='/home/robot/workspace', instanceCap=2147483647, mode=NORMAL, retentionStrategy=com.nirima.jenkins.plugins.docker.strategy.DockerOnceRetentionStrategy@dad0f97, numExecutors=1, dockerTemplateBase=DockerTemplateBase{image=docker-registry.example.com/cryan/cucushift:latest}, removeVolumes=false, pullStrategy=PULL_LATEST}' for cloud='MTV Docker VM'
com.github.dockerjava.api.DockerClientException: Could not pull image
	at com.github.dockerjava.core.command.PullImageResultCallback.awaitSuccess(PullImageResultCallback.java:44)
	at com.nirima.jenkins.plugins.docker.DockerCloud.pullImage(DockerCloud.java:336)
	at com.nirima.jenkins.plugins.docker.DockerCloud.provisionWithWait(DockerCloud.java:343)
	at com.nirima.jenkins.plugins.docker.DockerCloud.access$000(DockerCloud.java:58)
	at com.nirima.jenkins.plugins.docker.DockerCloud$1.call(DockerCloud.java:233)
	at com.nirima.jenkins.plugins.docker.DockerCloud$1.call(DockerCloud.java:230)
	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

Sep 11, 2015 4:10:53 PM WARNING hudson.slaves.NodeProvisioner$2 run

Provisioned slave Image of docker-registry.example.com/cryan/cucushift:latest failed to launch
com.github.dockerjava.api.DockerClientException: Could not pull image
	at com.github.dockerjava.core.command.PullImageResultCallback.awaitSuccess(PullImageResultCallback.java:44)
	at com.nirima.jenkins.plugins.docker.DockerCloud.pullImage(DockerCloud.java:336)
	at com.nirima.jenkins.plugins.docker.DockerCloud.provisionWithWait(DockerCloud.java:343)
	at com.nirima.jenkins.plugins.docker.DockerCloud.access$000(DockerCloud.java:58)
	at com.nirima.jenkins.plugins.docker.DockerCloud$1.call(DockerCloud.java:233)
	at com.nirima.jenkins.plugins.docker.DockerCloud$1.call(DockerCloud.java:230)
	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

Sep 11, 2015 4:10:53 PM INFO com.nirima.jenkins.plugins.docker.DockerCloud provision

Asked to provision 1 slave(s) for: docker&&cucushift_v3

Sep 11, 2015 4:10:53 PM INFO com.nirima.jenkins.plugins.docker.DockerCloud provision

Will provision 'docker-registry.example.com/cryan/cucushift:latest', for label: 'docker&&cucushift_v3', in cloud: 'MTV Docker VM'

Sep 11, 2015 4:10:53 PM INFO com.nirima.jenkins.plugins.docker.DockerCloud addProvisionedSlave

Provisioning 'docker-registry.example.com/cryan/cucushift:latest' number '0' on 'MTV Docker VM'; Total containers: '0'

Sep 11, 2015 4:10:53 PM INFO hudson.slaves.NodeProvisioner$StandardStrategyImpl apply

Started provisioning Image of docker-registry.example.com/cryan/cucushift:latest from MTV Docker VM with 1 executors. Remaining excess workload: 0

Sep 11, 2015 4:10:54 PM INFO com.nirima.jenkins.plugins.docker.DockerCloud pullImage

Pulling image 'docker-registry.example.com/cryan/cucushift:latest' again. This may take awhile...

Sep 11, 2015 4:10:54 PM SEVERE com.github.dockerjava.core.async.ResultCallbackTemplate onError

Error during callback
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "stream" (class com.github.dockerjava.api.model.PullResponseItem), not marked as ignorable (6 known properties: , "status", "error", "errorDetail", "id", "progress", "progressDetail"])
 at [Source: com.github.dockerjava.jaxrs.util.WrappedResponseInputStream@1f574a31; line: 1, column: 12] (through reference chain: com.github.dockerjava.api.model.PullResponseItem["stream"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:79)
	at com.fasterxml.jackson.databind.DeserializationContext.reportUnknownProperty(DeserializationContext.java:579)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:672)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:906)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:328)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:121)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:2769)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:1478)
	at com.github.dockerjava.core.async.JsonStreamProcessor.processResponseStream(JsonStreamProcessor.java:44)
	at com.github.dockerjava.jaxrs.async.AbstractCallbackNotifier.call(AbstractCallbackNotifier.java:62)
	at com.github.dockerjava.jaxrs.async.AbstractCallbackNotifier.call(AbstractCallbackNotifier.java:22)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

Sep 11, 2015 4:10:54 PM SEVERE com.nirima.jenkins.plugins.docker.DockerCloud$1 call

Error in provisioning; template='DockerTemplate{configVersion=2, labelString='cucushift_v3 docker', launcher=com.nirima.jenkins.plugins.docker.launcher.DockerComputerSSHLauncher@6525604d, remoteFsMapping='', remoteFs='/home/robot/workspace', instanceCap=2147483647, mode=NORMAL, retentionStrategy=com.nirima.jenkins.plugins.docker.strategy.DockerOnceRetentionStrategy@dad0f97, numExecutors=1, dockerTemplateBase=DockerTemplateBase{image=docker-registry.example.com/cryan/cucushift:latest}, removeVolumes=false, pullStrategy=PULL_LATEST}' for cloud='MTV Docker VM'
com.github.dockerjava.api.DockerClientException: Could not pull image
	at com.github.dockerjava.core.command.PullImageResultCallback.awaitSuccess(PullImageResultCallback.java:44)
	at com.nirima.jenkins.plugins.docker.DockerCloud.pullImage(DockerCloud.java:336)
	at com.nirima.jenkins.plugins.docker.DockerCloud.provisionWithWait(DockerCloud.java:343)
	at com.nirima.jenkins.plugins.docker.DockerCloud.access$000(DockerCloud.java:58)
	at com.nirima.jenkins.plugins.docker.DockerCloud$1.call(DockerCloud.java:233)
	at com.nirima.jenkins.plugins.docker.DockerCloud$1.call(DockerCloud.java:230)
	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by marcuslinke** [comment]
No problem.
