### ISSUE TITLE
Hang at java.net.SocketInputStream.socketRead0 for WaitContainerCmd

### ISSUE THREAD

**Issue by hex108** [docker-java/docker-java#346]
We are running `DockerClientService.DockerContainerWait` in a thread pool(Executors.newCachedThreadPool).  After calling shutdownNow() for thread pool, `DockerClientService.DockerContainerWait` just hangs, the stack trace is as following:

```
"ContainersLauncher #877" #19011 prio=5 os_prio=0 tid=0x0000000001cba800 nid=0x2a13 runnable [0x00007f1bd7c9b000]
   java.lang.Thread.State: RUNNABLE
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.read(SocketInputStream.java:150)
        at java.net.SocketInputStream.read(SocketInputStream.java:121)
        at org.apache.http.impl.io.AbstractSessionInputBuffer.fillBuffer(AbstractSessionInputBuffer.java:166)
        at org.apache.http.impl.io.SocketInputBuffer.fillBuffer(SocketInputBuffer.java:90)
        at org.apache.http.impl.io.AbstractSessionInputBuffer.readLine(AbstractSessionInputBuffer.java:281)
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:92)
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:62)
        at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:254)
        at org.apache.http.impl.AbstractHttpClientConnection.receiveResponseHeader(AbstractHttpClientConnection.java:289)
        at org.apache.http.impl.conn.DefaultClientConnection.receiveResponseHeader(DefaultClientConnection.java:252)
        at org.apache.http.impl.conn.ManagedClientConnectionImpl.receiveResponseHeader(ManagedClientConnectionImpl.java:191)
        at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:300)
        at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:127)
        at org.apache.http.impl.client.DefaultRequestDirector.tryExecute(DefaultRequestDirector.java:715)
        at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:520)
        at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:906)
        at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:827)
        at com.sun.jersey.client.apache4.ApacheHttpClient4Handler.handle(ApacheHttpClient4Handler.java:170)
        at com.github.dockerjava.client.utils.JsonClientFilter.handle(JsonClientFilter.java:17)
        at com.sun.jersey.api.client.filter.LoggingFilter.handle(LoggingFilter.java:183)
        at com.github.dockerjava.client.SelectiveLoggingFilter.handle(SelectiveLoggingFilter.java:44)
        at com.sun.jersey.api.client.Client.handle(Client.java:648)
        at com.sun.jersey.api.client.WebResource.handle(WebResource.java:670)
        at com.sun.jersey.api.client.WebResource.access$200(WebResource.java:74)
        at com.sun.jersey.api.client.WebResource$Builder.post(WebResource.java:553)
        at com.github.dockerjava.client.command.WaitContainerCmd.impl(WaitContainerCmd.java:48)
        at com.github.dockerjava.client.command.WaitContainerCmd.impl(WaitContainerCmd.java:18)
        at com.github.dockerjava.client.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:27)
        at org.apache.hadoop.yarn.server.nodemanager.DockerClientService.DockerContainerWait(DockerClientService.java:128)
        at org.apache.hadoop.yarn.server.nodemanager.DockerContainerExecutor.waitExitCode(DockerContainerExecutor.java:162)
       ...
```

It seems that  `java.net.SocketInputStream.socketRead0` does not response to `Thread.interrupt`. Is there any method to solve it?

**Comment by marcuslinke** [comment]
@hex108  Thanks for reporting. `SocketInputStream.socketRead()` blocks until the server response arrives but as  the container process probably doesn't finish it hangs.

As `SocketInputStream.socketRead()` doesn't react to  `Thread.interrupt()` the only way to interrupt the blocking would be to close the underlying connection. Sadly the current wait container API doesn't provide a hook to do so which seems to be a design glitch.

I think we have to change the API to be callback-driven like with log container or events command. This way you could call the `close()` method of the callback to close and abort the connection when the thread must be interrupted. Would this somehow provide a solution for your problem?

**Comment by hex108** [comment]
@marcuslinke Thanks for the explanation and suggestion. 

>I think we have to change the API to be callback-driven like with log container or events command. This way you could call the close() method of the callback to close and abort the connection when the thread must be interrupted. Would this somehow provide a solution for your problem?

If using this method, we need execute wait command in a new thread, then we could catch the `Thread.interrrupt()` in current thread and call `close()` method of the callback to callback. Am I right?

**Comment by marcuslinke** [comment]
@hex108 Yes, something like that. Or you could call `close()` at the callback before `shutdownNow()` the thread pool. Would it be feasible?

**Comment by hex108** [comment]
@marcuslinke thanks. It could work. Is it possible to implement it using non-blocking  HTTP-client(e.g. netty), likes [http://stackoverflow.com/questions/28785085/how-to-prevent-hangs-on-socketinputstream-socketread0-on-windows-in-java](http://stackoverflow.com/questions/28785085/how-to-prevent-hangs-on-socketinputstream-socketread0-on-windows-in-java)?  It seems more straightforward.

**Comment by marcuslinke** [comment]
Using netty instead of jersey (with underlying Apache HttpClient connector) would need a complete refactoring of docker-java. This is currently a bit out-of-scope although I've thought about it already for other reasons. Personally I've no netty knowledge and there are some challenges that must be solved like UNIX socket support and SSL...

However, the wait command is a potentially long running operation that must be cancable from the API perspective. So for the first I would suggest to adopt the wait container API to allow this cancellation regardless any threading issues.

Btw. could you shortly explain your use case and why you operate the wait command from a thread pool? I'm just curious...

**Comment by marcuslinke** [comment]
Closing this in favor of https://github.com/docker-java/docker-java/issues/348

**Comment by hex108** [comment]
Thanks a lot.

Our case: we are using it to support docker container in our version of [Hadoop YARN](http://hadoop.apache.org/). `NodeManager` in YARN uses `ContainersLauncher` which has a thread pool to launch containers. In the thread pool, tasks first run docker containers, then wait containers to finish.  If `NodeManager` need stop services, it will calls `shutdownNow` to shutdown the thread pool. However thread will not exit because it hangs at `DockerClientService.DockerContainerWait`. 

Our workaround is calling `setDaemon(true)` for the thread pool, and daemon threads will not prevent JVM from exiting.
