### ISSUE TITLE
 NullPointerException at statsCmd() when no container id specified 

### ISSUE THREAD

**Issue by doronl** [docker-java/docker-java#389]
Exception below thrown when calling: dockerClient.statsCmd().exec(statsCallback), debugging the code shows that calling withContainerId is mandatory for this method execution however nothing implies this until you fail at the lowest level...

IMO either:

1.	Don’t allow call exec directly from statsCmd.
2.	Add checkNotNull on the container id along the way.
3.	Support getting stats for all containers.

Thanks,
  Doron

java.lang.NullPointerException: value is 'null'.
	at jersey.repackaged.com.google.common.base.Preconditions.checkNotNull(Preconditions.java:208)
	at org.glassfish.jersey.client.JerseyWebTarget.resolveTemplate(JerseyWebTarget.java:244)
	at org.glassfish.jersey.client.JerseyWebTarget.resolveTemplate(JerseyWebTarget.java:237)
	at org.glassfish.jersey.client.JerseyWebTarget.resolveTemplate(JerseyWebTarget.java:59)
	at com.github.dockerjava.jaxrs.StatsCmdExec.callbackNotifier(StatsCmdExec.java:26)
	at com.github.dockerjava.jaxrs.StatsCmdExec.callbackNotifier(StatsCmdExec.java:15)
	at com.github.dockerjava.jaxrs.AbstrAsyncDockerCmdExec.execute(AbstrAsyncDockerCmdExec.java:57)
	at com.github.dockerjava.jaxrs.AbstrAsyncDockerCmdExec.exec(AbstrAsyncDockerCmdExec.java:22)
	at com.github.dockerjava.jaxrs.AbstrAsyncDockerCmdExec.exec(AbstrAsyncDockerCmdExec.java:13)
	at com.github.dockerjava.core.command.AbstrAsyncDockerCmd.exec(AbstrAsyncDockerCmd.java:23)

**Comment by marcuslinke** [comment]
@doronl Thanks for pointing this out. The container id has to be passed into the command constructor. I'll fix this.

**Comment by marcuslinke** [comment]
Fixed here 77b8559685906e68e1871084ee7bfbfba3e24b71
