### ISSUE TITLE
for docker 1.9?

### ISSUE THREAD

**Issue by wzhyh** [docker-java/docker-java#391]
I have a question in docker 1.9. Could you help to fix it?

java.lang.UnsupportedClassVersionError: com/github/dockerjava/api/DockerClient : Unsupported major.minor version 51.0 (unable to load class com.github.dockerjava.api.DockerClient)
	at org.apache.catalina.loader.WebappClassLoaderBase.findClassInternal(WebappClassLoaderBase.java:2993)
	at org.apache.catalina.loader.WebappClassLoaderBase.findClass(WebappClassLoaderBase.java:1223)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1706)
	at com.taobao.tomcat.container.context.loader.AliWebappClassLoaderBase.loadClass(AliWebappClassLoaderBase.java:115)
	n(ThreadPoolExecutor.java:603)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:679)

Thanks

**Comment by KostyaSha** [comment]
`Unsupported major.minor version 51.0 (unable to load class com.github.dockerjava.api.DockerClient)`
Please update your JVM http://stackoverflow.com/questions/10382929/how-to-fix-unsupported-major-minor-version-51-0-error

**Comment by wzhyh** [comment]
sorry, I have got it. I am stupid. ^_^
Thanks thanks
