### ISSUE TITLE
Exception thrown by library when using unix:/// docker endpoint

### ISSUE THREAD

**Issue by garthy** [docker-java/docker-java#401]
If you use 2.1.3 docker-java with a docker enpoint "unix:///var/run/docker.sock" then an exception is throw trying to resolve the proxy to use. It should skip proxy configuration if docker endpoint protocol is "unix://"

java.lang.IllegalArgumentException: protocol = unix host = null
        at sun.net.spi.DefaultProxySelector.select(Unknown Source) 
        at com.github.dockerjava.jaxrs.DockerCmdExecFactoryImpl.configureProxy(DockerCmdExecFactoryImpl.java:187)
        at com.github.dockerjava.jaxrs.DockerCmdExecFactoryImpl.init(DockerCmdExecFactoryImpl.java:145) 
        at com.github.dockerjava.core.DockerClientImpl.withDockerCmdExecFactory(DockerClientImpl.java:130) 
        at com.github.dockerjava.core.DockerClientBuilder.build(DockerClientBuilder.java:47)

**Comment by marcuslinke** [comment]
Duplicates #396
