### ISSUE TITLE
IllegalArgumentException when using Unix socket

### ISSUE THREAD

**Issue by patelrit** [docker-java/docker-java#405]
Recent change to DockerCmdExecFactoryImpl breaks Unix socket support.

java.lang.IllegalArgumentException: protocol = unix host = null
        at sun.net.spi.DefaultProxySelector.select(DefaultProxySelector.java:176) ~[na:1.8.0_66-internal]
        at com.github.dockerjava.jaxrs.DockerCmdExecFactoryImpl.configureProxy(DockerCmdExecFactoryImpl.java:187) ~[docker-java-2.1.3.jar:na]
        at com.github.dockerjava.jaxrs.DockerCmdExecFactoryImpl.init(DockerCmdExecFactoryImpl.java:145) ~[docker-java-2.1.3.jar:na]
        at com.github.dockerjava.core.DockerClientImpl.withDockerCmdExecFactory(DockerClientImpl.java:130) ~[docker-java-2.1.3.jar:na]
        at com.github.dockerjava.core.DockerClientBuilder.build(DockerClientBuilder.java:47) ~[docker-java-2.1.3.jar:na]

I believe the changes are:
https://github.com/docker-java/docker-java/commit/83c0407b22b50618e09101cc0282b0fc0362c878
@marcuslinke

**Comment by marcuslinke** [comment]
@patelrit This is fixed already. See https://github.com/docker-java/docker-java/pull/403
