### ISSUE TITLE
https protocol is not supported?

### ISSUE THREAD

**Issue by francisdb** [docker-java/docker-java#419]
If you forget to set up the `DOCKER_HOST` you get this error. This should probably fail with a more appropriate error.

And `DOCKER_HOST` should probably default to `unix:///var/run/docker.sock` ?

```
javax.ws.rs.ProcessingException: org.apache.http.conn.UnsupportedSchemeException: https protocol is not supported
	at com.github.dockerjava.jaxrs.connector.ApacheConnector.apply(ApacheConnector.java:490)
	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:246)
	at org.glassfish.jersey.client.JerseyInvocation$3.call(JerseyInvocation.java:705)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:424)
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:701)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:417)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.get(JerseyInvocation.java:313)
	at com.github.dockerjava.jaxrs.ListImagesCmdExec.execute(ListImagesCmdExec.java:35)
	at com.github.dockerjava.jaxrs.ListImagesCmdExec.execute(ListImagesCmdExec.java:17)
	at com.github.dockerjava.jaxrs.AbstrDockerCmdExec.exec(AbstrDockerCmdExec.java:53)
	at com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:29)
	at com.whisk.docker.DockerKit$$anonfun$listImages$1.apply(DockerKit.scala:25)
	at com.whisk.docker.DockerKit$$anonfun$listImages$1.apply(DockerKit.scala:25)
Caused by: org.apache.http.conn.UnsupportedSchemeException: https protocol is not supported
	at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:99)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:314)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:357)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:218)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:194)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:85)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:186)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
	at com.github.dockerjava.jaxrs.connector.ApacheConnector.apply(ApacheConnector.java:443)
	... 15 more
```

**Comment by marcuslinke** [comment]
@francisdb I guess this is related to https://github.com/docker-java/docker-java/issues/331. Currently it is possible to configure docker-java inconsinstently. Docker CLI prevents this situation by allowing only `tcp://` urls in DOCKER_HOST and switch between secure and unsecure via `TLS_VERIFY`. In contract to this if `TLS_VERIFY` or `DOCKER_CERT_PATH` is set then docker-java assumes a secure connection is needed but you have to pass a `https` url in `DOCKER_HOST` then also. What I mean is that these settings currently must be consistent, otherwise you will get some distracting expection like you got. Hope this helps.

**Comment by francisdb** [comment]
Well, let's be clear, inconsistent config/setup should not fail with `UnsupportedSchemeException: https protocol is not supported` from apache http client as this is totally unrelated and misleading.

**Comment by marcuslinke** [comment]
@francisdb You are absolutely right. Feel free to provide a PR that solves #331 ;-)

**Comment by marcuslinke** [comment]
@francisdb Fixed via #447

**Comment by francisdb** [comment]
@marcuslinke I guess this is only for 3.x?

**Comment by marcuslinke** [comment]
Yes. Version 3.0.0-RC1 already contains it. Please note the configuration changes (see README.md).

**Comment by francisdb** [comment]
@marcuslinke I can confirm I don't get the 'https protocol is not supported' any more. Thanks.
