### ISSUE TITLE
Read Timed out for Events

### ISSUE THREAD

**Issue by triggetry** [docker-java/docker-java#482]
I am trying to build some kind of "Docker Event Monitor". So, I want to track docker events for over an unlimeted amount of time.

I am starting the docker event command using  `dockerClient.eventsCmd().exec( this.callback )`.
It works fine as long there are frequent docker events every couple of seconds.

However, when there was no docker event for a longer time (about half a minute) I am getting a Read Timeout and the callback is shutting down with `onComplete()`. Also, trying to close the callback / stream using `this.callback.close()` blocks for a certain time until a read time out occurs.

**Comment by marcuslinke** [comment]
I guess you use the default JAX-RS based implementation of `DockerCmdExecFactory` so you could try to adjust the readTimeout as described here: https://github.com/docker-java/docker-java/wiki#intialize-docker-client-advanced

**Comment by KostyaSha** [comment]
read timeout would happen if you set too small timeout in connection. 
@marcuslinke provided link to the docs.

**Comment by triggetry** [comment]
@marcuslinke @KostyaSha Ok, thanks for the fast reply. Actually,in my use case I never want the connection to time out, because I will never know **when** the next docker event will occur.
Is this possible?

**Comment by KostyaSha** [comment]
As docs states, set it to `0`.

**Comment by KostyaSha** [comment]
Or you can navigate to chain of classes because this settings configures `ApacheConnector`
@marcuslinke `-1` or `0` ?

**Comment by triggetry** [comment]
Ok, tried it with `readTimeOut` and `connectionTimeout` of  `-1` as well as `0`, but still I am getting a `"read timed out"` after some time when no event occured.

**Comment by KostyaSha** [comment]
@triggetry could you provide stack traces?

**Comment by triggetry** [comment]
@KostyaSha sure:


`Read timed out
java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:170)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at sun.net.www.http.ChunkedInputStream.readAheadBlocking(ChunkedInputStream.java:552)
	at sun.net.www.http.ChunkedInputStream.readAhead(ChunkedInputStream.java:609)
	at sun.net.www.http.ChunkedInputStream.read(ChunkedInputStream.java:696)
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3335)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
LKJLKJ
	at com.github.dockerjava.jaxrs.util.WrappedResponseInputStream.read(WrappedResponseInputStream.java:44)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.loadMore(UTF8StreamJsonParser.java:180)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._skipWSOrEnd2(UTF8StreamJsonParser.java:2904)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._skipWSOrEnd(UTF8StreamJsonParser.java:2899)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:692)
	at com.github.dockerjava.core.async.JsonStreamProcessor.processResponseStream(JsonStreamProcessor.java:51)
	at com.github.dockerjava.jaxrs.async.AbstractCallbackNotifier.call(AbstractCallbackNotifier.java:62)
	at com.github.dockerjava.jaxrs.async.AbstractCallbackNotifier.call(AbstractCallbackNotifier.java:22)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
`

Btw, setting the timeouts seems to have no effect at all, I tried it with different values, but the behavior is always the same.

**Comment by marcuslinke** [comment]
Maybe you could also try it with netty impl of `DockerCmdExecFactory` as there is no timeout I 'm currently aware of.

**Comment by KostyaSha** [comment]
`org.glassfish.jersey.client.ClientProperties` ?

**Comment by triggetry** [comment]
@marcuslinke Thanx, it's working with the netty implementation of `DockerCmdExecFactory`.

**Comment by KostyaSha** [comment]
@triggetry do you have any `@Test` example of your issue?
