### ISSUE TITLE
test failure: executable flag preserved

### ISSUE THREAD

**Issue by llamahunter** [docker-java/docker-java#505]
I'm getting a single test failure when running the top of trunk build. It seems like this should be an unlikely test to fail, but it is, repeatedly.

```
Tests run: 213, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 3.565 sec <<< FAILURE! - in TestSuite
testExecutableFlagIsPreserved(com.github.dockerjava.core.CompressArchiveUtilTest)  Time elapsed: 0.011 sec  <<< FAILURE!
java.lang.AssertionError: 

Expected: is <true>
     but: was <false>
	at com.github.dockerjava.core.CompressArchiveUtilTest.createExecutableFile(CompressArchiveUtilTest.java:39)
	at com.github.dockerjava.core.CompressArchiveUtilTest.testExecutableFlagIsPreserved(CompressArchiveUtilTest.java:26)


Results :

Failed tests: 
  CompressArchiveUtilTest.testExecutableFlagIsPreserved:26->createExecutableFile:39 
Expected: is <true>
     but: was <false>

Tests run: 213, Failures: 1, Errors: 0, Skipped: 0
```

**Comment by KostyaSha** [comment]
Please show your `docker version` `docker info`

**Comment by KostyaSha** [comment]
Works fine for me on docker-1.10.2

**Comment by KostyaSha** [comment]
no replies, closing
