### ISSUE TITLE
Creating network throws exception

### ISSUE THREAD

**Issue by igorspasic** [docker-java/docker-java#514]
Creating overlay network with a name failed:

```java
		CreateNetworkResponse createNetworkResponse =
			dockerClient.createNetworkCmd()
				.withName(networkName)
				.withDriver(driver)
				.exec();

```
Exception:

```
115628 ERROR [2016-03-21 22:12:35,583 worker-1] c.l.l.c.n.a.d.DockerNewNetwork#error:41 - Creating network failed
com.github.dockerjava.api.exception.InternalServerErrorException: pool configuration failed because of Unexpected response code: 413 (Value exceeds 524288 byte limit)

	at com.github.dockerjava.jaxrs.filter.ResponseStatusExceptionFilter.filter(ResponseStatusExceptionFilter.java:53) ~[docker-java-3.0.0-RC3.jar:na]
	at org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply(ClientFilteringStages.java:134) ~[jersey-client-2.11.jar:na]
	at org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply(ClientFilteringStages.java:123) ~[jersey-client-2.11.jar:na]
	at org.glassfish.jersey.process.internal.Stages.process(Stages.java:171) ~[jersey-common-2.11.jar:na]
	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:251) ~[jersey-client-2.11.jar:na]
	at org.glassfish.jersey.client.JerseyInvocation$2.call(JerseyInvocation.java:683) ~[jersey-client-2.11.jar:na]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315) ~[jersey-common-2.11.jar:na]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297) ~[jersey-common-2.11.jar:na]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:228) ~[jersey-common-2.11.jar:na]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:424) ~[jersey-common-2.11.jar:na]
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:679) ~[jersey-client-2.11.jar:na]
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:435) ~[jersey-client-2.11.jar:na]
	at org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:338) ~[jersey-client-2.11.jar:na]
	at com.github.dockerjava.jaxrs.CreateNetworkCmdExec.execute(CreateNetworkCmdExec.java:28) ~[docker-java-3.0.0-RC3.jar:na]
	at com.github.dockerjava.jaxrs.CreateNetworkCmdExec.execute(CreateNetworkCmdExec.java:14) ~[docker-java-3.0.0-RC3.jar:na]
	at com.github.dockerjava.jaxrs.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:23) ~[docker-java-3.0.0-RC3.jar:na]
	at com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:35) ~[docker-java-3.0.0-RC3.jar:na]
....
```

**Comment by igorspasic** [comment]
ok, this is related to docker issue:

```
Error response from daemon: failed to parse pool request for address space "GlobalDefault" pool "" subpool "": cannot find address space GlobalDefault (most likely the backing datastore is not configured)
```

**Comment by marcuslinke** [comment]
OK. So closing this as its not a docker-java issue.
