### ISSUE TITLE
Large volumes of output from "docker exec" trigger out of memory error

### ISSUE THREAD

**Issue by davidtnorth** [docker-java/docker-java#531]
I ran a command via the API call for docker exec. It produced several GB of output on stderr. This resulted in the following:
```
java.lang.OutOfMemoryError: Requested array size exceeds VM limit
        at io.netty.buffer.UnpooledHeapByteBuf.capacity(UnpooledHeapByteBuf.java:115)
        at io.netty.buffer.AbstractByteBuf.ensureWritable0(AbstractByteBuf.java:270)
        at io.netty.buffer.AbstractByteBuf.ensureWritable(AbstractByteBuf.java:251)
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1023)
        at com.github.dockerjava.netty.handler.FramedResponseStreamHandler.channelRead0(FramedResponseStreamHandler.java:48)
        at com.github.dockerjava.netty.handler.FramedResponseStreamHandler.channelRead0(FramedResponseStreamHandler.java:23)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
        at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
        at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:154)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:354)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:145)
        at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:233)
        at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
        at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:154)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:354)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:145)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:1078)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:125)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:510)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:467)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:381)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:353)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by KostyaSha** [comment]
test examples...

**Comment by marcuslinke** [comment]
Probably a `rawBuffer.discardReadBytes();` is missing after https://github.com/docker-java/docker-java/blob/master/src/main/java/com/github/dockerjava/netty/handler/FramedResponseStreamHandler.java#L64

**Comment by KostyaSha** [comment]
That what i also thought.

**Comment by davidtnorth** [comment]
I'll try and come up with a minimal reproduction; shouldn't be hard to do something involving "cat" and /dev/zero

**Comment by marcuslinke** [comment]
@davidtnorth Could you build docker-java from branch `issue-531` and test if the fix solves the issue for you please?

**Comment by marcuslinke** [comment]
@davidtnorth Could you test with latest 3.0.0-SNAPSHOT please?

**Comment by KostyaSha** [comment]
@marcuslinke do we push master to snapshots?

**Comment by marcuslinke** [comment]
@KostyaSha I think so. We call https://github.com/docker-java/docker-java/blob/master/travis-after-success.sh after travis successfully built the project. There is a `mvn deploy` called.

**Comment by marcuslinke** [comment]
Confirmed: See https://travis-ci.org/docker-java/docker-java/builds/121777177#L2610
