### ISSUE TITLE
Run container with image from private registry version 2 gives connection refused

### ISSUE THREAD

**Issue by smattheis** [docker-java/docker-java#573]
I'm trying to run a container (within Docker Swarm) from a private insecure registry (version 2) that I  configuring in the application as follows:

``` java
DockerClientConfig config =
                DockerClientConfig.createDefaultConfigBuilder()
    .withDockerHost("tcp://192.168.99.101:3376")
    .withDockerTlsVerify(true).withDockerCertPath("/path/to/certs").withApiVersion("1.21")
    .withRegistryUrl("http://192.168.99.100:5000/v2/").build();
DockerClient docker = DockerClientBuilder.getInstance(config).build();

CreateContainerResponse container =
    docker.createContainerCmd("myimage").withName("mycontainer").withTty(true)
        .withNetworkMode("myoverlay")
        .withCmd("/bin/bash").exec();

docker.startContainerCmd(container.getId()).exec();
```

The error message is as follows:

```
Exception in thread "main" com.github.dockerjava.api.exception.InternalServerErrorException: Error response from daemon: Get https://192.168.99.100/v1/_ping: dial tcp 192.168.99.100:443: getsockopt: connection refused

	at com.github.dockerjava.jaxrs.filter.ResponseStatusExceptionFilter.filter(ResponseStatusExceptionFilter.java:53)
	at org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply(ClientFilteringStages.java:134)
	at org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply(ClientFilteringStages.java:123)
	at org.glassfish.jersey.process.internal.Stages.process(Stages.java:171)
	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:251)
	at org.glassfish.jersey.client.JerseyInvocation$2.call(JerseyInvocation.java:683)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:424)
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:679)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:435)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:338)
	at com.github.dockerjava.jaxrs.CreateContainerCmdExec.execute(CreateContainerCmdExec.java:33)
	at com.github.dockerjava.jaxrs.CreateContainerCmdExec.execute(CreateContainerCmdExec.java:15)
	at com.github.dockerjava.jaxrs.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:23)
	at com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:35)
	at com.github.dockerjava.core.command.CreateContainerCmdImpl.exec(CreateContainerCmdImpl.java:130)
	at com.bmwcarit.footstep.DockerDriver.spawn(DockerDriver.java:66)
	at com.bmwcarit.footstep.Host.spawn(Host.java:362)
	at com.bmwcarit.footstep.SeqNode.spawn(SeqNode.java:84)
	at com.bmwcarit.footstep.SeqNode.initialize(SeqNode.java:54)
	at com.bmwcarit.footstep.Host.<init>(Host.java:266)
	at com.bmwcarit.footstep.Host.<init>(Host.java:229)
	at com.bmwcarit.footstep.DockerDriver.spawn(DockerDriver.java:40)
	at com.bmwcarit.footstep.ProcessDriver.main(ProcessDriver.java:95)
```

However, it seems that docker-java tries to connect to https://192.168.99.100/v1/ ... In particular, it seems to take the IP address of the registry but not Non-HTTPS, nor the port 5000 and also not version 2. Is there something wrong in the usage? Is this supported by docker-java?

Note: I successfully tested the command manually (by installing docker-engine inside a Docker Swarm container) where environment variables are set respectively:

``` bash
export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://192.168.99.101:3376"
export DOCKER_CERT_PATH="/path/to/certs"
docker run --name mycontainer --net myoverlay -it 192.168.99.100:5000/myimage /bin/bash
```

Is the translation of the run command into docker-java wrong?

**Comment by marcuslinke** [comment]
Could you try the following please?

```
DockerClientConfig config =
                DockerClientConfig.createDefaultConfigBuilder()
    .withDockerHost("tcp://192.168.99.101:3376")
    .withDockerTlsVerify(true).withDockerCertPath("/path/to/certs").withApiVersion("1.21")
    .build();
DockerClient docker = DockerClientBuilder.getInstance(config).build();

CreateContainerResponse container =
    docker.createContainerCmd("192.168.99.100:5000/myimage").withName("mycontainer").withTty(true)
        .withNetworkMode("myoverlay")
        .withCmd("/bin/bash").exec();

docker.startContainerCmd(container.getId()).exec();
```

**Comment by smattheis** [comment]
Thanks, it's working perfectly. Actually, I had another issue with buffered images in Docker Swarm so the true exception for the shown code is not "connection refused" but something like "cannot find library/myimage".
Using `docker.createContainerCmd("192.168.99.100:5000/myimage")`it's then working in the end. Thanks!
P.S. I could imagine that configuring the use of a private registry with `.withRegistryUrl("http://192.168.99.100:5000/v2/")` is nice to have for convenience, but please take it just as an idea because actually everything works fine as it is. :)
