### ISSUE TITLE
Keep getting Connection refused build failure

### ISSUE THREAD

**Issue by galyona** [docker-java/docker-java#587]
I'm trying to install on **Windows** 7. Are there any Windows-specific installation instructions?

I keep getting the following failure (copied from TestSuite.txt):

Tests run: 1053, Failures: 1, Errors: 0, Skipped: 1049, Time elapsed: 6.585 sec <<< FAILURE! - in TestSuite
beforeTest(com.github.dockerjava.client.DockerClientTest)  Time elapsed: 3.89 sec  <<< FAILURE!
javax.ws.rs.ProcessingException: org.apache.http.conn.HttpHostConnectException: Connect to localhost:2376 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused: connect
    at com.github.dockerjava.client.DockerClientTest.beforeTest(DockerClientTest.java:32)
Caused by: org.apache.http.conn.HttpHostConnectException: Connect to localhost:2376 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused: connect
    at com.github.dockerjava.client.DockerClientTest.beforeTest(DockerClientTest.java:32)
Caused by: java.net.ConnectException: Connection refused: connect
    at com.github.dockerjava.client.DockerClientTest.beforeTest(DockerClientTest.java:32)

I've tried:
- SET DOCKER_HOST=tcp://localhost:2376
-  opening TCP on port 2376 using:
  netsh advfirewall firewall add rule name="Docker daemon " dir=in action=allow protocol=TCP localport=2376
- setting DOCKER_TLS_VERIFY to 0

Does anyone have any suggestions? Perhaps I didn't fully understand the installation instructions.

Tnx,

**Comment by marcuslinke** [comment]
Port 2376 is usually used for TLS/SSL/https connection, so you have to provide certs via DOCKER_CERT_PATH variable and switch DOCKER_TLS_VERIFY to 1.

**Comment by KostyaSha** [comment]
@galoosh is it still actual?
