### ISSUE TITLE
inspectContainerCmd blocks until eventsCmd finished

### ISSUE THREAD

**Issue by elw00d** [docker-java/docker-java#602]
I use `3.0.0` with default settings:

```java

Lock lock = new ReentrantLock();
Condition cond = lock.newCondition();

String containerId = createContainerResponse.getId();

docker.eventsCmd()
                .withContainerFilter(createContainerResponse.getId())
                .exec(new EventsResultCallback() {
                    @Override
                    public void onNext(Event item) {
                        logger.info(String.format("Event from container [%s]: '%s'.", containerId, item));
                        if ("die".equals(item.getStatus())) {
                            try {
                                lock.lock();
                                cond.signal();
                            } finally {
                                lock.unlock();
                            }
                        }
                        super.onNext(item);
                    }
                });

docker.startContainerCmd(containerId).exec();

try {
            lock.lock();
            final int TIMEOUT_SECONDS = 5;
            if (!cond.await(TIMEOUT_SECONDS, TimeUnit.SECONDS)) {
                // !!! This method doesnt return immediately, it waits the container to be died, and subsequently
                // there is not possible to kill container
                InspectContainerResponse inspectContainerResponse = docker.inspectContainerCmd(containerId).exec();
                String status = inspectContainerResponse.getState().getStatus();
                //
                if ("exited".equals(status) || "dead".equals(status)) {
                    if (inspectContainerResponse.getState().getOOMKilled()) {
                        logger.error(String.format("Container [%s] in '%s' state after OutOfMemory. Nothing to do.", containerId, status));
                    } else {
                        logger.warn(String.format("Container [%s] in '%s' state, nothing to do.", containerId, status));
                    }
                } else {
                    logger.error(String.format("Container [%s] in '%s' state after %d seconds, killing it..", containerId, status, TIMEOUT_SECONDS));
                    docker.killContainerCmd(containerId).exec();
                    logger.error(String.format("Container [%s] killed.", containerId));
                }
            }
        } catch (InterruptedException e) {
            logger.error("Thread interrupted", e);
            Thread.currentThread().interrupt();
        } finally {
            lock.unlock();
        }
```

This is reproduced not always. I will update this issue if will found more precise way to reproduce.

**Comment by KostyaSha** [comment]
Run what you expect in separate thread?

**Comment by elw00d** [comment]
No, it doesnt work, I tried this already.. I've found some workaround:

```java
DockerClientConfig config = DockerClientConfig.createDefaultConfigBuilder()
                .withDockerHost("unix:///var/run/docker.sock")
                .build();
        DockerClient docker = DockerClientBuilder.getInstance(config)
                .build();
        DockerCmdExecFactoryImpl dockerCmdExecFactory = new DockerCmdExecFactoryImpl();
        dockerCmdExecFactory.withMaxTotalConnections(10);
        dockerCmdExecFactory.withMaxPerRouteConnections(10);
        ((DockerClientImpl) docker).withDockerCmdExecFactory(dockerCmdExecFactory);
```

Seems it by default allows only 2 connections. I have two executed tasks: EventsCmd and LogsCmd running. And when I try to start third task, it waits for available connection.

Unfortunately, there is no way to configure these parameters without casting to `DockerClientImpl`. Hope you add this feature :)

**Comment by KostyaSha** [comment]
Is it netty?
You shouldn't cast, just pass your custom dockerCmdExecFactory to Builder

**Comment by elw00d** [comment]
Ow, thanks, I missed this. Now it looks like

```java
DockerClientConfig config = DockerClientConfig.createDefaultConfigBuilder()
                .withDockerHost("unix:///var/run/docker.sock")
                .build();
        DockerCmdExecFactoryImpl dockerCmdExecFactory = new DockerCmdExecFactoryImpl();
        dockerCmdExecFactory.withMaxTotalConnections(10);
        dockerCmdExecFactory.withMaxPerRouteConnections(10);
        DockerClient docker = DockerClientBuilder.getInstance(config)
                .withDockerCmdExecFactory(dockerCmdExecFactory)
                .build();
```

It's jersey, netty doesnt work at all in 3.0.0 for me :)

**Comment by KostyaSha** [comment]
What wrong with netty?

**Comment by KostyaSha** [comment]
> Now it looks like

Yes, that it was supposed to be. If you don't like default, then pass your own options.

**Comment by elw00d** [comment]
Thanks !

In netty I have next trace:

```
io.netty.handler.codec.TooLongFrameException: object length exceeds 1048576: 1049445 bytes discarded
	at io.netty.handler.codec.json.JsonObjectDecoder.decode(JsonObjectDecoder.java:99)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:387)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:245)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:154)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:354)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:145)
	at com.github.dockerjava.netty.handler.HttpResponseHandler.channelRead0(HttpResponseHandler.java:72)
	at com.github.dockerjava.netty.handler.HttpResponseHandler.channelRead0(HttpResponseHandler.java:33)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:154)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:354)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:145)
	at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:233)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:154)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:354)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:145)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:433)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:277)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:264)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:243)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:154)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:354)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:145)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:1078)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:875)
	at io.netty.channel.epoll.EpollDomainSocketChannel$EpollDomainUnsafe.epollInReady(EpollDomainSocketChannel.java:141)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:347)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:263)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
Exception in thread "main" io.netty.handler.codec.TooLongFrameException: object length exceeds 1048576: 1049445 bytes discarded
	at io.netty.handler.codec.json.JsonObjectDecoder.decode(JsonObjectDecoder.java:99)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:387)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:245)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:154)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:354)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:145)
	at com.github.dockerjava.netty.handler.HttpResponseHandler.channelRead0(HttpResponseHandler.java:72)
	at com.github.dockerjava.netty.handler.HttpResponseHandler.channelRead0(HttpResponseHandler.java:33)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:154)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:354)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:145)
	at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:233)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:154)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:354)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:145)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:433)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:277)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:264)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:243)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:154)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:354)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:145)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:1078)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:875)
	at io.netty.channel.epoll.EpollDomainSocketChannel$EpollDomainUnsafe.epollInReady(EpollDomainSocketChannel.java:141)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:347)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:263)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
```

after listContainerCmd:

```java
Info info = docker.infoCmd().exec();
List<Container> containers = docker.listContainersCmd().withShowAll(true).exec();
```

infoCmd works.

**Comment by marcuslinke** [comment]
Seems this is a bug in netty impl. We probable have to use different constructor for `JsonObjectDecoder` there. See https://github.com/netty/netty/blob/4.1/codec/src/main/java/io/netty/handler/codec/json/JsonObjectDecoder.java#L68

**Comment by KostyaSha** [comment]
@elw00d please create issue per issue :)

**Comment by KostyaSha** [comment]
@elw00d could you PR your code as Test method?
