### ISSUE TITLE
Jersey's connectTimeout, readTimeout causes strange errors

### ISSUE THREAD

**Issue by elw00d** [docker-java/docker-java#604]
If I specify timeouts

```java
DockerClientConfig config = DockerClientConfig.createDefaultConfigBuilder()
                .withDockerHost("unix:///var/run/docker.sock")
                .build();
        DockerCmdExecFactoryImpl dockerCmdExecFactory = new DockerCmdExecFactoryImpl()
                .withConnectTimeout(1000)
                .withReadTimeout(1000)
                .withMaxPerRouteConnections(20)
                .withMaxTotalConnections(20);
        DockerClient docker = DockerClientBuilder.getInstance(config)
                .withDockerCmdExecFactory(dockerCmdExecFactory)
                .build();
```

there are some errors later

```
java.io.IOException: Resource temporarily unavailable at Socket[addr=0.0.0.0/0.0.0.0,port=0,localport=0][fd=java.io.FileDescriptor@1a26e5a5; file=/run/docker.sock; connected=true; bound=false]
	at org.newsclub.net.unix.AFUNIXSocketImpl$AFUNIXInputStream.read(AFUNIXSocketImpl.java:190)
	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:136)
	at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:152)
	at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:270)
	at org.apache.http.impl.io.ChunkedInputStream.getChunkSize(ChunkedInputStream.java:240)
	at org.apache.http.impl.io.ChunkedInputStream.nextChunk(ChunkedInputStream.java:206)
	at org.apache.http.impl.io.ChunkedInputStream.read(ChunkedInputStream.java:169)
	at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:137)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at org.glassfish.jersey.message.internal.EntityInputStream.read(EntityInputStream.java:101)
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream.read(ReaderInterceptorExecutor.java:300)
	at com.github.dockerjava.jaxrs.util.WrappedResponseInputStream.read(WrappedResponseInputStream.java:44)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.loadMore(UTF8StreamJsonParser.java:207)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._skipWSOrEnd2(UTF8StreamJsonParser.java:2919)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._skipWSOrEnd(UTF8StreamJsonParser.java:2914)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:707)
	at com.github.dockerjava.core.async.JsonStreamProcessor.processResponseStream(JsonStreamProcessor.java:56)
	at com.github.dockerjava.jaxrs.async.AbstractCallbackNotifier.call(AbstractCallbackNotifier.java:67)
	at com.github.dockerjava.jaxrs.async.AbstractCallbackNotifier.call(AbstractCallbackNotifier.java:24)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.newsclub.net.unix.AFUNIXSocketException: Resource temporarily unavailable
	at org.newsclub.net.unix.NativeUnixSocket.read(Native Method)
	at org.newsclub.net.unix.AFUNIXSocketImpl$AFUNIXInputStream.read(AFUNIXSocketImpl.java:187)
	... 25 more
```

If remove timeouts, all works fine.

**Comment by KostyaSha** [comment]
Don't use  `.withReadTimeout(1000)` read would mean that jersey will close connection for execCmd that would have "sleep 1000" in bash. Because no more new data would be incoming.

**Comment by elw00d** [comment]
Hmm, ok, thanks for information. Will use connectTimeout only

**Comment by marcuslinke** [comment]
@elw00d So this issue can be closed now?
