### ISSUE TITLE
Kill paused container cause InternalServerErrorException

### ISSUE THREAD

**Issue by tjlee** [docker-java/docker-java#644]
Is it expected behavior? Or docker-java should return another exception?

**Comment by KostyaSha** [comment]
examples? logs?

**Comment by tjlee** [comment]
Example test code:
```
public void killPausedContainer() {
        CreateContainerResponse container = dockerClient.createContainerCmd(BUSYBOX_IMAGE).withCmd("sleep", "9999").exec();
        LOG.info("Created container: {}", container.toString());
        assertThat(container.getId(), not(isEmptyString()));
        dockerClient.startContainerCmd(container.getId()).exec();

        InspectContainerResponse inspectContainerResponse = dockerClient.inspectContainerCmd(container.getId()).exec();
        assertThat(inspectContainerResponse.getState().getRunning(), is(true));

        dockerClient.pauseContainerCmd(container.getId()).exec();

        InspectContainerResponse inspectContainerResponse1 = dockerClient.inspectContainerCmd(container.getId()).exec();
        assertThat(inspectContainerResponse1.getState().getPaused(), is(true));

        dockerClient.killContainerCmd(container.getId()).exec();
    }
```
Log:
```
13:39:01.652 DEBUG c.g.d.j.JerseyDockerCmdExecFactory$1 - Connection released: [id: 4][route: {}->http://172.16.1.121:2375][total kept alive: 0; route allocated: 0 of 2; total allocated: 0 of 20]
com.github.dockerjava.api.exception.InternalServerErrorException: Cannot kill container 9e8b84d0a33561582fb1c4b72aebf763e19640f1b8184013791e053df1ab5a41: Container 9e8b84d0a33561582fb1c4b72aebf763e19640f1b8184013791e053df1ab5a41 is paused. Unpause the container before stopping

	at com.github.dockerjava.jaxrs.filter.ResponseStatusExceptionFilter.filter(ResponseStatusExceptionFilter.java:53)
	at org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply(ClientFilteringStages.java:140)
	at org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply(ClientFilteringStages.java:128)
	at org.glassfish.jersey.process.internal.Stages.process(Stages.java:171)
	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:257)
	at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:684)
	at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:681)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:444)
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:681)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:437)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:343)
	at com.github.dockerjava.jaxrs.KillContainerCmdExec.execute(KillContainerCmdExec.java:31)
	at com.github.dockerjava.jaxrs.KillContainerCmdExec.execute(KillContainerCmdExec.java:12)
	at com.github.dockerjava.jaxrs.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:23)
	at com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:35)
	at com.github.dockerjava.core.command.KillContainerCmdImpl.exec(KillContainerCmdImpl.java:50)
	at com.github.dockerjava.core.command.KillContainerCmdImplTest.killPausedContainer(KillContainerCmdImplTest.java:104)
```

**Comment by marcuslinke** [comment]
This is the expected behavior as docker-java has no knowledge of the container state. It just transports the HTTP error code 500 from the docker remote API to the user.

**Comment by tjlee** [comment]
Thank you.
