### ISSUE TITLE
Pulling image with authentication fails with UnauthorizedException

### ISSUE THREAD

**Issue by benash** [docker-java/docker-java#691]
Thanks for the work on this project.

I haven't been able to pull an image from our internal registry. With the following setup:
```java
AuthConfig authConfig = new AuthConfig()
        .withUsername("developer")
        .withPassword("myPassword")
        .withEmail("ben@me.com")
        .withRegistryAddress("my-registry.com");
DefaultDockerClientConfig.Builder builder = DefaultDockerClientConfig.createDefaultConfigBuilder();
DockerClient dockerClient = DockerClientBuilder.getInstance(builder.build())
        .withDockerCmdExecFactory(dockerCmdExecFactory)
        .build();
```

This auth command succeeds, but the pull command fails:
```java
dockerClient.authCmd().withAuthConfig(authConfig).exec(); // WORKS

dockerClient.pullImageCmd("my-registry.com/cassandra") // FAILS
        .withTag("latest")
        .withAuthConfig(authConfig)
        .exec(new PullImageResultCallback()).awaitSuccess();
```
```
16:35:36.827 DEBUG c.g.d.j.JerseyDockerCmdExecFactory - 3 * Sending client request on thread dockerjava-jaxrs-async-0
3 > POST https://192.168.99.100:2376/images/create?fromImage=my-registry.com%2Fcassandra&tag=latest
3 > Accept: application/octet-stream
3 > Content-Type: application/json
3 > X-Registry-Auth: (removed)
16:35:36.830 DEBUG c.g.d.j.JerseyDockerCmdExecFactory$1 - Connection request: [route: {s}->https://192.168.99.100:2376][total kept alive: 0; route allocated: 0 of 2; total allocated: 0 of 20]
16:35:36.830 DEBUG c.g.d.j.JerseyDockerCmdExecFactory$1 - Connection leased: [id: 2][route: {s}->https://192.168.99.100:2376][total kept alive: 0; route allocated: 1 of 2; total allocated: 1 of 20]
16:35:36.830 DEBUG o.a.h.i.c.DefaultHttpClientConnectionOperator - Connecting to /192.168.99.100:2376
16:35:36.852 DEBUG o.a.h.i.c.DefaultHttpClientConnectionOperator - Connection established 192.168.99.1:57454<->192.168.99.100:2376
16:35:37.801 DEBUG o.a.h.i.c.DefaultManagedHttpClientConnection - http-outgoing-2: Shutdown connection
16:35:37.803 DEBUG o.a.h.i.c.DefaultManagedHttpClientConnection - http-outgoing-2: Close connection
16:35:37.803 DEBUG c.g.d.j.JerseyDockerCmdExecFactory$1 - Connection released: [id: 2][route: {s}->https://192.168.99.100:2376][total kept alive: 0; route allocated: 0 of 2; total allocated: 0 of 20]
16:35:37.806 ERROR c.g.d.c.async.ResultCallbackTemplate - Error during callback
com.github.dockerjava.api.exception.UnauthorizedException: {"message":"Get https://my-registry.com/v2/cassandra/manifests/latest: unauthorized: authentication required"}
	at com.github.dockerjava.jaxrs.filter.ResponseStatusExceptionFilter.filter(ResponseStatusExceptionFilter.java:45)
	at org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply(ClientFilteringStages.java:140)
	at org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply(ClientFilteringStages.java:128)
```

Whereas I can pull fine with the CLI:
```
» docker pull my-registry.com/cassandra
Using default tag: latest
latest: Pulling from cassandra
Digest: sha256:f95931d0efbde34e438c127f6a7494c589ea3a45cead9025d75bbc120bd47935
Status: Image is up to date for my-registry.com/cassandra:latest
```

I decoded the `X-Registry-Auth` header that was sent with the POST request and, that seems to look correct:
```json
{"username":"developer","password":"myPassword","email":"ben@me.com","serveraddress":"my-registry.com"}
```

How could I further troubleshoot this issue?

**Comment by KostyaSha** [comment]
Do you have any private registries in image chain? Then you must specify them all in AuthConfig.

**Comment by benash** [comment]
Thanks for the suggestion, but the only private registry is the one that I've already specified in `withRegistryAddress`. I also haven't been able get this working by curling to the either. I wish I could view the request that gets sent from the CLI to the daemon, since that must be different somehow.

In case it's helpful, here are the Docker daemon logs:
```
time="2016-09-08T19:01:11.194806546Z" level=debug msg="Calling GET /images/busybox/json"
time="2016-09-08T19:01:11.584847015Z" level=debug msg="Calling POST /images/create?fromImage=my-registry.com%2Fcassandra"
time="2016-09-08T19:01:11.752010434Z" level=debug msg="hostDir: /etc/docker/certs.d/my-registry.com"
time="2016-09-08T19:01:11.832701368Z" level=debug msg="hostDir: /etc/docker/certs.d/my-registry.com"
time="2016-09-08T19:01:11.832831590Z" level=debug msg="Trying to pull my-registry.com/cassandra from https://my-registry.com v2"
time="2016-09-08T19:01:12.501443269Z" level=error msg="Error trying v2 registry: Get https://my-registry.com/v2/cassandra/tags/list: unauthorized:
authentication required"
time="2016-09-08T19:01:12.501481133Z" level=error msg="Attempting next endpoint for pull after error: Get https://my-registry.com/v2/cassandra/tags
/list: unauthorized: authentication required"
time="2016-09-08T19:01:12.501494890Z" level=debug msg="Skipping v1 endpoint https://my-registry.com because v2 registry was detected"
time="2016-09-08T19:01:12.501511306Z" level=error msg="Handler for POST /images/create returned error: Get https://my-registry.com/v2/cassandra/tag
s/list: unauthorized: authentication required"
```

**Comment by benash** [comment]
To add a little more info, the image that I'm trying to pull has a few layers beneath it, all from the same private registry, then finally a layer at the bottom from a public registry. 

The registry URL does point at a load balancer that balances between three different registry instances. I'm not sure how I would add all three (or four) URLs to the authConfig.

**Comment by benash** [comment]
I tracked the issue down to what looks like a bug in the Docker daemon. When the (decoded) auth object looks like this, it works:
```json
// Works
{
"username":"developer",
"password":"mypass",
"serveraddress":"my-docker-registry.com"
}
```
But putting any params on the same line breaks it:
```json
// Fails
{ "username":"developer",
"password":"mypass",
"serveraddress":"my-docker-registry.com"
}
```
This example also works, probably because `email` and `auth` are not needed for a successful login:
```json
// Works
{
"username":"developer",
"password":"qW*2Y9_M>?kPK[3;",
"serveraddress":"docker-registry.hub.bitbrew.com",
"email":"me@gmail.com", "auth":""
}
```

**Comment by marcuslinke** [comment]
@benash What version of docker daemon do you use?

**Comment by benash** [comment]
```
Boot2Docker version 1.12.1, build HEAD : ef7d0b4 - Thu Aug 18 21:18:06 UTC 2016
Docker version 1.12.1, build 23cf638
```

**Comment by KostyaSha** [comment]
Oh, new release :)

**Comment by marcuslinke** [comment]
...with new bugs... :-)

**Comment by KostyaSha** [comment]
Retriggering https://github.com/docker-java/docker-java/pull/676 but without socket fixes difficult to check test results.

**Comment by marcuslinke** [comment]
Hmmm. Auth works for me here with latest docker-java SNAPSHOT and docker 1.12.1...

**Comment by benash** [comment]
@marcuslinke Are you using docker-machine like I am?

**Comment by marcuslinke** [comment]
No. I'm using ubuntu 16,04 with docker installed via https://docs.docker.com/engine/installation/linux/ubuntulinux/

**Comment by KostyaSha** [comment]
@marcuslinke merge socket fixes?

**Comment by KostyaSha** [comment]
https://travis-ci.org/docker-java/docker-java/builds/158802442 experimental and testing should install latest versions (even more than 1.12.1) so let's wait for results!

**Comment by benash** [comment]
Did all the tests pass? I was playing around with things more and have an easier-to-reproduce testcase:
```shell
# Works
AUTH=`echo -n "{ \"username\": \"$DOCKER_USERNAME\",
     \"password\": \"$DOCKER_PASSWORD\",
     \"serveraddress\": \"$DOCKER_REGISTRY\"
}" | perl -pe 's/\r\n|\n|\r/\r\n/g' | base64`; curl -X POST -H "X-Registry-Auth: $AUTH" -H "Cache-Control: no-cache" https://$DOCKER_HOST_IP:2376/images/create\?fromImage\=$DOCKER_REGISTRY%2Fcassandra\&tag\=latest --cert $DOCKER_CERT_PATH/cert.p12 --pass mypass --key $DOCKER_CERT_PATH/key.pem --cacert $DOCKER_CERT_PATH/ca.pem
```
```shell
{"status":"Pulling from cassandra","id":"latest"}
```
```shell
# Fails
AUTH=`echo -n "{\"username\": \"$DOCKER_USERNAME\",
     \"password\": \"$DOCKER_PASSWORD\",
     \"serveraddress\": \"$DOCKER_REGISTRY\"
}" | perl -pe 's/\r\n|\n|\r/\r\n/g' | base64`; curl -X POST -H "X-Registry-Auth: $AUTH" -H "Cache-Control: no-cache" https://$DOCKER_HOST_IP:2376/images/create\?fromImage\=$DOCKER_REGISTRY%2Fcassandra\&tag\=latest --cert $DOCKER_CERT_PATH/cert.p12 --pass mypass --key $DOCKER_CERT_PATH/key.pem --cacert $DOCKER_CERT_PATH/ca.pem
```
```shell
{"message":"Get https://docker-registry.hub.bitbrew.com/v2/cassandra/manifests/latest: unauthorized: authentication required"}
```

Note:
- The only difference between the two is the space after the opening `{` of the auth json. No space breaks it.
- I need to use DOS line endings to get anything to work at all.

**Comment by KostyaSha** [comment]
I don't remind anything specific from docker API, could you try fill issue to docker project?

**Comment by benash** [comment]
Yep, I'll file with Docker.

**Comment by benash** [comment]
Opened https://github.com/docker/docker/issues/26602

Thanks for the help.

**Comment by KostyaSha** [comment]
I think that not docker-java issue as it just JSON parser error.
