### ISSUE TITLE
Single argument form of links are not supported

### ISSUE THREAD

**Issue by gcbartlett** [docker-java/docker-java#718]
For supporting legacy container links, docker supports two forms for the `--link` argument: `--link <name or id>:alias` and `--link <name or id>` (see https://docs.docker.com/engine/userguide/networking/default_network/dockerlinks/#communication-across-links).

**docker-java**, however, only supports the first form.

Attempting to use the single argument form produces an `IllegalArgumentException`, e.g.:

```
java.lang.IllegalArgumentException: Error parsing Link 'jenkins_master_1'
    at com.github.kostyasha.yad_docker_java.com.github.dockerjava.api.model.Link.parse(Link.java:70)
    at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
    at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
    at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
    at com.github.kostyasha.yad.commons.DockerCreateContainer.fillContainerConfig(DockerCreateContainer.java:541)
    at com.github.kostyasha.yad.DockerCloud.runContainer(DockerCloud.java:151)
    at com.github.kostyasha.yad.DockerCloud.provisionWithWait(DockerCloud.java:197)
    at com.github.kostyasha.yad.DockerCloud.lambda$provision$0(DockerCloud.java:120)
    at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by KostyaSha** [comment]
https://github.com/docker-java/docker-java/blob/master/src/main/java/com/github/dockerjava/api/model/Link.java#L47-L72

**Comment by KostyaSha** [comment]
https://github.com/docker/docker/blob/9f0593990f6d8ac95a5dde312e0b7401b472cfb9/runconfig/opts/parse.go#L796-L816

**Comment by KostyaSha** [comment]
Also IllegalArgumentException must throw message.
