### ISSUE TITLE
LogStream throws EOFException if the stream contains less than 8 bytes

### ISSUE THREAD

**Issue by bayanr** [docker-java/docker-java#732]
When trying to read the output of a command launched through `DockerClient.execStart()`, an `EOFException` is thrown if the output of the command is less than 8 characters using `v6.0.0:shaded`

The following unit test demonstrates the problem.

``` java
@Test
public void readStdoutOfCommandWithOutputLessThan8Chars() throws DockerCertificateException, DockerException, InterruptedException, IOException {
  DockerClient client = createDockerClient();
  String simpleEcho = client.execCreate("container_id", new String[] { "echo" ,"Hello" }, DockerClient.ExecCreateParam.attachStdout(true), DockerClient.ExecCreateParam.attachStderr(true)).id();

  LogStream logStream = client.execStart(simpleEcho, DockerClient.ExecStartParameter.TTY);
  ByteArrayOutputStream stdOut = new ByteArrayOutputStream();
  ByteArrayOutputStream stdErr = new ByteArrayOutputStream();

  logStream.attach(stdOut, stdErr);
  System.out.println("======== OUTPUT =======");
  System.out.println(stdOut);
}
```

Produces the following trace:

```
java.lang.RuntimeException: java.io.EOFException

    at com.google.common.base.Throwables.propagate(Throwables.java:160)
    at com.spotify.docker.client.LogStream.computeNext(LogStream.java:61)
    at com.spotify.docker.client.LogStream.computeNext(LogStream.java:35)
    at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
    at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
    at com.spotify.docker.client.LogStream.attach(LogStream.java:142)
    at Test.readStdoutOfCommandWithOutputLessThan8Chars(Test.java:61)
    // JUnit noise omitted
Caused by: java.io.EOFException
    at com.spotify.docker.client.LogReader.nextMessage(LogReader.java:59)
    at com.spotify.docker.client.LogStream.computeNext(LogStream.java:59)
    ... 31 more
```

Whereas the following test

``` java
@Test
public void readStdoutOfCommandWithOutputMoreThan8Chars() throws DockerCertificateException, DockerException, InterruptedException, IOException {
  DockerClient client = createDockerClient();
  String simpleEcho = client.execCreate("container_id", new String[] { "echo" ,"HelloWorld" }, DockerClient.ExecCreateParam.attachStdout(true), DockerClient.ExecCreateParam.attachStderr(true)).id();

  LogStream logStream = client.execStart(simpleEcho, DockerClient.ExecStartParameter.TTY);
  ByteArrayOutputStream stdOut = new ByteArrayOutputStream();
  ByteArrayOutputStream stdErr = new ByteArrayOutputStream();

  logStream.attach(stdOut, stdErr);
  System.out.println("======== OUTPUT =======");
  System.out.println(stdOut);
}
```

Prints out the expected output:

```
//Misc logs
======== OUTPUT =======
HelloWorld
```

**Comment by marcuslinke** [comment]
This is an issue not related to docker-java but rather to spotify client.

**Comment by bayanr** [comment]
Yikes! sorry about that.
