### ISSUE TITLE
How can I search image in my private docker-registry v2?

### ISSUE THREAD

**Issue by liuccc1** [docker-java/docker-java#801]
I can pull and push images from my private docker-registry v2 successful.But cannot search image use  dockerClient.searchImagesCmd("busybox").
code:
DockerClientConfig config = DefaultDockerClientConfig.createDefaultConfigBuilder()
                .withDockerHost("tcp://10.183.21.81:2375")
                .withApiVersion("1.22")
                .withRegistryUrl("https://10.183.21.81:5000/v2/")
                .withRegistryUsername("docker")
                .withRegistryPassword("docker")
                .withRegistryEmail("docker@github.com")
                .build();
        DockerCmdExecFactory dockerCmdExecFactory = new JerseyDockerCmdExecFactory()
                .withReadTimeout(3000)
                .withConnectTimeout(2000)
                .withMaxTotalConnections(100)
                .withMaxPerRouteConnections(10);
  List<SearchItem> list = dockerClient.searchImagesCmd("busybox").exec();
        for (SearchItem searchItem : list) {
            System.out.println(searchItem);
        }

log:
"C:\Program Files (x86)\Java\jdk1.7.0_45\bin\java" -ea -Didea.launcher.port=7532 "-Didea.launcher.bin.path=C:\Program Files (x86)\JetBrains\IntelliJ IDEA Community Edition 2016.3.2\bin" -Dfile.encoding=UTF-8 -classpath "C:\Program Files (x86)\JetBrains\IntelliJ IDEA Community Edition 2016.3.2\lib\idea_rt.jar;C:\Program Files (x86)\JetBrains\IntelliJ IDEA Community Edition 2016.3.2\plugins\junit\lib\junit-rt.jar;C:\Program Files (x86)\Java\jdk1.7.0_45\jre\lib\charsets.jar;C:\Program Files (x86)\Java\jdk1.7.0_45\jre\lib\deploy.jar;C:\Program Files (x86)\Java\jdk1.7.0_45\jre\lib\ext\access-bridge-32.jar;C:\Program Files (x86)\Java\jdk1.7.0_45\jre\lib\ext\dnsns.jar;C:\Program Files (x86)\Java\jdk1.7.0_45\jre\lib\ext\jaccess.jar;C:\Program Files (x86)\Java\jdk1.7.0_45\jre\lib\ext\localedata.jar;C:\Program Files (x86)\Java\jdk1.7.0_45\jre\lib\ext\sunec.jar;C:\Program Files (x86)\Java\jdk1.7.0_45\jre\lib\ext\sunjce_provider.jar;C:\Program Files (x86)\Java\jdk1.7.0_45\jre\lib\ext\sunmscapi.jar;C:\Program Files (x86)\Java\jdk1.7.0_45\jre\lib\ext\sunpkcs11.jar;C:\Program Files (x86)\Java\jdk1.7.0_45\jre\lib\ext\zipfs.jar;C:\Program Files (x86)\Java\jdk1.7.0_45\jre\lib\javaws.jar;C:\Program Files (x86)\Java\jdk1.7.0_45\jre\lib\jce.jar;C:\Program Files (x86)\Java\jdk1.7.0_45\jre\lib\jfr.jar;C:\Program Files (x86)\Java\jdk1.7.0_45\jre\lib\jfxrt.jar;C:\Program Files (x86)\Java\jdk1.7.0_45\jre\lib\jsse.jar;C:\Program Files (x86)\Java\jdk1.7.0_45\jre\lib\management-agent.jar;C:\Program Files (x86)\Java\jdk1.7.0_45\jre\lib\plugin.jar;C:\Program Files (x86)\Java\jdk1.7.0_45\jre\lib\resources.jar;C:\Program Files (x86)\Java\jdk1.7.0_45\jre\lib\rt.jar;D:\study\studyProject\myJavaProject\study-docker-java\target\classes;D:\tools\.m2\repository\junit\junit\4.9\junit-4.9.jar;D:\tools\.m2\repository\org\hamcrest\hamcrest-core\1.1\hamcrest-core-1.1.jar;D:\tools\.m2\repository\com\github\docker-java\docker-java\3.0.6\docker-java-3.0.6.jar;D:\tools\.m2\repository\com\fasterxml\jackson\jaxrs\jackson-jaxrs-json-provider\2.6.4\jackson-jaxrs-json-provider-2.6.4.jar;D:\tools\.m2\repository\com\fasterxml\jackson\jaxrs\jackson-jaxrs-base\2.6.4\jackson-jaxrs-base-2.6.4.jar;D:\tools\.m2\repository\com\fasterxml\jackson\core\jackson-core\2.6.4\jackson-core-2.6.4.jar;D:\tools\.m2\repository\com\fasterxml\jackson\core\jackson-databind\2.6.4\jackson-databind-2.6.4.jar;D:\tools\.m2\repository\com\fasterxml\jackson\core\jackson-annotations\2.6.0\jackson-annotations-2.6.0.jar;D:\tools\.m2\repository\com\fasterxml\jackson\module\jackson-module-jaxb-annotations\2.6.4\jackson-module-jaxb-annotations-2.6.4.jar;D:\tools\.m2\repository\org\glassfish\jersey\connectors\jersey-apache-connector\2.23.1\jersey-apache-connector-2.23.1.jar;D:\tools\.m2\repository\org\glassfish\jersey\core\jersey-common\2.23.1\jersey-common-2.23.1.jar;D:\tools\.m2\repository\javax\annotation\javax.annotation-api\1.2\javax.annotation-api-1.2.jar;D:\tools\.m2\repository\org\glassfish\jersey\bundles\repackaged\jersey-guava\2.23.1\jersey-guava-2.23.1.jar;D:\tools\.m2\repository\org\glassfish\hk2\osgi-resource-locator\1.0.1\osgi-resource-locator-1.0.1.jar;D:\tools\.m2\repository\javax\ws\rs\javax.ws.rs-api\2.0.1\javax.ws.rs-api-2.0.1.jar;D:\tools\.m2\repository\org\apache\httpcomponents\httpcore\4.4.5\httpcore-4.4.5.jar;D:\tools\.m2\repository\org\apache\httpcomponents\httpclient\4.5\httpclient-4.5.jar;D:\tools\.m2\repository\commons-logging\commons-logging\1.2\commons-logging-1.2.jar;D:\tools\.m2\repository\org\glassfish\jersey\core\jersey-client\2.23.1\jersey-client-2.23.1.jar;D:\tools\.m2\repository\org\glassfish\hk2\hk2-api\2.4.0-b34\hk2-api-2.4.0-b34.jar;D:\tools\.m2\repository\org\glassfish\hk2\hk2-utils\2.4.0-b34\hk2-utils-2.4.0-b34.jar;D:\tools\.m2\repository\org\glassfish\hk2\external\aopalliance-repackaged\2.4.0-b34\aopalliance-repackaged-2.4.0-b34.jar;D:\tools\.m2\repository\org\glassfish\hk2\external\javax.inject\2.4.0-b34\javax.inject-2.4.0-b34.jar;D:\tools\.m2\repository\org\glassfish\hk2\hk2-locator\2.4.0-b34\hk2-locator-2.4.0-b34.jar;D:\tools\.m2\repository\org\javassist\javassist\3.18.1-GA\javassist-3.18.1-GA.jar;D:\tools\.m2\repository\com\kohlschutter\junixsocket\junixsocket-common\2.0.4\junixsocket-common-2.0.4.jar;D:\tools\.m2\repository\log4j\log4j\1.2.17\log4j-1.2.17.jar;D:\tools\.m2\repository\com\kohlschutter\junixsocket\junixsocket-native-common\2.0.4\junixsocket-native-common-2.0.4.jar;D:\tools\.m2\repository\org\scijava\native-lib-loader\2.0.2\native-lib-loader-2.0.2.jar;D:\tools\.m2\repository\org\apache\commons\commons-compress\1.12\commons-compress-1.12.jar;D:\tools\.m2\repository\commons-codec\commons-codec\1.10\commons-codec-1.10.jar;D:\tools\.m2\repository\commons-lang\commons-lang\2.6\commons-lang-2.6.jar;D:\tools\.m2\repository\commons-io\commons-io\2.5\commons-io-2.5.jar;D:\tools\.m2\repository\org\slf4j\slf4j-api\1.7.21\slf4j-api-1.7.21.jar;D:\tools\.m2\repository\org\slf4j\jcl-over-slf4j\1.7.21\jcl-over-slf4j-1.7.21.jar;D:\tools\.m2\repository\com\google\guava\guava\19.0\guava-19.0.jar;D:\tools\.m2\repository\org\bouncycastle\bcpkix-jdk15on\1.54\bcpkix-jdk15on-1.54.jar;D:\tools\.m2\repository\org\bouncycastle\bcprov-jdk15on\1.54\bcprov-jdk15on-1.54.jar;D:\tools\.m2\repository\io\netty\netty-codec-http\4.1.3.Final\netty-codec-http-4.1.3.Final.jar;D:\tools\.m2\repository\io\netty\netty-codec\4.1.3.Final\netty-codec-4.1.3.Final.jar;D:\tools\.m2\repository\io\netty\netty-handler\4.1.3.Final\netty-handler-4.1.3.Final.jar;D:\tools\.m2\repository\io\netty\netty-buffer\4.1.3.Final\netty-buffer-4.1.3.Final.jar;D:\tools\.m2\repository\io\netty\netty-transport\4.1.3.Final\netty-transport-4.1.3.Final.jar;D:\tools\.m2\repository\io\netty\netty-resolver\4.1.3.Final\netty-resolver-4.1.3.Final.jar;D:\tools\.m2\repository\io\netty\netty-handler-proxy\4.1.3.Final\netty-handler-proxy-4.1.3.Final.jar;D:\tools\.m2\repository\io\netty\netty-codec-socks\4.1.3.Final\netty-codec-socks-4.1.3.Final.jar;D:\tools\.m2\repository\io\netty\netty-transport-native-epoll\4.1.3.Final\netty-transport-native-epoll-4.1.3.Final-linux-x86_64.jar;D:\tools\.m2\repository\io\netty\netty-common\4.1.3.Final\netty-common-4.1.3.Final.jar;D:\tools\.m2\repository\ch\qos\logback\logback-core\1.1.2\logback-core-1.1.2.jar;D:\tools\.m2\repository\ch\qos\logback\logback-classic\1.1.2\logback-classic-1.1.2.jar" com.intellij.rt.execution.application.AppMain com.intellij.rt.execution.junit.JUnitStarter -ideVersion5 test.DockerJavaTest,searchImagesCmd
09:44:44,653 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
09:44:44,653 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
09:44:44,653 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [file:/D:/study/studyProject/myJavaProject/study-docker-java/target/classes/logback.xml]
09:44:44,904 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
09:44:44,912 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
09:44:44,956 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
09:44:45,074 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [com.github.dockerjava] to DEBUG
09:44:45,074 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [com.github.dockerjava.jaxrs] to DEBUG
09:44:45,074 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [com.github.dockerjava.netty] to DEBUG
09:44:45,074 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.apache.http.impl.conn] to DEBUG
09:44:45,074 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
09:44:45,075 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
09:44:45,076 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
09:44:45,083 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@28388b - Registering current configuration as safe fallback point
09:44:45.823 DEBUG c.g.d.core.command.AbstrDockerCmd - Cmd: busybox,com.github.dockerjava.jaxrs.SearchImagesCmdExec@17032da
09:44:47.406 DEBUG c.g.d.j.JerseyDockerCmdExecFactory - 1 * Sending client request on thread main
1 > GET http://10.183.21.81:2375/v1.22/images/search?term=busybox
1 > Accept: application/json

09:44:47.551 DEBUG c.g.d.j.JerseyDockerCmdExecFactory$1 - Connection request: [route: {}->http://10.183.21.81:2375][total kept alive: 0; route allocated: 0 of 10; total allocated: 0 of 100]
09:44:47.586 DEBUG c.g.d.j.JerseyDockerCmdExecFactory$1 - Connection leased: [id: 0][route: {}->http://10.183.21.81:2375][total kept alive: 0; route allocated: 1 of 10; total allocated: 1 of 100]
09:44:47.593 DEBUG o.a.h.i.c.DefaultHttpClientConnectionOperator - Connecting to /10.183.21.81:2375
09:44:47.600 DEBUG o.a.h.i.c.DefaultHttpClientConnectionOperator - Connection established 10.169.89.234:57020<->10.183.21.81:2375
09:44:50.606 DEBUG o.a.h.i.c.DefaultManagedHttpClientConnection - http-outgoing-0: Close connection
09:44:50.607 DEBUG o.a.h.i.c.DefaultManagedHttpClientConnection - http-outgoing-0: Shutdown connection
09:44:50.607 DEBUG o.a.h.i.c.DefaultManagedHttpClientConnection - http-outgoing-0: Close connection
09:44:50.607 DEBUG c.g.d.j.JerseyDockerCmdExecFactory$1 - Connection released: [id: 0][route: {}->http://10.183.21.81:2375][total kept alive: 0; route allocated: 0 of 10; total allocated: 0 of 100]

javax.ws.rs.ProcessingException: java.net.SocketTimeoutException: Read timed out

	at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:481)
	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:252)
	at org.glassfish.jersey.client.JerseyInvocation$3.call(JerseyInvocation.java:724)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:444)
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:720)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:430)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.get(JerseyInvocation.java:321)
	at com.github.dockerjava.jaxrs.SearchImagesCmdExec.execute(SearchImagesCmdExec.java:30)
	at com.github.dockerjava.jaxrs.SearchImagesCmdExec.execute(SearchImagesCmdExec.java:16)
	at com.github.dockerjava.jaxrs.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:23)
	at com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:35)
	at test.DockerJavaTest.searchImagesCmd(DockerJavaTest.java:87)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:69)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:48)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:292)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:157)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:237)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.read(SocketInputStream.java:152)
	at java.net.SocketInputStream.read(SocketInputStream.java:122)
	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
	at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)
	at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:282)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:140)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:167)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:271)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:71)
	at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:435)
	... 41 more

Process finished with exit code -1

**Comment by orzeh** [comment]
@liuccc1 invoking
````java
dockerClient.searchImagesCmd("busybox").exec();
````
will search images in Docker engine, not in your private registry (see [docs](https://docs.docker.com/engine/api/v1.26/#operation/ImageSearch)). This library allows to communicate with Docker daemon not with private registries.

**Comment by liuccc1** [comment]
@orzeh 
thanks, how can i search my private registry?use which method?

**Comment by orzeh** [comment]
@liuccc1 use Docker Registry v2 API, please see SO answer: http://stackoverflow.com/questions/30113726/docker-registry-2-0-api-v2

**Comment by liuccc1** [comment]
@orzeh 
oh!  so  docker-java lib is not support search images in registry v2. I use 
curl https://docker:docker@reg.eservice.com:5000/v2/busybox/tags/list -k
to search successful.

**Comment by liuccc1** [comment]
Thanks!

**Comment by huyunhao** [comment]
As you say, you have succeed in pulling and pushing images to yourprivate docker-registry, colud you help me how to pull and push the images
