### ISSUE TITLE
Unable to deserialize status response from amazon ECR login

### ISSUE THREAD

**Issue by devshorts** [docker-java/docker-java#810]
Logging into a private ECR registry under AWS the docker client throws a deserialization error because AWS returns an extra field in the json payload:

![image](https://cloud.githubusercontent.com/assets/1799346/23728377/55f2195a-0411-11e7-8d2f-9cd53b140b9b.png)

The jackson error is:

```
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "IdentityToken" (class com.github.dockerjava.api.model.AuthResponse), not marked as ignorable (one known property: "Status"])
 at [Source: org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream@4edd8a0a; line: 1, column: 19] (through reference chain: com.github.dockerjava.api.model.AuthResponse["IdentityToken"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:62)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:834)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1093)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1477)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1455)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:282)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:140)
	at com.fasterxml.jackson.databind.ObjectReader._bind(ObjectReader.java:1583)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:964)
	at com.fasterxml.jackson.jaxrs.base.ProviderBase.readFrom(ProviderBase.java:811)
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.invokeReadFrom(ReaderInterceptorExecutor.java:256)
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.aroundReadFrom(ReaderInterceptorExecutor.java:235)
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor.proceed(ReaderInterceptorExecutor.java:155)
	at org.glassfish.jersey.message.internal.MessageBodyFactory.readFrom(MessageBodyFactory.java:1085)
	at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:874)
```

Is there a workaround? Can I configure the jackson mapper to ignore unknown fields?

**Comment by KostyaSha** [comment]
Please PR change.

**Comment by devshorts** [comment]
I'd love to, but I'm looking for a faster fix right now. Is there a possible workaround or plugin mechanism? I can submit a PR at a later date just curious if there is an extension point to work around this issue right now

**Comment by KostyaSha** [comment]
You need place annotation on model class so mapper wouldn't fail. That done almost for all classes.
