### ISSUE TITLE
at org.apache.http.pool.PoolEntryFuture.await

### ISSUE THREAD

**Issue by lecky-fu** [docker-java/docker-java#812]
**When i use the  createContainerCmd() api  method to create a container，i meet the problem below:**

`"Thread-11@4762" daemon prio=5 tid=0x33 nid=NA waiting
  java.lang.Thread.State: WAITING
	  at sun.misc.Unsafe.park(Unsafe.java:-1)
	  at java.util.concurrent.locks.LockSupport.park(LockSupport.java:186)
	  at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2043)
	  at org.apache.http.pool.PoolEntryFuture.await(PoolEntryFuture.java:139)
	  at org.apache.http.pool.AbstractConnPool.getPoolEntryBlocking(AbstractConnPool.java:307)
	  at org.apache.http.pool.AbstractConnPool.access$000(AbstractConnPool.java:65)
	  at org.apache.http.pool.AbstractConnPool$2.getPoolEntry(AbstractConnPool.java:193)
	  at org.apache.http.pool.AbstractConnPool$2.getPoolEntry(AbstractConnPool.java:186)
	  at org.apache.http.pool.PoolEntryFuture.get(PoolEntryFuture.java:108)
	  at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.leaseConnection(PoolingHttpClientConnectionManager.java:276)
	  at org.apache.http.impl.conn.PoolingHttpClientConnectionManager$1.get(PoolingHttpClientConnectionManager.java:263)
	  at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:190)
	  at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	  at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	  at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	  at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	  at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:71)
	  at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:435)
	  at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:252)
	  at org.glassfish.jersey.client.JerseyInvocation$2.call(JerseyInvocation.java:701)
	  at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	  at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	  at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
	  at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:444)
	  at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:697)
	  at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:448)
	  at org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:349)
	  at com.github.dockerjava.jaxrs.CreateContainerCmdExec.execute(CreateContainerCmdExec.java:34)
	  at com.github.dockerjava.jaxrs.CreateContainerCmdExec.execute(CreateContainerCmdExec.java:15)
	  at com.github.dockerjava.jaxrs.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:23)
	  at com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:35)
	  at com.github.dockerjava.core.command.CreateContainerCmdImpl.exec(CreateContainerCmdImpl.java:177)
	  at dockerDao.ContainerDao.createTomcatContainer(ContainerDao.java:71)
	  at dockerService.DockerManageService.createTomcatContainer(DockerManageService.java:93)
	  at servlet.ActionServlet$2.run(ActionServlet.java:153)
	  at java.lang.Thread.run(Thread.java:745)`

My thread has been blocked an this place,how can i do with it?

**Comment by marcuslinke** [comment]
Seems you have to increment max connections setting. See https://github.com/docker-java/docker-java/wiki#intialize-docker-client-advanced how to do it.

**Comment by lecky-fu** [comment]
thank you, i hava just solve the problem like this.

**Comment by MoyuSha** [comment]
Excuse me,that link dosen't work , I am using docker-java 3.2.1 and I have encountered  similar problems. Here is the stack info:
`#2038 prio=5 os_prio=0 tid=0x00007f3104086800 nid=0x474e waiting on condition [0x00007f30ed47a000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000000b8592ca8> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at org.apache.http.pool.AbstractConnPool.getPoolEntryBlocking(AbstractConnPool.java:377)
	at org.apache.http.pool.AbstractConnPool.access$200(AbstractConnPool.java:67)
	at org.apache.http.pool.AbstractConnPool$2.get(AbstractConnPool.java:243)
	- locked <0x00000000ba6c72d0> (a org.apache.http.pool.AbstractConnPool$2)
	at org.apache.http.pool.AbstractConnPool$2.get(AbstractConnPool.java:191)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.leaseConnection(PoolingHttpClientConnectionManager.java:282)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager$1.get(PoolingHttpClientConnectionManager.java:269)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:191)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
	at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:480)
	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:296)
	at org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$0(JerseyInvocation.java:609)
	at org.glassfish.jersey.client.JerseyInvocation$$Lambda$113/2125901086.call(Unknown Source)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:205)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:390)
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:608)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:421)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:327)
	at com.github.dockerjava.jaxrs.JerseyInvocationBuilder.postStream(JerseyInvocationBuilder.java:173)
	at com.github.dockerjava.core.exec.LoadImageCmdExec.execute(LoadImageCmdExec.java:24)
	at com.github.dockerjava.core.exec.LoadImageCmdExec.execute(LoadImageCmdExec.java:10)
	at com.github.dockerjava.core.exec.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:21)
	at com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:35)
	at com.hero.lte.ems.utils.DockerUtils.pushImage(DockerUtils.java:121)`
