### ISSUE TITLE
Stdin not working

### ISSUE THREAD

**Issue by xuchenCN** [docker-java/docker-java#859]
I trying to use docker-java to exec /bin/bash , and continuously to send some command like a standard terminal 
And using NettyDockerCmdExecFactory
Got exception trace 

`Exception in thread "main" java.lang.ExceptionInInitializerError
	at io.netty.channel.epoll.IovArray.<clinit>(IovArray.java:57)
	at io.netty.channel.epoll.EpollEventLoop.<init>(EpollEventLoop.java:62)
	at io.netty.channel.epoll.EpollEventLoopGroup.newChild(EpollEventLoopGroup.java:130)
	at io.netty.channel.epoll.EpollEventLoopGroup.newChild(EpollEventLoopGroup.java:35)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:84)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:58)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:47)
	at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:58)
	at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:100)
	at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:87)
	at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:64)
	at com.github.dockerjava.netty.NettyDockerCmdExecFactory$UnixDomainSocketInitializer.init(NettyDockerCmdExecFactory.java:229)
	at com.github.dockerjava.netty.NettyDockerCmdExecFactory.init(NettyDockerCmdExecFactory.java:203)
	at com.github.dockerjava.core.DockerClientImpl.withDockerCmdExecFactory(DockerClientImpl.java:161)
	at com.github.dockerjava.core.DockerClientBuilder.build(DockerClientBuilder.java:45)
	at docker_client_test.docker_client_test.TesContianerExec.main(TesContianerExec.java:23)
Caused by: java.lang.IllegalStateException: Only supported on Linux
	at io.netty.channel.epoll.Native.loadNativeLibrary(Native.java:267)
	at io.netty.channel.epoll.Native.<clinit>(Native.java:64)
	... 16 more`

My OS is Mac OSX

**Comment by fengxx** [comment]
Right now NettyDockerCmdExecFactory support linux-x86_64 only.
```
	<dependency>
		<groupId>io.netty</groupId>
		<artifactId>netty-transport-native-epoll</artifactId>
		<version>${netty.version}</version>
		<classifier>linux-x86_64</classifier>
	</dependency>
````

However upstream (Netty) does support macOS via KQueueEventLoop 
maven artifact

```
    <dependency>
      <groupId>io.netty</groupId>
      <artifactId>netty-transport-native-kqueue</artifactId>
      <version>${netty.version}</version>
      <classifier>macos-x86_64</classifier>
    </dependency>

````
See more details, please checkout [native-transports](http://netty.io/wiki/native-transports).

To add macOS support, I think it can be done via a new maven module to avoid bing unnecessary to the main project

**Comment by xuchenCN** [comment]
@fengxx Thanks for reply ,
actually I tried netty-transport-native-kqueue on osx ,
but still encountered class not found exception "EpollEventLoopGroup" .

So want to use **stdin**  in docker-java NettyDockerCmdExecFactory is necessary?

**Comment by fengxx** [comment]
Epoll is for linux,  KQueue for Mac
```
EpollEventLoopGroup -> KQueueEventLoopGroup
EpollEventLoop -> KQueueEventLoop
EpollServerSocketChannel -> KQueueServerSocketChannel
EpollSocketChannel -> KQueueSocketChannel
```

**Comment by xuchenCN** [comment]
@fengxx I mean my environment for development on OSX , product on Linux .
In this situation I must be test my code on Linux ?

**Comment by xuchenCN** [comment]
Hi @marcuslinke  I saw u commit a branch of **netty-unixsocket-experiment** that still in the phase of experiment?

**Comment by marcuslinke** [comment]
@xuchenCN Yes, this one was experimental where I replaced netty with jnr-unixsocket. As netty officially supports KQueue since v4.1.11 this is outdated now. There is another branch with https://github.com/docker-java/docker-java/blob/netty-native-kqueue/src/main/java/com/github/dockerjava/netty/NettyDockerCmdExecFactory.java implementing the same with netty 4.1.7.Final-SNAPSHOT. So basically it would need to update netty dependencies in master branch to 4.1.11 and use the ```NettyDockerCmdExecFactory.java ``` from that branch.

**Comment by xuchenCN** [comment]
@marcuslinke since I was using both of OSX and Linux , so that branch you mentioned will compatible automatically?

**Comment by marcuslinke** [comment]
@xuchenCN I've prepared a local branch that does the needed modifications but unfortunatly I found an issue. See https://github.com/netty/netty/issues/6837

**Comment by xuchenCN** [comment]
@marcuslinke I encountered that issue when I test on OSX 10.11.x , and I think netty won't fix this issue recently . So I prefer using your current branch to develop my project , If there is any updates please let me know .
Danke!

**Comment by marcuslinke** [comment]
The netty-native-kqueue branch is based on a local build of netty 4.1.7.Final-SNAPSHOT and does support MacOS only (no linux support). When netty is build on my MacOS 10.11.x it worked of course with that OS version and probably also with versions > 10.11.x. The problem is that the netty guys have build their release version with MacOS Sierra so it doesn't work with older versions anymore. We will see if this get fixed somehow.
