### ISSUE TITLE
Getting NoSuchMethodError error  in waitContainerCmd  

### ISSUE THREAD

**Issue by nagnath-sawant** [docker-java/docker-java#864]
I am witting code in java for wait a container. following is my java code:
 
`		dockerClient.startContainerCmd(container.getId()).exec();

		System.out.println("Container "+ containerName +" has been started");

		System.out.println("Waiting for a container to execute");

		int exitCode = dockerClient.waitContainerCmd(container.getId())

		.exec(new WaitContainerResultCallback()).awaitStatusCode();	
	
		System.out.println("Exit status code of Wait container is :" +exitCode );

		dockerClient.removeContainerCmd(container.getId()).exec();`

I have tried with different version of jackson library. Still getting this issue:
`Create container responsecom.github.dockerjava.api.command.CreateContainerResponse@3c0fbd3a[id=6689bc5cbe78cf5d2fc246d7b3bcca48cbafb08635fa0638a77de7ba83fb5f26,warnings=<null>]
Container word-count-application has been started
Waiting for a application to execute
Exception in thread "main" ERROR 2017-06-16 17:30:36,252 [dockerjava-jaxrs-async-0] com.github.dockerjava.core.async.ResultCallbackTemplate: Error during callback
java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.node.ObjectNode.isEmpty(Lcom/fasterxml/jackson/databind/SerializerProvider;)Z
	at com.github.dockerjava.core.async.JsonStreamProcessor.processResponseStream(JsonStreamProcessor.java:47) ~[docker-java-3.0.10.jar:?]
	at com.github.dockerjava.jaxrs.async.AbstractCallbackNotifier.call(AbstractCallbackNotifier.java:66) ~[docker-java-3.0.10.jar:?]
	at com.github.dockerjava.jaxrs.async.AbstractCallbackNotifier.call(AbstractCallbackNotifier.java:24) ~[docker-java-3.0.10.jar:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_111]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.node.ObjectNode.isEmpty(Lcom/fasterxml/jackson/databind/SerializerProvider;)Z
	at com.github.dockerjava.core.async.JsonStreamProcessor.processResponseStream(JsonStreamProcessor.java:47)
	at com.github.dockerjava.jaxrs.async.AbstractCallbackNotifier.call(AbstractCallbackNotifier.java:66)
	at com.github.dockerjava.jaxrs.async.AbstractCallbackNotifier.call(AbstractCallbackNotifier.java:24)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
`
Please Help.
Thanks

**Comment by orzeh** [comment]
@nagnath-sawant it is probably Jackson library version conflict. Do not add direct reference to it from your build script - it will be included as transient dependency of `docker-java`.

Your issue is not specific to `docker-java` but rather general Java classpath / build tool problem. Maybe post on StackOverflow to get help.
