### ISSUE TITLE
Error during callback

### ISSUE THREAD

**Issue by Beautifulmind20** [docker-java/docker-java#886]
I am facing the following problem while running Gradle task. I am not sure what exactly this means. Can someone help me out with this?  I am behind the proxy
Details are here:- 
Docker version Docker version 17.06.0-ce
Gradle 3.4.1

**gradle task :-** 
`  tag 'myaddress/env/java'

    baseImage 'centos'

    if (proxy) {
        setEnvironment 'http_proxy', proxy
        setEnvironment 'https_proxy', proxy
    }

    addFile file('base/jdk-8u131-linux-x64.rpm'), '/tmp'

    runCommand 'yum -y update'
    runCommand 'yum -y install bc unzip'
    runCommand 'rpm -i /tmp/jdk-8u131-linux-x64.rpm && rm -f /tmp/jdk-8u131-linux-x64.rpm'
    setEnvironment 'JAVA_HOME', '/usr/java/default'`

**Error is here:-** 
`Error during callback
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "aux" (class com.github.dockerjava.api.model.BuildResponseItem), not marked as ignorable (9 known properties: , "stream", "error", "from", "progress", "time", "status", "errorDetail", "id", "progressDetail"])
 at [Source: com.github.dockerjava.jaxrs.util.WrappedResponseInputStream@3c676c45; line: 24, column: 9] (through reference chain: com.github.dockerjava.api.model.BuildResponseItem["aux"])
        at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:79)
        at com.fasterxml.jackson.databind.DeserializationContext.reportUnknownProperty(DeserializationContext.java:579)
        at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:672)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:906)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:328)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:121)
        at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:2769)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:1478)
        at com.github.dockerjava.core.async.JsonStreamProcessor.processResponseStream(JsonStreamProcessor.java:44)
        at com.github.dockerjava.jaxrs.async.AbstractCallbackNotifier.call(AbstractCallbackNotifier.java:62)
        at com.github.dockerjava.jaxrs.async.AbstractCallbackNotifier.call(AbstractCallbackNotifier.java:22)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
:dockerBase FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task 'xyz'.
> Could not build image: null

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
`

**Comment by noor-siddique-m4** [comment]
Why did you close this issue? I am also experiencing same issue! Did you solve the issue? If yes then how?

**Comment by KostyaSha** [comment]
Please report errors firstly to projects that you are using, not to library with unknown version and code using it.
